### ISSUE TITLE
Feature Request: Flagging proofreading questions on ELU

### ISSUE THREAD

**Issue by MarcelloTheArcane** [Charcoal-SE/SmokeDetector#1000]
In [English.SE](https://english.stackexchange.com), we get a few questions with the following style:
> Block of text, with very little if no paragraph formatting
> Generally capitals in the first sentence
> Contains either IELTS or TOEFL in the title
> Says something like '*Hi everyone. I start to learn TOFFEL writing and I have lots of mistake. Could you find out and fix them for me?*' in the title
> Tags like: [[grammar](https://english.stackexchange.com/questions/tagged/grammar)], [[punctuation](https://english.stackexchange.com/questions/tagged/punctuation)], [[spelling](https://english.stackexchange.com/questions/tagged/spelling)]

A few examples: <sup>I think a few might have been deleted, but I'm a sub-10k user.</sup>
- https://english.stackexchange.com/questions/404087/hi-everyone-i-start-to-learn-toffel-writing-and-i-have-lots-of-mistake-could-y
- https://english.stackexchange.com/questions/403750/im-praticing-the-ielts-task-1-and-id-like-you-have-a-look-at-my-writing-thank

**Is there something SmokeDetector could do to flag these types of questions?**

**Comment by angussidney** [comment]
SmokeDetector only deals with spam and abusive posts, so if the posts you're trying to catch/flag are simply off-topic, than we're not really the right people to be talking to sorry :)

Of course, all our code is open source and you're free to build your own bot based on it. If you need help we're always happy to answer questions. Additionally, the folks over at [SOBotics](https://chat.stackoverflow.com/rooms/111347/sobotics) have build a bunch of bots which conduct a variety of tasks on SO, so if you drop in there maybe someone can help you out.

**Comment by ArtOfCode-** [comment]
I adapted Smokey to do something similar to this on ELU not long ago, so it's certainly possible to use the bot to do this kind of thing. "The" SmokeDetector, however, only focuses on spam, like Angus said.

**Comment by MarcelloTheArcane** [comment]
Okay, thanks for the advice @angussidney. I'll check SOBotics and the source code out...
