### ISSUE TITLE
Blacklisting or watching soon after restart fails

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1026]
This has happened to me multiple times last week, and again today just now.

Example: at https://chat.stackexchange.com/transcript/message/39523256#39523256  is a `!!/watch` request which is ignored. I posted it some 20 seconds after the "Restart: API quota" message in the hopes that it would work, but apparently I didn't wait long enough.

My next attempt to watch the same domain failed again, apparently because of some sort of (silent) Smoke Detector crash.

Finally at https://chat.stackexchange.com/transcript/message/39523609#39523609  I managed to successfully get it watched.

**Comment by quartata** [comment]
There's actually a decent chance this is a ChatExchange issue, and not specific to `!!/watch`. I've observed odd glitches when posting commands right after the startup message, even in NG (presumably due to the fact that the watcher hasn't fully initialized yet).

**Comment by angussidney** [comment]
Has this been recently reproduced?
