### ISSUE TITLE
Option to run Smoke Detector chatless/metasmokeless/gitless

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1028]
For testing, it would be beneficial if Smoke Detector could be run in a completely local mode, i.e. with output only to the console, and no connection to various back-end services which it normally communicates with.

Ideally, the services it uses should be individually selectable, but for a start, a way to disable them all would encourage experimentation and perhaps even allow more people to participate in its development because setting up a private instance is both less visible (and so less embarrassing if you make silly mistakes, or have weird experiments which would pollute the chat room inordinately) as well as less technically intimidating.

---

- [x] Chatless
- [x] Metasmokeless
- [ ] Gitless

**Comment by ArtOfCode-** [comment]
Obligatory sarcastic "edit your hosts file"...

But in seriousness, we're almost there already. Git and metasmoke are already entirely optional - just don't put them in config if you don't want them. Chat is less optional, but someone (Thomas) made a start on a no-chat mode that could be finished up.

**Comment by teward** [comment]
I'm happy to try and build a chat-less mode, but it'll be a little tricky to build.  You can assign this to me in the mean time - we have such heavy chat integration for things, that I'll have to do some overhauling just to get this part working.  I also don't think I have any work on the no-chat mode, I only had fixes for 'failed to login to chat' issues.

**Comment by quartata** [comment]
Chatless is trivial in the NG PR with an empty rooms.yml.

**Comment by angussidney** [comment]
The 'gitless' point (which I'm assuming means using git for read-only tasks) should be complete when #1280 is merged.

**Comment by quartata** [comment]
I'd say we're already decently Metasmoke-less as well
