### ISSUE TITLE
Generated PRs have broken search for users who are not logged in

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1032]
The link to a metasmoke search in generated PRs (for example, just now, #1031) is useful, but the behavior when you try to visit from e.g. a mobile phone where you are not logged into Metasmoke is just a JSON error message.

Approximation:
```
tripleee$ curl 'https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=garagedoorsrepairnoblesville.com'
{"error":"Unauthenticated users cannot use regex search"}
```

Perpaps at least the error message should be slightly more human-friendly, perhaps with an option to log in?

**Comment by ArtOfCode-** [comment]
Huh. That error message shouldn't show up unless the request is for JSON format, which that link isn't. That's a metasmoke bug, I'll take a look.

**Comment by angussidney** [comment]
Simple smokey-side fix: remove the `&body_is_regex=1` option from the generated URL, since Smokey appears to be adding the non-regex version of the blacklist item to the MS URL anyway.
