### ISSUE TITLE
Dockerfile still refers to Python 2.7

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1047]
The Dockerfile should be updated to Python 3.

Its purpose should probably be clarified, too.  It would be nice if it had all the functionality to run a production Smokey instance.

**Comment by tripleee** [comment]
I'm not sure what exactly is required to run a prod instance. It should `git checkout deploy` and have the configuration file with the keys.  Anything else?

**Comment by Undo1** [comment]
Credentials are the biggest thing. Maybe we could have an encrypted config file, with the password distributed to trusted folks as we do now with individual creds?

**Comment by angussidney** [comment]
@Undo1 do you mean have everything pre-entered but encrypted, and then provide a password to unlock it? That won't necessarily work all the time, given that MS keys are separate and we don't always want to use the main Smokey account. 

A simple interactive program which directly prompts for SE username/pass (via CE), MS Key, GH creds, and location would allow more flexibility.

**Comment by Undo1** [comment]
Good catch. Would be possible to split the file, but that's likely more trouble than it's worth.

**Comment by tripleee** [comment]
The merge a week ago solved this.
