### ISSUE TITLE
Prevent accidental deletion of Smokey chat messages in Charcoal HQ

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1071]
Suggested by @j-f1 here:
https://chat.stackexchange.com/transcript/11540?m=39866998#39866998

> Should we change the `sd delete|poof|gone` commands in CHQ to say something like ”Messages from SmokeDetector in Charcoal HQ are generally kept as records. If you really need to delete a message, please use `sd delete-force` [wiki link for more info](some URL)?”

**Comment by angussidney** [comment]
Basic spec: edit existing chat sub-command to check chatroom and post warning if necessary; create new chat sub-command which is a duplicate of the old command.

**Comment by tripleee** [comment]
As far as I can tell, this was completely covered by #1138
