### ISSUE TITLE
Avoid catching the same post if it hasn't been modified since last report

### ISSUE THREAD

**Issue by AjayBrahmakshatriya** [Charcoal-SE/SmokeDetector#1085]
On several occasions one sees the disambiguation screen on MS because there are multiple reports for a single posts. But many times the contents of the post are exactly the same since the last report. 

SmokeDetector can simply filter our such cases by comparing the last reported time with the last modified time of the post. Even better if it can do an exact string matching from the last report (to avoid change + rollbacks changing the modified time).

One instance of such a case is [here](https://metasmoke.erwaysoftware.com/posts/by-url?url=//dba.stackexchange.com/a/131273). 

The answer has never been edited and also has been marked as fp or naa on all the occasions. 
It was caught just because Community boosted the post.

**Comment by angussidney** [comment]
Alternatively we could just use the revision number, since we already get that from the API AFAIK
