### ISSUE TITLE
add a command for tpu and delete

### ISSUE THREAD

**Issue by K-Guan** [Charcoal-SE/SmokeDetector#110]
Looks like we haven't a command can run `tpu and delete` yet, I mean if I need make a message as `tpu` and delete it I need:

```
sd tpu
sd deleted
```

What about add a command like `tp[u]d[-]` or `tp[u]del[-]`?

**Comment by BrockA** [comment]
I don't like it.  Other people can flag spam; what if they don't see it before you delete the chat message?

I've seen after-hours spam stick around for up to a day.  (Or much much longer on the Russian site).

Revisiting chat, I routinely check old Smokey messages and often find some that are a few screens back, that still need flags.
I'm sure I'm not the only one. That can't happen if someone deletes Smokey's posts in the very short window that chat even allows messages to be deleted.

**Comment by K-Guan** [comment]
@BrockA  Yeah I know, the command is use for when someone see a post should be make as `tpu` and it has been deleted. For example I always see a post be deleted when I flag it as spam(6 spam flag delete a post, yeah that is), then I need say `tpu` and `deleted` to Smoke. 

However I don't recommend use `delete` or this command if a post hasn't been be deleted.

**Comment by ArtOfCode-** [comment]
More to the point, there's only a very small window in which this command is useful - Smokey's not a moderator-level user, so it can't delete its messages beyond something like 2 minutes back (may be 5).

**Comment by Undo1** [comment]
Yep 2 minutes. I don't think this would be terribly useful, although I
wouldn't be completely against it either.

**Comment by K-Guan** [comment]
Sure, but looks like sometimes a post can be delete before the 2min-edge. So if we add this command then we don't need run two commands.

> By the way, what about auto delete a message if a post has been deleted?
