### ISSUE TITLE
Document build infrastructure

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1155]
I don't think I have seen proper documentation for how the two CI systems are being used and what triggers are supposed to launch e.g. merges from `master` to `deploy` and where this is supposed to happen.

Ref. also #1154 just now.

**Comment by angussidney** [comment]
More importantly, I think instructions on how to fix master/deploy merge conflicts should be written down somewhere

**Comment by tripleee** [comment]
I think we are good now; Angus and Art solved it.  Apparently the root cause was a stray commit on the deploy branch.

**Comment by ArtOfCode-** [comment]
https://charcoal-se.org/smokey/Build-Infrastructure
