### ISSUE TITLE
Create a todo list maintained by Smokey

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#1167]
As [suggested](https://chat.stackexchange.com/transcript/message/40707684#40707684) by @surajrao:

> Possible feature request: SD maintain charcoal todo list

Smokey (or another bot) could monitor chat for messages indicating bugs, FRs, etc, and post a ticket in a new [project](https://github.com/Charcoal-SE/SmokeDetector/projects) dedicated to TODOs. Even better, it would detect which repo (SD, MS, US or website) and post the ticket in the appropriate one.

That way, joke/status-denied tickets wouldn't be turned into a full GH issue, and good ideas can easily be converted to a proper issue with discussion at the appropriate time.

**Comment by AWegnerGitHub** [comment]
I don't like this idea at all. GH issues are for exactly this type of thing. If something is created as a joke, then close the issue. Splitting where we store what we want to work on is only going to make figuring out what we want to do more difficult.

**Comment by Undo1** [comment]
Also disagree - we'd want to establish something the current system doesn't do. Main 'issues' we have now is that it requires a GitHub account and knowledge of where the 'create issue' button is. Not too high a bar, really. Also, it's probably good to have denied tickets here in a place we can easily link them.

For joke issues... pallet-of-bricks enforcement works well, and we haven't had an issue with it that I've seen (could be missing something).
