### ISSUE TITLE
Multiple instances need to have their local master reset

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1219]
We had an issue yesterday #1213 where branch protection was briefly enabled in Smoke Detector's Github repository. This caused git operations to fail because the instance was not allowed to push to `master`.

As the result of this, at least teward/Solar Flare and NobodyNada/Raspberry Pi have unmerged commits on their `master` branch.

The simple and straightforward fix is probably to delete the local `master` and start over. You will lose some unmerged commits but they never made it to production anyway. Maybe check if there is something which needs to be resubmitted separately before you zap the master.

At least these instances need to be fixed:
* @teward Solar Flare - chat transcript https://chat.stackexchange.com/transcript/message/41063836#41063836
* @NobodyNada Raspberry Pi - chat transcript https://chat.stackexchange.com/transcript/message/41063871#41063871

**Comment by quartata** [comment]
This is a good example of why we shouldn't mess with local master until after we push successfully.

**Comment by tripleee** [comment]
Calling this done now; there could be instances left which still need this but I think we have the situation pretty much handled (and if something is broken now, it could be something else, too).
