### ISSUE TITLE
Adjust blacklist/watchlist functionality to utilize Helios

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#1280]
The changes to utilize Helios are:

- [ ] Remove blacklists and watchlists from the repository
- [ ] Ignore those files in `.gitignore`
- [ ] Call the Helios endpoints at startup and promotion from standby to pull blacklists and write these lists to the local files that were previously removed from the repository
- [ ] When writing a new blacklist record, write to the local file
- [ ] When writing a new blacklist record, follow the procedure outlined [here](https://github.com/Charcoal-SE/metasmoke/issues/289) if the user doesn't have permissions to directly create a blacklist item. This will involve either a call to Helios itself with a flag indicating it's not active yet or a call to metasmoke for approval
- [ ] When writing a new blacklist record, if the user has permissions, call the appropriate Helios endpoint to add the new record

---

- [ ] Adjust the `!//pull` command or add a new command (ie. `!//update-blacklists`) to pull all lists from Helios and over write the local cache files

**Comment by quartata** [comment]
Might be worth combining these issues into one "refactor datahandling" list
