### ISSUE TITLE
Fix wiki link to metasmoke admins

### ISSUE THREAD

**Issue by thetrentus** [Charcoal-SE/SmokeDetector#1286]
Please fix the link in the wiki to the metasmoke admin list. 

https://charcoal-se.org/smokey/Privileges

It appears to go to the permissions manager it is restricted to admins only and not the list of admins. Please rectify this. Thank you

**Comment by tripleee** [comment]
Chat link:

https://chat.stackexchange.com/transcript/message/41380546#41380546

**Comment by tripleee** [comment]
I tweaked the wording and added a link to /pings/ near the top of the page.  I see now that there is a separate link to /people#admins slightly lower down on the page.  Anyway, calling this done.

**Comment by tripleee** [comment]
For the record, commits https://github.com/Charcoal-SE/charcoal-se.github.io/commit/ad647492665cc17533d104f1329c6b30af2fd2c4 and https://github.com/Charcoal-SE/charcoal-se.github.io/commit/f9f152e76045cac35c3ce9fa824291003852c57a

**Comment by j-f1** [comment]
You can see the actual changes here: https://github.com/Charcoal-SE/SmokeDetector/wiki/Privileges/_compare/e435339ed7d2dfe6bd62010e0169c31b2b1668ae...c804a73d80ca97f3295916724c252ef45fe02031
