### ISSUE TITLE
Relicense under dual MIT/Apache 2.0

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/SmokeDetector#129]
We currently don't have a specified license for SmokeDetector - and thus, by default, it is under full copyright. This is very restrictive, and we'd like to change it to something more permissive (in this case, dual licensed under MIT/Apache 2.0). We'll need consent from all contributors to this repository to do so:

 - [x] @ProgramFOX
 - [x] @normalhuman
 - [x] @hichris1234
 - [x] @Undo1
 - [x] @Manishearth
 - [x] @BrockA
 - [x] @rschrieken
 - [x] @AWegnerGitHub
 - [x] @Seth-Johnson
 - [x] @JC3
 - [x] @rekire
 - [x] @durron597
 - [x] @AstroCB
 - [x] @Siguza
 - [x] @ArcticEcho
 - [x] @K-Guan
 - [x] @ByteCommander
 - [x] @TheGuywithTheHat
 - [x] @apnorton
 - [x] @michaelb958
 - [x] @ndrewh

To agree to relicensing, just leave this comment below or otherwise indicate consent:

    I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

Some more info:

This involves adding the following to the README and including the full text of both licenses in the repository:

    ## License

    Licensed under either of

     * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
     * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

    at your option.

    ### Contribution

    Unless you explicitly state otherwise, any contribution intentionally submitted
    for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any
    additional terms or conditions.

MIT is fairly permissive, so it's preferred by most, however it requires you to include the license in everything using the code. On the other hand, Apache doesn't have this issue, but is incompatible with GPLv2. A dual license gives users the freedom to choose a license of their choice.

**Comment by Undo1** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by hichris1234** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by TheGuywithTheHat** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Manishearth** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by AstroCB** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by rekire** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Siguza** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ndrewh** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by normalhuman** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by BrockA** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Seth-Johnson** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by durron597** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by AWegnerGitHub** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ProgramFOX** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by K-Guan** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ArcticEcho** [comment]
I license all past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees (and unicorns) to choose either at their option.

**Comment by ProgramFOX** [comment]
@ByteCommander also agrees (commenting for him because he doesn't have his GH account at hand currently):
http://chat.stackoverflow.com/transcript/message/28343567#28343567

**Comment by apnorton** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by JC3** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option. I license your mom under the same terms.

**Comment by rschrieken** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by michaelb958** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by makyen** [comment]
@ndrewh A comment of yours was deleted here due to an issue of it containing PII. Unfortunately, that leaves us with no record here that you agreed to license your contributions as described in the initial Issue comment here. If you're willing, it would be appreciated if you could restate your willingness to license your prior contributions, as described above. Thanks.

**Comment by ndrewh** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ndrewh** [comment]
@makyen Since this was 5 years ago I'm very curious what I wrote. Would you be able to have someone email me (github.ndrewh@gmail.com) the content of the comment? Yikes

**Comment by makyen** [comment]
@ndrewh I didn't see it and there's no access to deleted comments (as far as I know), so I can't. As I understand it, it was PII of a different individual, not you.
