### ISSUE TITLE
"already recently reported" links are formatted badly in chat

### ISSUE THREAD

**Issue by paulroub** [Charcoal-SE/SmokeDetector#1303]
The nested brackets seem to throw off the renderer.  The first bracket is seen as part of the link, not the second.

    [[MS](https://m.erwaysoftware.com/posts/by-url?url=//stackoverflow.com/a/475980‌​16)]

ends up as this HTML:

    <a href="https://m.erwaysoftware.com/posts/by-url?url=//stackoverflow.com/a/47598016">[MS</a>]

*(extra, unrelated, attributes removed for readability)*

Adding spaces (as in the `[ SmokeDetector | MS ]` blocks) would solve the problem.

**Comment by j-f1** [comment]
Adding a `\u200b` character (`​`) might also fix it.
