### ISSUE TITLE
Invalid .pullapprove.yml

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1345]
Chasing the error message on pullapprove.com is incredibly complex IMHO.

I see **'hichris1234' is not a collaborator of this repo** in the error message at https://pullapprove.com/Charcoal-SE/SmokeDetector/

I imagine the correct fix is to mark hichris1234 as a collaborator in GitHub.

**Comment by tripleee** [comment]
I temporarily removed hichris1234 from .pullapprove.yml but I'll leave this open for visibility and discussion. Ideally I'd like to be able to uncomment the fix.

**Comment by NobodyNada** [comment]
@tripleee This happened when I was added to that list as well.  IIRC, the fix was to add me to the OAP team of the Charcoal org.

**Comment by tripleee** [comment]
Yeah, but Chris was there like forever, was he recently removed from the org on GitHub, or what?

**Comment by tripleee** [comment]
hichris1234 is now @csnardi apparently.  Thanks to @ArtOfCode- for the explanation.

https://chat.stackexchange.com/transcript/message/41596394#41596394
