### ISSUE TITLE
Replying `n` to a chat message doesn't record feedback anymore

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#1362]
Case in point: https://chat.stackexchange.com/transcript/message/41641607#41641607

As [quartata suggested](https://chat.stackexchange.com/transcript/message/41641642#41641642), replying `naa-` does work, e.g. [here](https://chat.stackexchange.com/transcript/message/41648584#41648584).

**Comment by quartata** [comment]
This is a Metasmoke inconsistency -- normally with most feedbacks, only the first letter matters -- e.g. if it starts with t then it's a tp, if it starts with f then it's an fp But naa appears to have to be exactly naa.

**Comment by ArtOfCode-** [comment]
Metasmoke inconsistency, but still a Smokey bug :)

**Comment by Glorfindel83** [comment]
I have a history of posting metasmoke bugs on the SmokeDetector project and vice versa ...

Anyway, the problem seems to extend to `k` as well:
https://chat.stackexchange.com/transcript/message/41653240#41653240

**Comment by angussidney** [comment]
Ideally, for the sake of consistency we’d like to continue using the old behaviour. i.e. everything is extended to tpu-, naa- etc

**Comment by quartata** [comment]
The `k` not working was due to your notes after it which were interpreted as part of the command, that's a separate thing. I'll fix both later today.
