### ISSUE TITLE
Website (metasmoke.erwaysoftware.com) gives a 503 service unavailable Error.

### ISSUE THREAD

**Issue by JonasCz** [Charcoal-SE/SmokeDetector#137]
The website (https://metasmoke.erwaysoftware.com/), linked from the description of this github repo is broken, It gives me a "503 Service Unavailable" error page. Would be nice if it worked :-)

**Comment by normalhuman** [comment]
Yes, this is a recurring issue, but it belongs to https://github.com/Charcoal-SE/metasmoke
