### ISSUE TITLE
test_unshorten_link is failing

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#1423]
test_unshorten_link is failing in recent builds: https://travis-ci.org/Charcoal-SE/SmokeDetector/builds/322787010

```
=================================== FAILURES ===================================
_____ test_unshorten_link[https://goo.gl/kAb9rz-https://charcoal-se.org/] ______
shortened = 'https://goo.gl/kAb9rz', original = 'https://charcoal-se.org/'
    @pytest.mark.parametrize('shortened, original', [
        ('https://goo.gl/kAb9rz', 'https://charcoal-se.org/'),
        ('https://bit.ly/2jhMbxn', 'https://charcoal-se.org/'),
        ('https://tinyurl.com/y7ba4pth', 'https://charcoal-se.org/'),
        ('https://tiny.cc/gsbbpy', 'https://charcoal-se.org/')
    ])
    def test_unshorten_link(shortened, original):
>       assert helpers.unshorten_link(shortened) == original
E       AssertionError: assert 'https://goo.gl/kAb9rz' == 'https://charcoal-se.org/'
E         - https://goo.gl/kAb9rz
E         + https://charcoal-se.org/
test/test_helpers.py:12: AssertionError
------------------------------ Captured log call -------------------------------
connectionpool.py          824 DEBUG    Starting new HTTPS connection (1): goo.gl
connectionpool.py          396 DEBUG    https://goo.gl:443 "HEAD /kAb9rz HTTP/1.1" 405 0
==================== 1 failed, 222 passed in 12.12 seconds =====================
```

I am unable to replicate this failure locally. 

It doesn't appear to be rate limiting related (at least, I can't get my local environment rate limited by rapidly hitting this URL).

It seems like it's failing through [this](https://github.com/Charcoal-SE/SmokeDetector/blob/603e3b138c38f70fd331472b30be160ddf598605/helpers.py#L63) `while` loop by getting an `HTTP 405` and returning the original shortened URL.

**Comment by Undo1** [comment]
405 is Method Not Allowed. Did a GET turn into a POST or something?

**Comment by quartata** [comment]
This does not occur on Circle CI, only Travis.

**Comment by ArtOfCode-** [comment]
@Undo1 -

    host           port   request_string          resp_code bytes
    https://goo.gl:443    "HEAD /kAb9rz HTTP/1.1" 405       0

So for whatever reason, `goo.gl` is issuing Method Not Allowed for a `HEAD` request. I have a nasty suspicion that Travis is clobbering our custom User-Agent and replacing it with their own, and Google is denying requests from Travis because they're automated. Will do some testing to find out.

**Comment by ArtOfCode-** [comment]
Theory annoyingly disproved:

![selection_059](https://user-images.githubusercontent.com/10406565/34449250-55ce6278-ecee-11e7-9d18-6d83c99aece6.png)

**Comment by AWegnerGitHub** [comment]
Did we fix this or did it just stop happening?

**Comment by ArtOfCode-** [comment]
I think it just stopped happening - bug on Google's side, maybe
