### ISSUE TITLE
Send post tags to metasmoke

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/SmokeDetector#1426]
Ref: Charcoal-SE/metasmoke#283

There is now a field for tags in the MS database; Smokey should send that information to metasmoke. It can be sent as an array in the post creation request; MS will serialize the array and store it.

**Comment by Undo1** [comment]
Do we have post tag information? Trying to remember if the API returns it in a convenient (semicolon-delimited or something) format or if it does something evil.

**Comment by ArtOfCode-** [comment]
Haven't the foggiest :)

**Comment by quartata** [comment]
It's available as an array `tags`, but only from `/question` not `/posts` (that works for us though).

**Comment by angussidney** [comment]
The allspam command doesn’t use either of these routes AFAIK, so we may need to make an extra API request there in order to get the tags.

**Comment by Undo1** [comment]
Would it be better to run the request from metasmoke?

**Comment by ArtOfCode-** [comment]
Only if we're sure we don't want to use tags for spam checks

**Comment by quartata** [comment]
Any tags on spam posts are (almost always) going to just be the suggested tags.

**Comment by Undo1** [comment]
Agree with quartata, since 1-rep folks can't create tags they don't appear to have much signal. I think we should start collecting them first, then build it into Smokey if we see useful patterns.
