### ISSUE TITLE
Incorrect parsing of answer URL as question

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/SmokeDetector#1428]
Bhargav reported [this post](https://stackoverflow.com/questions/20038353/smooth-animation-when-tab-switches/48046679#48046679) in [this chat message](https://chat.stackoverflow.com/transcript/message/40629714#40629714):

```
 !!/report https://stackoverflow.com/questions/20038353/smooth-animation-when-tab-switches/48046679#48046679
```

The link was somehow parsed as a question link, resulting in this URL in [the report](https://chat.stackoverflow.com/transcript/message/40629715#40629715) ([MS](https://metasmoke.erwaysoftware.com/post/100010)):

```
https://stackoverflow.com/questions/20038353
```

**Comment by quartata** [comment]
This has existed for as long as I've been aware of. You need to use share to get an answer link.

**Comment by Undo1** [comment]
I could have sworn it used to work. If we can't fix it to work work those links (shouldn't be too hard), we should at least reject those format links.

**Comment by teward** [comment]
we DID have it parse answers properly, before the recent refactoring if I remember right.  But it might require some specific debugging tracking to ID the actual culprit in the code.



*Sent from my iPhone.  Please excuse any typos, as they are likely to happen by accident.*

**Comment by j-f1** [comment]
Check out https://github.com/Charcoal-SE/charcoal-se.github.io/blob/site/_assets/js/ms-urls.coffee for the RegExii I use on the ms-urls page to find the question/answer IDs.

**Comment by Bhargav-Rao** [comment]
FWIW, I manually reported another answer, a couple of hours before that [here](https://chat.stackoverflow.com/transcript/message/40629414#40629414), and it worked perfectly. Text of the report: 

    !!/report https://stackoverflow.com/questions/239209/is-it-safe-to-assume-that-the-path-c-windows-system32-always-exists/48046326#48046326

and metasmoke page https://metasmoke.erwaysoftware.com/post/100008

**Comment by Undo1** [comment]
Drat, I was hoping for a quick fix. No such luck:

```
>>> print(parsing.fetch_post_id_and_site_from_url("https://stackoverflow.com/questions/20038353/smooth-animation-when-tab-switches/48046679#48046679"))
('48046679', 'stackoverflow.com', 'answer')
>>> print(parsing.fetch_post_id_and_site_from_url("https://stackoverflow.com/questions/239209/is-it-safe-to-assume-that-the-path-c-windows-system32-always-exists/48046326#48046326"))
('48046326', 'stackoverflow.com', 'answer')
```

**Comment by Bhargav-Rao** [comment]
I'm not sure if ChatExchange uses the `/message/<message_id>` endpoint, but it is known to insert some invisible characters in between long URLs. In the one [which I reported](https://chat.stackoverflow.com/message/40629414): 

    !!/report https://stackoverflow.com/questions/20038353/smooth-animation-when-tab-switches/&zwnj;&#8203;48046679#48046679

The `&zwnj;&#8203;` character has appeared exactly after the `/` which might have lead to an incorrect parsing of the URL. 

This was one reason [why I had troubling parsing the URL in one of my bots earlier](https://chat.stackoverflow.com/transcript/message/33613867#33613867).

**Comment by Bhargav-Rao** [comment]
FWIW, this occurred again ... and to me again ... here https://chat.stackoverflow.com/transcript/message/40942991#40942991. I'm sure that the invisible character stuff is the reason to blame.
