### ISSUE TITLE
Regression: Don't report experimental reasons outside Charcoal HQ

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1455]
I believe we had this working before the chat overhaul a few weeks ago.

Experimental reasons like "potentially bad keyword" should not be reported in other chat rooms, only in Charcoal HQ.

I'll see if I can dig up a ticket or at least a commit where this was previously implemented.

Discussion in SOCVR: https://chat.stackoverflow.com/rooms/41570/conversation/smoke-detector-bug-1455

**Comment by quartata** [comment]
Typo, fixing.

**Comment by tripleee** [comment]
Yet one more; not sure why it's still being reported?

https://chat.stackoverflow.com/transcript/message/40751812#40751812
