### ISSUE TITLE
Tone down console spam from SmokeDetector

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#1457]
When Smokey is running, it spams the console constantly. I think we need to adjust how/what is printed to the console. 

It'd be nice if this could be dynamically defined, so that on start up it'd only print a specific level of messages, but if needed a chat command could be run to print more/less.

If we go this route, the default start up level should be configurable in the config file.

**Comment by j-f1** [comment]
Node.js has a [`debug`](https://www.npmjs.com/package/debug) module that might be useful to take inspiration from. You use it like this:

```js
const createDebug = require('debug')
const debug = createDebug('library-name:some-scope')

// ...

debug('some text', { an: { object: true } })
```

```shellsession
$ node example.js
$ DEBUG="library-name:*" node example.js
  library-name:some-scope some text { an: { object: true } } +0ms
$ DEBUG="library-name:*" node example.js | cat # not a TTY
2018-01-05T20:32:15.347Z library-name:some-scope some text { an: { object: true } }
```

**Comment by ArtOfCode-** [comment]
We already have a debug method, we just need to add a level check to it and config.

**Comment by quartata** [comment]
Most of the spam comes from `bodyfetcher`, which prints out the list of post IDs to be scanned regardless of log level. This would be the best change to make.

**Comment by tripleee** [comment]
The code should probably use the Python `logging` module which easily lets you tweak the level of detail you see. You'd run it with only errors (and maybe warnings) enabled in production, but tweak it up when developing. I wanted to get rid of some debug prints before, but postponed it because it should be done consistently throughout the code base.

**Comment by AWegnerGitHub** [comment]
We have a logging function in helpers I believe. I haven't actually looked
at that function to see what it does though

**Comment by ArtOfCode-** [comment]
Logging function author here... I wrote that function as a way to tone down the spam, intending to make the default level WARN. After adding it, I felt that the added timestamp and color distinction was actually enough to make it acceptable. That doesn't, of course, preclude us from still setting the default level to WARN. In fact, even setting the default to INFO would be enough - all the low-level, spammy stuff, like the bodyfetcher IDs, are DEBUG messages.

**Comment by ArtOfCode-** [comment]
There's now a `--loglevel` command-line switch you can use to tone down the spam:

    $ python3 nocrash.py --loglevel=info

is now my default run command.
