### ISSUE TITLE
[FR] Still Alive Function

### ISSUE THREAD

**Issue by CalvT** [Charcoal-SE/SmokeDetector#1549]
I think it'd be nice (and useful!) for Smokey to have some sort of function to find posts that are still alive; by which I mean posts that have at least one TP, were posted within the last 12 hours, and have not been deleted. This would not include posts that also have FP or NAA in the feedback. 

Having this list of posts, my thoughts were then to:

- Have a `!!/stillalive` command, and Smokey replies with a list of urls of the posts
- Or have Smokey repost the post after x hours, with something like `[SmokeDetector | Still Alive | MS]` to make it clear.

Glorfindel suggested querying the MS API (`/api/v2.0/posts/undeleted`) for the posts, so that way it wouldn't use up any of our SE quota.

While the docs for that say *may not be 100% accurate; use the SE API if that's what you need* I'm sure it'd be good enough for this use.

**Comment by j-f1** [comment]
> Glorfindel suggested querying the MS API (`/api/v2.0/posts/undeleted`) for the posts, so that way it wouldn't use up any of our SE quota.

Note that MS stops watching after 10 (?) minutes and it doesn’t know about posts that get deleted after that.

**Comment by quartata** [comment]
This used to exist -- it was called `!!/pending`, but it was unfortunately broken due to some MS API change (this was before V2).

**Comment by quartata** [comment]
What would be really cool would be something like Open Reports where you get a small webpage with the reasons listed and a button you can press to open all the posts in separate tabs.

**Comment by quartata** [comment]
Additionally I think this would also coincide nicely with a deletionwatcher refactor I've been wanting to do for a while.

**Comment by angussidney** [comment]
Previously suggested and closed as redundant since we already have the Autoflagging Information and More userscript which highlights undeleted posts: https://github.com/Charcoal-SE/SmokeDetector/issues/226

**Comment by ArtOfCode-** [comment]
Good find, cheers @angussidney

**Comment by quartata** [comment]
?? I dont think that's much of a substitute since you still have to scroll through the entire transcript...
