### ISSUE TITLE
As a room owner I want newly privileged users to receive a link to Smokey's guidance/wiki 

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/SmokeDetector#156]
... so that they don't screw up things on their first actions and need to be told trivial things.

This might just be implemented as a humanoid procedure but if doable it would be nice if it could be automated.

**Comment by Undo1** [comment]
Interesting idea, not sure how one could implement it cleanly. Smokey is fairly stateless and has a notoriously bad memory (especially if we're switching Smokey servers, which happens occasionally).

Might be possible to track feedback/reports in metasmoke, then tell Smokey if it's the first time a user has posted feedback. Then Smokey could reply to the feedback message with whatever we want it to say.

**Comment by ArtOfCode-** [comment]
@Undo1 Just ask people with push access to link the guidance when they add a new privileged user.

**Comment by The-Quill** [comment]
given that metasmoke stores info about user feedback, couldn't we just search the list of authors and send missing ones the info?

**Comment by ArtOfCode-** [comment]
@The-Quill yeah, we could do. If we want to automate this, I'd say check when smokey starts - check the list of privileged users against the list of feedback authors in metasmoke, and ping anyone new with info.

**Comment by Undo1** [comment]
@ArtOfCode- Problem there is that you'd be pinging people on every startup until they post their first feedback, which is a little unnecessary.

Instead, I'd propose that we send a JIT message to the user on their first feedback - metasmoke could reply to the request if it's the first feedback from the user, then Smokey could reply to their feedback chat message with a "thank you for contributing, here's the rules" message.

**Comment by ArtOfCode-** [comment]
@Undo1 Does Smokey send the chat ID when it pushes feedback to MS? And does MS store it on all new feedbacks? If so then that works; we can check ID's. If not, then certain people will get pinged every time their name changes.

**Comment by Undo1** [comment]
@ArtOfCode- Yes, we do now. Earliest one with a chat ID is from `Tue, 03 May 2016 19:41:14 UTC`, so we have a fair bit of data there to work with.

**Comment by ArtOfCode-** [comment]
[MS commit b323ade3976ad0d1da15594a99a087058691b0e1](https://github.com/Charcoal-SE/metasmoke/commit/b323ade3976ad0d1da15594a99a087058691b0e1) should complete this.

**Comment by ArtOfCode-** [comment]
Deployed, tested, and working.
