### ISSUE TITLE
I seem to have lost my privileges on Tavern on the Meta

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#1574]
I (Sonic the Anonymous Hedgehog) seem to have recently lost my privileges on Tavern on the Meta. I see no commit in the code that suggests that my privileges were revoked, and I had privileges one hour ago. Is this a bug?

**Comment by ArtOfCode-** [comment]
Caused by switching to ArtOfCode/EC2 which was about a bajillion commits behind. Pulling gave me errors, will fix later, we're back on Solar Flare now.
