### ISSUE TITLE
Send post_type to MS

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/SmokeDetector#1637]
When a spam post is first caught, I assume it is also sent to metasmoke. For Charcoal-SE/metasmoke#325, I need to be able to grab the post_type when the post is created. That means that SD will  need to grab it from the API (which I think is automatically included) and the forward it to metasmoke.

I would do it myself, but I am too afraid that everything would explode.

**Comment by iBug** [comment]
Since ArtOfCode declined Charcoal-SE/metasmoke#325, I'm closing this, too.
