### ISSUE TITLE
Clean up handle_commands discussion

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#166]
# Summary

The [`handle_commands`](https://github.com/Charcoal-SE/SmokeDetector/blob/aaf332daa8588394af555357d2bd1da32966a234/chatcommunicate.py#L170) function is a 500 line monstrosity. I'd like to discuss cleaning it up to do the following:

- Standardize what is returned from `handle_commands`
- Have individual functions for each command. 
 
If we agree that this work is needed, I'll take on the work load over the next several weeks (translation: after my summer vacation) to do this work.
 
# Clean up details

This section describes my plan for the above changes. I'd like to do both changes at the same time, but if opposition to that exists one change at a time is acceptable to me.

## Standardize what is returned from `handle_commands`

Currently, the function has multiple return paths and multiple ways of returning data. 

One example is in the [`!!/block`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommunicate.py#L491) command:

    return False, "Invalid duration."
	
Another example is in [`!!/errorlogs`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommunicate.py#L513)

    return "The !!/errorlogs command requires 1 argument."
	
These two methods lead to weird handling in the two locations that `handle_commands` is called from. ([Location 1](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommunicate.py#L123), [Location 2](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommunicate.py#L157))

Method of handling 1:

    if type(result) != tuple:
        result = (True, result)
    if result[1] is not None:
        if wrap2.host + str(message_id) in GlobalVars.listen_to_these_if_edited:
            GlobalVars.listen_to_these_if_edited.remove(wrap2.host + str(message_id))
        message_with_reply = u":{} {}".format(message_id, result[1])
        if len(message_with_reply) <= 500 or "\n" in result[1]:
            ev.message.reply(result[1], False)
    if result[0] is False:
        add_to_listen_if_edited(wrap2.host, message_id)

Method of handling 2:

    r = result
    if type(result) == tuple:
        result = result[1]
    if result is not None and result is not False:
        reply += result + os.linesep
    elif result is None:
        reply += "<processed without return value>" + os.linesep
        amount_none += 1
    elif result is False or r[0] is False:
        reply += "<unrecognized command>" + os.linesep
        amount_unrecognized += 1
		
These type of checks are unintuitive and difficult to follow. It also adds two sections of unnecessary code that perform in a similar, but not identical way. 

### Proposal

I propose that all return paths in `handle_commands` return the expected tuple of `(boolean, string)` and the two locations that call `handle_commands` do so like this, with appropriate variable names:

    bool_result, string_result = handle_commands(...)
	
The block of code afterward can then be reduced and simplified by using descriptive variables instead of elements of a tuple.

## Have individual functions for each command.

As `handle_commands` is currently written, *all* command processing is occurring in this function. Much of this logic should be moved to their own individual functions and `handle_commands` should be used to determine which function to call. Each block that looks like the following should have their own function:

    if content_lower.startswith("!!/addblu")
	
### Proposal

Move the logic of each command to it's own function. This keeps `handle_commands` cleaner and allows for certain areas of code to be reused

**Comment by hichris1234** [comment]
This is a fun one...

> Standardize what is returned from `handle_commands`

Yeah, this code isn't the easiest to follow. But it was born with the intention that mistakes could be edited - so only commands that return an error or return nothing should have a boolean attached to them (as those are the only ones that should be considered for editing. Not sure how to best approach this...

> Have individual functions for each command.

Is there really enough common logic to justify this? I think most of the logic is individual to a command (especially in return values), so moving each command into a method wouldn't really do much except have a `def` surrounding the logic instead of an `if` statement.

**Comment by AWegnerGitHub** [comment]
> Yeah, this code isn't the easiest to follow. But it was born with the intention that mistakes could be edited - so only commands that return an error or return nothing should have a boolean attached to them (as those are the only ones that should be considered for editing. Not sure how to best approach this...

By default, we are making tuples that have the first element equal to `True` [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommunicate.py#L171) and [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommunicate.py#L152) (though less explicitly). 

My solution would be to change all `return "String values"` to have the format `return True, "String values"` I think this falls under ["explicit is better than implicit"](https://www.python.org/dev/peps/pep-0020/).

**Comment by ArtOfCode-** [comment]
> Have individual functions for each command.

If we're doing this, why not create a new file and class for these command methods? In the original file, you can have a dictionary mapping command calls (`!!/addblu` - or just `addblu` with the prefix prepended, for efficiency) to command methods (`ChatCommands.addblu`).

Other than that, like it. Anything that cleans this monster up...

**Comment by Undo1** [comment]
Definitely agree that something should be done to organize that better; this seems like a good approach.

**Comment by AWegnerGitHub** [comment]
Completed with #168 and #174
