### ISSUE TITLE
CircleCI 2.0 update (deadline Aug 31 2018)

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1662]
There was an email from CircleCI about their sunsetting CircleCI 1.0

Here is a blog post with a deadline of August 31st. https://circleci.com/blog/sunsetting-1-0/

They offer a transition page with some tools and documentation at https://circleci.com/sunset1-0/

Basically, it seems that the transition requires a {{config.yml}} update which can be at least partially automated.

The email I got contains a link which however is a 404 if you are not logged in to Circle: http://go.circleci.com/Mk0H0A0RZ071200TG0IM062 but contrary to what the wording in the email suggested, I can't see whether we are currently on 1.0 or 2.0 (or I'm blind).  I assume we have work to do here.

**Comment by ArtOfCode-** [comment]
We're on 1.0, I checked after I got the email. Definitely work to do.

**Comment by tripleee** [comment]
https://circleci.com/api/v1.1/project/github/Charcoal-SE/SmokeDetector/config-translation gives me a 505, not sure if I misunderstand the instructions.

**Comment by Undo1** [comment]
@tripleee I bet it's because Python isn't a supported platform for that translation tool (from the top of https://circleci.com/docs/2.0/config-translation/).

**Comment by angussidney** [comment]
See https://github.com/Charcoal-SE/SmokeDetector/tree/circle-config
