### ISSUE TITLE
Link to SE post in SD message about "fp feedback on autoflagged post"

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/SmokeDetector#1667]
When a user is notified there's been `fp` feedback on a post they've autoflagged, the most important thing is for those users to be able to get to the SE post in order to evaluate the post and choose to either retract their flag, or leave it active. This would be most effectively accomplished by having a link to the SE post in the notification chat message. 

Given that other people will want to evaluate the MS report, it would be advantageous to also have a link to the MS report. 

I'd suggest including both links, similar SD reports. Perhaps something like:

>  [ [MS](https://metasmoke.erwaysoftware.com/post/108607) ] fp feedback on autoflagged post: [The content should be editable without going into HTML, so the client should be able to edit it.](https://graphicdesign.stackexchange.com/questions/106244) (@angussidney @Glorfindel @Yvette @JakeSymons @ByteCommander)

**Comment by angussidney** [comment]
Fixed by Charcoal-SE/metasmoke#333
