### ISSUE TITLE
Extend blacklist keywords

### ISSUE THREAD

**Issue by tschallacka** [Charcoal-SE/SmokeDetector#1686]
So there is this blacklist for wordpress keyword spam people tend to use

https://github.com/splorp/wordpress-comment-blacklist/blob/master/blacklist.txt

Would it be an idea to use this to extend the blacklist for bad keywords in smoke detector?
Or is the list that's currently avaialble comprehensive enough?

It has 26328 keywords mixed words and domains, multiple languages. It would have to be filtered somehow because of terms like server 2012. maybe a queue where people can vote on blacklist relevance, 5 votes  is add it, 5 negative discard it.

**Comment by quartata** [comment]
I've only gone through a few lines of this and I notice that perfectly legitimate things like "abercrombiefitch" are blacklisted. This may cast too wide of a net for SE.

**Comment by angussidney** [comment]
I agree with quartata. There are way too many legit strings in that list (e.g. `/www/`), and many strings which are seemingly spam but could turn up in codeblocks all the time on SO. 

We could add it as a separate rule with `stripcodeblocks=True`, but then we'd still have to go through and manually remove all the legit entries. Additionally, SE recieves a vey specific type of spamming, and I doubt this list would be very effective. Seems like too much work for too little gain.

Of course, if you've found a few entries in that list which seem particularly useful and aren't currently being caught, feel free to watch/blacklist them manually, or even better, compile them into one big pull request with all of the new entries to reduce the number of commits/CI tests/reviews needed.
