### ISSUE TITLE
Migrate config to globalvariables

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#170]
There are currently only a few values in [`config`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/config.sample). I propose we remove "config" completely and migrate these values to globalvaribles.

This removes two locations (config and globalvariables) that developers have to modify when starting SmokeDetector and allows us to remove a ConfigParser import that is only used at start up.

**Comment by ferrybig** [comment]
Having to edit global vars instead of a single config file would mean that an update to any place in global vars would break automatic pulling using !!/pull because git cannot merge files that have uncommitted changes.

I suggest we migrate global vars to config instead.

**Comment by AWegnerGitHub** [comment]
There are quiet a few that are important to change when running a few
version.

One of those is the rooms and privileged users. That is a dictionary. The
configuration files are strings.

However, I do agree that we don't want to pull individual user changes to
globalvaribles

**Comment by Undo1** [comment]
Another thing to consider is that the MS key in that is fairly sensitive,
and it's nice having a hard barrier (.gitignore) to me accidentally
committing/pushing credentials.

**Comment by AWegnerGitHub** [comment]
I don't see config in .gitignore currently. We may want to fix that too. Or put the key in an environment variable the way we do with login credentials.

**Comment by Undo1** [comment]
The gitignore change is probably stuck in my local repo. An environment variable could work.

**Comment by ArtOfCode-** [comment]
> An environment variable could work.

Nay, an environment variable would not only work, it would be a good idea in terms of security.

**Comment by AWegnerGitHub** [comment]
It seems we've decided what to do with the MS Key - put it in an environment variable.

What is the opinion on the other values in `config`?

**Comment by Undo1** [comment]
I don't see any reason that they shouldn't be environment variables either.
It should probably allow start without metasmoke information, but perhaps
require the location (Running on [location]) to be present, either as an
environment variable or as a command line option.

Your other suggestion of being able to change the [SmokeDetector] prefix
and repo link would also fit in well - perhaps try to read from environment
variables / command line options, then fall back on defaults?

**Comment by AWegnerGitHub** [comment]
I am happy with environment variables and default fullbacks for both
location and the chat prefix strings.

The MSkey should allow for nonexistence (since I don't run MS locally when
testing smokey).

**Comment by ArtOfCode-** [comment]
We should let as many things be empty as possible. The fewer things you have to set before running the bot, the easier it is to get started.
