### ISSUE TITLE
Activate Smokey in Charcoal Test chatroom

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#1716]
We have a Charcoal Test chatroom, but we can't test commands there because Smokey is not active.
@ArtOfCode-  thinks it's a good idea as well: https://chat.stackexchange.com/transcript/message/43350221#43350221
It should be a relatively simple change: https://chat.stackexchange.com/transcript/message/43350285#43350285

**Comment by ArtOfCode-** [comment]
Done
