### ISSUE TITLE
Add check_permissions decorator

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#172]
Before I create a pull request for a feature I've already written, I want to make sure everyone is on board with the change. 

The full change is available [here](https://github.com/AWegnerGitHub/SmokeDetector/tree/branch_priv_decorator)  (with a [successful Travis CI build](https://travis-ci.org/AWegnerGitHub/SmokeDetector)). 

---

This change pulls the `is_privileged` check out of each of the commands and instead uses a decorator on the functions that should be restricted to privileged users.

Previously:

```
def command_add_blacklist_user(message_parts, content_lower, message_url, ev_room, ev_user_id, wrap2, *args, **kwargs):
    quiet_action = any([part.endswith('-') for part in message_parts])
    if is_privileged(ev_room, ev_user_id, wrap2):
        uid, val = get_user_from_list_command(content_lower)
        if uid > -1 and val != "":
            add_blacklisted_user((uid, val), message_url, "")
            return None if quiet_action else "User blacklisted (`{}` on `{}`).".format(uid, val)
        elif uid == -2:
            return "Error: {}".format(val)
        else:
            return "Invalid format. Valid format: `!!/addblu profileurl` *or* `!!/addblu userid sitename`."
```

New:

```
@check_permissions
def command_add_blacklist_user(message_parts, content_lower, message_url, ev_room, ev_user_id, wrap2, *args, **kwargs):
    quiet_action = any([part.endswith('-') for part in message_parts])
    uid, val = get_user_from_list_command(content_lower)
    if uid > -1 and val != "":
        add_blacklisted_user((uid, val), message_url, "")
        return None if quiet_action else "User blacklisted (`{}` on `{}`).".format(uid, val)
    elif uid == -2:
        return "Error: {}".format(val)
    else:
        return "Invalid format. Valid format: `!!/addblu profileurl` *or* `!!/addblu userid sitename`."
```

Using this decorator, we can write the functions to work without caring about whether the user has permission to access it. If we want to protect the function, add the decorator. If we do not, don't add the decorator.

**Comment by Undo1** [comment]
Looks much cleaner and harder to mess up on a case-by-case basis. I like it.
