### ISSUE TITLE
Throttle less important chat messages

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#1735]
Context: [here](https://chat.stackexchange.com/transcript/message/43396899#43396899).
Smokey is busy posting unimportant messages like

> Conflicting feedback across revisions: current, #1
> Conflicting feedback across revisions: current, #1
> [...]
> Conflicting feedback across revisions: current, #1
> Conflicting feedback across revisions: current, #1
> Conflicting feedback across revisions: current, #1

while there's a report waiting, which took more than a minute of waiting to be posted. In the end it wasn't posted at all due to a reboot.

**Comment by iBug** [comment]
I'll take a look at this in a few days and hopefully come up with a fix, after coping with my homeworks and assignments.
