### ISSUE TITLE
Still no MS link in long chat messages

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1737]
#488 was closed last year but the logic in shortening chat messages still sometimes removes the MS link. This seems to annoy and baffle people, probably more than dropping a few more reasons would.

Chat: https://chat.stackexchange.com/transcript/message/43397950#43397950

**Comment by M-A-Ramezani** [comment]
I'm not ever interested in seeing the fourth and fifth reasons.  No one is.  Two or three reasons,  preferably ones with the highest weight, should be enough.

**Comment by j-f1** [comment]
Looks like we explicitly remove the MS link, and [the wheel of blame](
https://github.com/Charcoal-SE/SmokeDetector/commit/7c97ed656026b1ad394fbc82e92cd22eba3778a3#diff-73ffc8a77cc10366f971590d298defe7R145) points to @quartata.

https://github.com/Charcoal-SE/SmokeDetector/blob/b369a9808ce0fd43f58bc839369dca56c968c66b/spamhandling.py#L133-L135

**Comment by quartata** [comment]
@j-f1 I was just the last person to touch that line (I've touched every line in that file pretty much). It's always worked like that.

**Comment by angussidney** [comment]
@j-f1 that specific code has been the same since Metasmoke was introduced - I was the last person to make meaningful changes to that logic, and that was to limit it to 5 reasons
