### ISSUE TITLE
Detect links to fiverr.com

### ISSUE THREAD

**Issue by ztane** [Charcoal-SE/SmokeDetector#175]
Fiverr.com is a site for selling freelance work. Answers that link to that site are very likely spam.

An example post at http://stackoverflow.com/posts/38404091/revisions

**Comment by Undo1** [comment]
After looking through SO's occurrences of this, it seems sane to blacklist
it. 75 deleted, 16 undeleted.

Might be sane to require a nontrivial path in the URL, so we don't catch
"maybe you can pay someone through [Fiverr](fiverr.com)". That's LQ, but
not spam.

**Comment by normalhuman** [comment]
[implemented](https://github.com/Charcoal-SE/SmokeDetector/commit/84aec99b1adece224cc1c16fb8b18886c0e51299)
