### ISSUE TITLE
Different alert for apparent vandalism

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#190]
I have repeatedly tripped on SmokeDetector reports which looked like spam or rude/abusive but which were self-vandalism, which is easily reverted and should not be flagged as spam.

Could the alert from the bot look different when it triggers because of an edit to a post which was previously fine?

For [example](http://chat.stackoverflow.com/transcript/message/32256559#32256559), a chat alert message like

> [ [SmokeDetector](http://git.io/vgx7b) ] Few unique characters in body, repeating characters in body, repeating characters in title, title has only one unique char: [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](http://stackoverflow.com/questions/13640054) by [Kot](http://stackoverflow.com/u/1865357) on `stackoverflow.com` (@tripleee)

... could have been more easily categorized correctly if it had a different chat message, perhaps something like

> [ [SmokeDetector](http://git.io/vgx7b) ] Few unique characters in body, repeating characters in body, repeating characters in title, title has only one unique char: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa [edited](http://stackoverflow.com/revisions/13640054/5) by [Kot](http://stackoverflow.com/u/1865357) on `stackoverflow.com` (@tripleee)

Notice how the question's title is no longer a link, and the "edited" link instead links to the actual revision which introduced this vandalism.

**Comment by ArtOfCode-** [comment]
We don't store history, so doing this "for a post which was previously fine" isn't easily possible. We *could*, I think, change the message to have an `edited` link on *any* edited post instead.

**Comment by Undo1** [comment]
*If* we wanted to do this, it'd be fairly easy - we've been running this for long enough that we can reasonably assume that if we only caught a post after an edit, we've seen it before and it was okay then.

Of course, I'm not entirely convinced we want to do this. I don't really have any good arguments either way, though.

**Comment by AWegnerGitHub** [comment]
I disagree with this request. It is up to users of the system to look at the post before they flag. If they are getting tripped up by vandalism, they need to slow down. Adding this type of check to smokey removes incentive to look at and see what is going on with the post.

A self vandalism post should be easily identified already. By changing what is linked to in certain cases changes what users are expecting to happen with they click the link (post vs revisions).

**Comment by hichris1234** [comment]
Closing this based on Andy's comment -- agree with it as well and it seems the majority of us do.
