### ISSUE TITLE
Deletion watcher should also work for manual reports 

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/SmokeDetector#1932]
if those are also send to the Tavern on a delay

example :  https://chat.stackexchange.com/transcript/message/43700467#43700467

post was deleted way before the 5 minute mark, but still posted in the Tavern

https://chat.meta.stackexchange.com/transcript/message/6818125#6818125

Please don't do that for already deleted posts

**Comment by quartata** [comment]
This is specifically a problem with manually reported *answers* (questions work fine). When we manually report an answer, we don't know the question ID so it can't listen to it for deletions.

**Comment by iBug** [comment]
@quartata Aren't we fetching the parent for `post._parent` (so we have a title)?

**Comment by quartata** [comment]
This was before scan and report were merged

**Comment by quartata** [comment]
Before we did not fetch the parent as it was only needed for !!/scan

**Comment by iBug** [comment]
I've gone through the code again and it seems this issue has been fixed. Good to close?

**Comment by quartata** [comment]
Yeah it looks like it works. If post.parent.post_id is filled in (which it is) then handle_spam automatically calls add_post_site_id_link
