### ISSUE TITLE
Limit "notify" to users that have been active in the room in the past <X> minutes.

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/SmokeDetector#195]
At this moment, in the [SO Close Vote Reviewers chatroom](http://chat.stackoverflow.com/rooms/41570/so-close-vote-reviewers), SD is notifying 6 different users for every single report.

Example:

> [ SmokeDetector | MS ] Few unique characters in body: SolvedSOLVEDSOLVED by Furkan Ayık on stackoverflow.com
>  (@&#8203;PraveenKumar @&#8203;AndrasDeak @πάνταῥεῖ @&#8203;FrankerZ @&#8203;tripleee @&#8203;dorukayhan)

The amount of users getting notified has steadily been growing. Imo, it's getting a little annoying. Only a portion of the users actually respond to these notifications, and they get notified even when they haven't been active for hours.

I'd like to request these notifications to be filtered on user activity.
IE: Don't bother notifying a user that hasn't been active in the last hour.

Just to be clear: I have no issue with these users. Just that the list of notifications is getting close to the length of the actual report.

**Comment by ArtOfCode-** [comment]
Working on this. ChatExchange at our current version doesn't provide the info necessary to restrict this, so I've submitted a [pull request](https://github.com/Manishearth/ChatExchange/pull/123) to CE that adds it. When that's merged (hi @Manishearth), I/we can start implementing into Smokey.

On another note, thoughts on timeline? Only ping users who have been active in the last...what? Hour? Two hours?

**Comment by hichris1234** [comment]
Personally, I use `!!/notify` to get notifications on any post reported on ES. I'd like to get that notification whether I've been in the room recently or not.

**Comment by Undo1** [comment]
Jumping on with @hichris1234 here. I wonder if we could make it less obtrusive by only pinging the first x chars of their username?

**Comment by AWegnerGitHub** [comment]
Please don't do that @undo1. I already receive pings for other "Andy"s unintentionally. I don't want it to be automated now.

**Comment by Undo1** [comment]
@AWegnerGitHub Might be possible to automatically check the pingable list and figure out how many chars are necessary. Not sure, haven't looked into it enough.

**Comment by ArtOfCode-** [comment]
@hichris1234 I wondered if we might come across that case. Okay, here's a thought: `!!/notify` functions as of now. We add `!!/pingme` (or similar), which functions as described in this PR.

@AWegnerGitHub, @Undo1: it's definitely possible with existing CE functionality to check the pingable list to figure out how many chars are needed. The logic to do that might be a little contrived, but it's doable.

**Comment by ArtOfCode-** [comment]
The alternative I came up with (to address @hichris1234's situation) is to change notify to this PR, but add a reports feature to metasmoke - every 24h, metasmoke collects posts that you select (i.e. all one site, or all from reason X), and sends a link to that report to you in chat via the MS-Smokey websocket. I'd be happy to dev the MS side of that, I'll have time over the next couple weeks.

Thoughts?

**Comment by Undo1** [comment]
@ArtOfCode- Not sure it's worth it, or that it's the right solution. I don't use it (probably should), but from what I've seen people use it to get pinged when there's something they can flag - not too useful for that purpose if you get the notification once a day.

Not sure if that's what people are using it for, though. I could be wrong, that'd be new.

**Comment by AWegnerGitHub** [comment]
Let's ask the people using it what they are using it for then.
Specifically, what they are expecting/wishing/hoping regarding the
notifications when they aren't around.

**Comment by Cerbrus** [comment]
@hichris1234: The whole reason for this request is that users are being pinged while they aren't active in the room. They aren't even responding to pings from other users in the room. In other words, there's no point to these notifications if users aren't active.

The notification feature is there to allow users to **_quickly_** respond to reports. If you want a summary of reports, you can also visit https://metasmoke.erwaysoftware.com

**Comment by tripleee** [comment]
Another option is to notify each user in private chat. Yet another is to remove the `!!/notify` functionality entirely, which I suppose would end the disgruntlement over the bot generating too much noise with each notification. Switching to the Chrome plugin gets me the same functionality in a less obtrusive way - the pings are audio only, and I can change the setting client-side, and it doesn't bug me when I'm not using the browser, and it keeps my "supercollider" inbox clean from these bot pings, which are easily dozens per night, and detract from notifications I actually want to see several hours after they originally happened. Just my €0.02.

**Comment by adeak** [comment]
I think it's clear that there's a huge distinction to be made between SO and other SE sites. On SO, true positives get nuked very quickly, in a matter of minutes at worst. So pinging users on SO "overnight" is probably pointless. But on smaller sites spam and abuse can linger, so it would still be beneficial if users can go through the ping backlog and do the needful. But I suspect I've just been paraphrasing @hichris1234.

**Comment by Undo1** [comment]
@adeak This makes a lot of sense - on SO, we already have enough guns to shoot stuff down quickly.

On other sites, !!/notify is useful for, e.g., moderators destroying the users involved, looking for patterns, etc. 

Maybe we could just disable it in SOCVR? I can't speak for everyone, but I suspect CHQ would be more tolerant of 'noisy' messages with a bunch of people pinged.

**Comment by tripleee** [comment]
The SOVCR room can police itself -- there is an active group of room owners and an evolving FAQ / room guideline.  So perhaps no need to actually change the functionality if it is useful on other sites.

**Comment by Cerbrus** [comment]
@tripleee: The SOCVR has no say about who gets notified. We can only _ask_ them to unsubscribe.

There is absolutely a need to change the functionality. One of the users being notified hasn't sent a message in chat for over 9 days, and hasn't been logged in in chat for at least 2.  
We don't need noise like that added to the reports.

**Comment by normalhuman** [comment]
Not a SOCVR regular, but my understanding is that at-notification do not scale well, so it's understandable that at the size of SOCVR they may become more of a distraction than help. Disabling them in SOCVR, as @Undo1 suggested, seems the easiest solution.

**Comment by Cerbrus** [comment]
At this moment, there's only 1 user left in the notification subscriptions on the SOCVR. The other users unsubscribed from the notifications, after discussing it with them.

That one subscriber hasn't been active in a while. Consequently, we haven't had any luck getting in contact with him.

**Comment by tripleee** [comment]
The final SOCVR notification has been disabled now.

**Comment by ArtOfCode-** [comment]
That'll do for me, closing without even needing a code change :)

**Comment by Cerbrus** [comment]
@ArtOfCode- 
We've got 2 users being notified in SOCVR again:
http://chat.stackoverflow.com/transcript/message/33401100#33401100

One of them used to be unnotified, but apparently felt the need to re-register for notifications. As last time, they're not responding to pings.

I'd like to request these notifications to be disabled for that room. There's plenty of traffic there for reports to get handled quickly. There's no point in notifying users that don't respond, any way.

**Comment by hichris1234** [comment]
Is there an actual problem here? This really seems more like a personal objection to the notifications; I can't see that this is causing any direct harm or anything.

**Comment by tripleee** [comment]
The fact that users can add themselves to the ping list and then disappear is a maintainability hurdle.  Having the code remove users who have not been active in the room for a while would help make the whole thing more sustainable. The alternative is to commit to having an admin remove them manually when they have been gone for a long time, which is unattractive in many ways, not least because requiring other users to collect evidence to support such requests is yet another nuisance.

**Comment by hichris1234** [comment]
Maintainability? Hah, you're just adding bits to a file. Again, I can't see any direct evidence this is harming anyone. If the room owners see this as an issue, okay, fine -- but right now, it just seems like you don't like seeing any @ pings at the end of a message... which I can't really understand why that's so problematic.

**Comment by Cerbrus** [comment]
@hichris1234: This issue was raised because the signal-to-noise ratio of SD reports was deteriorating. More than half of the report was pointless metadata, back then, with 6 users being notified.

That is pointless in a room where the reports already get handled quickly. Even more so, considering the users getting pinged don't respond in time, before the reported post is handled.

**Comment by tripleee** [comment]
My PR was superseded by https://github.com/Charcoal-SE/SmokeDetector/commit/9b59fa2ba7a8b7dfed725fc66ebeacf05407a352

**Comment by tripleee** [comment]
As the discussion seems to continue over in SOCVR, I will also note here for context that one of the problems with this is that users who are constantly notified by the room by way of automation become effectively unreachable because they will learn to ignore any pings from the room, automated or not.
