### ISSUE TITLE
Should reports be edited on FP instead of deletion?

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#197]
Currently, if a report is marked as False Positive, Smokey will try to delete the report to prevent accidental flagging. 

However, on more than one occasion I have been wanting to see the post itself so I can make up my own mind/investigate/check for hidden spam etc. To do this, I have to go to metasmoke, click the post tab, find the post, go to the post page and click once more to view on the original site. Too much effort for a lazy person like me :)

Instead, I propose that Smokey should try to edit the report to the following:

> [SmokeDetector | MS] *(false positive - report deleted)*

or something similar, so that the MetaSmoke link is still clickable.

This could be easily done by modifying [line 983 of chatcommands.py](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommands.py#L983). Should be low-hanging fruit.

**Comment by Fortunate-MAN** [comment]
I like the idea, but if we want to do this, we would like to scratch the report instead of putting the false positive in brackets, as that would make it more clear. [Something like this](http://chat.stackoverflow.com/transcript/message/32392979#32392979):

![selection_120](https://cloud.githubusercontent.com/assets/12422882/17829376/496069ce-66ca-11e6-8281-a73b0d5c1ea5.png)

But note that as we cannot edit messages once two minutes have gone by, this will not be possible in many cases.

**Comment by angussidney** [comment]
@Fortunate-MAN I disagree - there is a reason why FPs are deleted in the first place, and that reason is probably to stop robo-flaggers from clicking the link and flagging it. While crossing the message out *does* convey that the report is a false-positive, it doesn't stop users from clicking on it.

Alternatively we could edit out the link *then* strikeout?

Also, you can't delete messages after x minutes anyway, so nothing much should change if we edit instead.

**Comment by AWegnerGitHub** [comment]
If you want to see the metasmoke report - and the link to the actual post - MetaSmoke is still available and contains the information. Deleting the report from the chatrooms doesn't remove that information

**Comment by angussidney** [comment]
@AWegnerGitHub exactly - but what I am asking, is for the MS report to be linked in the message, even after it has been marked as FP, for easier access.

**Comment by Undo1** [comment]
Throw this in a bookmark: [`//metasmoke.erwaysoftware.com/posts/latest`](//metasmoke.erwaysoftware.com/posts/latest)

**Comment by hichris1234** [comment]
I'm closing this one. We designed it this way to make it a quick and easy way to identify which reports not to waste your time with. If it's marked as a false positive, in most cases it is.

If you really want to review these posts, just view https://metasmoke.erwaysoftware.com/posts -- or the link Undo gave above.

**Comment by ArtOfCode-** [comment]
I do see that it can be a little peeving to have the MS link, in particular, removed from the chatroom because the message was deleted, but I also agree that deleting the message is the best thing to do. There's not really much we can do here.

**Comment by angussidney** [comment]
@Undo1 thanks for the tip - that should do nicely

**Comment by ByteCommander** [comment]
Just to have told you my opinion, I'd also personally prefer editing by striking the message through and optionally removing the post link, leaving only the metasmoke link over deleting the whole message. 

Besides that, if Smokey reports posts in foreign rooms (like Ask Ubuntu spam in the Ask Ubuntu General Room), the post there does not get deleted if somebody feeds back "f" e.g. in Charcoal HQ. The chance to attract robo-review flags in such a room with "ordinary" users is probably much higher than from within the specialized Charcoal HQ room.
