### ISSUE TITLE
Please document how to add a new room

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#198]
I was unable to find documentation for how to add a new room to the bot's configuration.  This seems to be a recurring thing, so having a few sentences about how to request an addition could be a welcome addition to e.g. https://github.com/Charcoal-SE/SmokeDetector/wiki/Chat-Rooms

I can guess, but I don't think that qualifies me to actually write documentation.

A rough transcript of my guesses will be visible around http://chat.stackoverflow.com/transcript/message/32434109#32434109

**Comment by kwokandy** [comment]
Thanks @tripleee I'm definitely looking for that. As @tripleee said, it is tough to see how the whole thing can be implemented

**Comment by Undo1** [comment]
Fairly simple. I'll leave it right here:

Add a dictionary to [`GlobalVars.specialrooms`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/ws.py#L78):

```
GlobalVars.specialrooms = [
    {
        "sites": ["yyy.stackexchange.com"],
        "room": GlobalVars.wrap.get_room("nnn"),
        "unwantedReasons": ["foo"]
    },
    [...]
```

Where `yyy.stackexchange.com` is the site that you want reports from, `nnn` is the room ID you want them sent to, and `["foo"]` is a list of reasons that you *don't* want reported.

**Comment by kwokandy** [comment]
One more question, please. 

Should I host the @SmokeDetector in a server? My guess is yes but I'd rather ask the question even if it seems silly ...

Thanks @Undo1

**Comment by Undo1** [comment]
Well, anything with decent uptime can be a 'server'. I'm running it on a Pi in my closet right now, have been for months without (too much) incident.

**Comment by kwokandy** [comment]
@Undo1 what ...? A Pi ...? #omg \o/ I thought @tripleee was kind of joking ... #LaughingHard

**Comment by ArtOfCode-** [comment]
@kwokandy Don't let me discourage you from running your own instance of Smokey; far from it. It's just worth noting that the effectiveness of Smokey is built on the fact that we have a decent size team of people who dedicate chunks of time to look at spam and find the patterns we use. If you're looking to run you're own coy, that's awesome, but bear in mind that you may not have that, so it may not be as effective (though you can of course merge the patterns the Smokey team finds from upstream).

**Comment by ArtOfCode-** [comment]
(closed, because the original issue has been resolved, but discussion should still be open)

**Comment by kwokandy** [comment]
Hi @ArtOfCode- thanks for your answer. By checking all the docs of the SOCVR, I have two more questions:

- I'm interested in the queen bot actually. Where can I find info about that bot?
- For smokey or the queen, are there ways to modify them to check for certain questions only?

Thanks

**Comment by ArtOfCode-** [comment]
@kwokandy queen isn't a Charcoal project, though I'm not sure whose it is. You'd have to ask who runs it in SOCVR. As for checking certain questions, sure, there's probably a way, but you'd need to write the code for it yourself - it's not built into Smokey.

**Comment by ArtOfCode-** [comment]
(^ fat fingers)

**Comment by tripleee** [comment]
Queen is run by @PetterFriberg; you can get support and more information in the SOCV Finder chat room; http://chat.stackoverflow.com/rooms/111347/socvfinder
