### ISSUE TITLE
Should we make our guidelines more specific regarding repairable offensive posts?

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#1982]
See also: https://github.com/Charcoal-SE/SmokeDetector/issues/995

Our current [feedback guidance](https://charcoal-se.org/smokey/Feedback-Guidance#repairable-offensive-posts) states that:

> Some (non-native) speakers think f*cking is a synonym for very. The posts usually can be salvaged by editing out the inappropriate language and leaving a comment. The appropriate feedback is f as we don’t want a system-level block preventing these kind of posts.

This guidance makes sense in situations like the one above - we don't necessarily want to block these posts outright, as they are otherwise (mostly) useful and repairable by an edit.

However, it doesn't seem to apply well to posts like [this](https://metasmoke.erwaysoftware.com/post/113176), where the offensive content is deliberately edited in after posting. If we were assessing the *edit* rather than the post as a whole, I would argue that *'why the f*** do you downvote'* is irrepariable, and thus the action **should** be blocked at a system level.

Thus I propose that we amend our guidelines to the following:

> Some people think that f*cking is a synonym for very, and so they use it to provide emphasis when writing their post. These posts usually can be salvaged by editing out the inappropriate language and leaving a comment. Therefore the appropriate feedback is `f` as we don’t want a system-level block preventing these kind of posts.
> However, if a post is *edited* by the author in a way which is mostly offensive, then the appropriate feedback is `k` as we would've wanted that edit to be blocked by the system.

What do you think?

**Comment by rschrieken** [comment]
Can't we just add one line to the current guidance instead? Something like:  _use your common sense for other f*cking occurances_ . So we cover all bases?

**Comment by ByteCommander** [comment]
Wouldn't `tp-`/`v` be ideal for that? 
In case of an edit, adding obscenities would really count as vandalism IMHO. 
And in case of a fresh post, it still serves the purpose of marking the report as correct without blacklisting the user.

**Comment by angussidney** [comment]
Guidance updated; recommended action is `tp-` as per @ByteCommander's suggestion.
