### ISSUE TITLE
Zoe requests privileges in SObotics

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1992]
This is currently pending on approval from a SObotics room owner.

https://chat.stackoverflow.com/transcript/message/42037475#42037475

**Comment by Bhargav-Rao** [comment]
They've been active very recently in the room, and I'm not very much inclined about giving them privileges immediately. 

Let's give it a few months more and then revisit this.

**Comment by tripleee** [comment]
Closing for now. Thanks for following up.

**Comment by LunarWatcher** [comment]
https://chat.stackoverflow.com/transcript/message/43445303#43445303
