### ISSUE TITLE
Add in an !!/unwatch command

### ISSUE THREAD

**Issue by WELZ-gh** [Charcoal-SE/SmokeDetector#1993]
We are pretty liberal with keywords we watch, therefore we need to remove keyword all the time.

Would be nice to have a command like `!!/unwatch {keyword}` or even `!!/unblacklist`

We already have this for users (`!!/rmblu`)

**Comment by quartata** [comment]
already implemented in helios

**Comment by CalvT** [comment]
Just to point out that the `!!/rmblu` process is way different to what would be needed to make an `!!/unwatch` command. 

The blacklisted users list is stored locally per instance, while the watch and blacklists are stored on GitHub.

**Comment by ArtOfCode-** [comment]
Done
