### ISSUE TITLE
Do not self-delete messages in Tavern on the Meta if marked as false positive there

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2011]
Currently, if a user marks a SmokeDetector report in Tavern on the Meta as a false positive there, the message is immediately deleted.

Unfortunately, I ran into an issue where I clicked "reply" on the wrong report, and ended up marking the wrong post as a false positive. The message was immediately deleted, so I couldn't change my feedback there. While I could open metasmoke and go into the review history, it's very inconvenient.

According to @Undo1 , the utility behind self-deleting reports marked as false positives was to avoid cluttering the transcript. However, a year (or three) after the change was made, ROs are routinely moving Smokey's messages into a different room called Chimney. As such, I believe that this doesn't have the utility that it once had.

If the community is intent on self-deleting these messages, there should be a window to correct mistakes. For example, Smokey should wait until just a few seconds before the self-deletion threshold expires to self-delete.

For context, here's the [conversation](https://chat.stackexchange.com/rooms/11540/conversation/self-deleting-false-positives-in-tavern) behind this.

**Comment by angussidney** [comment]
We're happy to make such a change, but you'll need to demonstrate that the majority of The Tavern regulars approve of the removal, especially given that they requested the feature in the first place.

**Comment by rschrieken** [comment]
If it happened once I don't think removing is needed. Beyond that, it is a convenient option to prevent extra attention for those posts that are fp. That works quicker then reaching for the clean tool. So I vote for keeping it as is.

**Comment by bjb568** [comment]
Couldn't there be a new command for fixing a mistaken fp that would print the information that would currently have been deleted?

**Comment by Undo1** [comment]
@bjb568 Easiest thing would be to hit http://metasmoke.erwaysoftware.com/posts

**Comment by angussidney** [comment]
There is a survey which is currently underway: https://chat.meta.stackexchange.com/transcript/message/6862342#6862342

**Comment by gparyani** [comment]
@angussidney I was the operator of that survey.

Over the course of the past two weeks, I received 16 responses: 8 were for keeping the status quo as is, 4 were for disabling self-deletion of such messages entirely, and the remaining 4 were for implementing an alternative option: to wait until the very end of the self-deletion time limit to self-delete.

Thus, since half the respondents were against implementing this change, I'll drop this.
