### ISSUE TITLE
!!/scan-ning an answer seems to scan the question in addition

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#2012]
See [here](https://chat.stackexchange.com/transcript/message/44016288#44016288) where I instructed SmokeDetector to scan an answer, but it responded with

> Potentially bad keyword in title:

(I'd expected it to trigger on blacklisted user, but the troll created another account with the same name).

**Comment by iBug** [comment]
Should be fixed in #2126, closing.
