### ISSUE TITLE
Watch sometimes adds entry twice

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2026]
This happened twice this morning.  A single `!!/watch` was applied twice, and resulted in a failed CI run when there was a duplicate in the file.

https://chat.stackexchange.com/transcript/message/44072445#44072445

https://chat.stackexchange.com/transcript/message/44073098#44073098

I have successfully submitted watches between those two which did not cause a failure.

**Comment by ArtOfCode-** [comment]
Pretty sure this was down to duplicate Smokey instances running. Closing for now, reopen if it happens again.
