### ISSUE TITLE
Check whether a post has been reported before when using `report` or `scan`.

### ISSUE THREAD

**Issue by JarkoDubbeldam** [Charcoal-SE/SmokeDetector#2047]
The last two days, I've seen two occurences of a post being reported a second time. Smokey's reaction is a bit inconsistent here.

Example 1:

https://chat.stackexchange.com/transcript/message/44108698#44108698

The post was already reported only just before, so it triggered a message from Smokey that it had been, linking to the MS records.

Example 2:

https://chat.stackexchange.com/transcript/message/44119418#44119418

This post was reported before, but did not trigger Smokey saying so.

The comments around the responsible code ([`scan`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommands.py#L1204) and [`report`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommands.py#L1119)) look a bit outdated:

> Don't re-report if the post wasn't marked as a false positive. If it was marked as a false, this re-report might be attempting to correct that/fix a mistake/etc.

It seems to me that currently, the preferred action would be to amend the previous report to be correct, instead of creating a new one.

The [check in the linked pieces of code](https://github.com/Charcoal-SE/SmokeDetector/blob/master/datahandling.py#L268) also only checks `GlobalVars.latest_questions`, which is only a cache of ~15 posts.

# Suggestion

Replace the check `has_already_been_posted` to check whether the post already exists in MS (this way we can look back further) and remove the exclusion of previously fp-marked posts.

**Comment by JarkoDubbeldam** [comment]
A similar piece of logic seems to be here: https://github.com/Charcoal-SE/SmokeDetector/blob/master/metasmoke.py#L109

**Comment by ZoeIsAFuckingCunt** [comment]
I think you can fix it by telling [Zoe](https://stackoverflow.com/users/6296561/zoe) where to shove [this](https://static1.e621.net/data/sample/8b/7c/8b7c8578f49a9853a597322bc96f9e9e.jpg). You see, Zoe's a fucking furfag bitch who should go fucking kill herself, so it should fix everything

**Comment by iBug** [comment]
Increased cache to 50 posts which should be enough most of the time
