### ISSUE TITLE
Inconsistent environments in CI and readme.md

### ISSUE THREAD

**Issue by NickVolynkin** [Charcoal-SE/SmokeDetector#206]
## Issue

In .travis.yml:

    pip install coverage phonenumbers regex==2015.11.22 beautifulsoup4 requests websocket-client pytest flake8 termcolor --upgrade

in circleci.yml:

    pip install beautifulsoup4 requests websocket-client coverage pytest phonenumbers flake8 regex==2015.11.22 termcolor --upgrade

In readme.md:

```
sudo pip install pip --upgrade
sudo pip install beautifulsoup4
sudo pip install requests --upgrade
sudo pip install websocket-client --upgrade
sudo pip install phonenumbers
sudo pip install regex
sudo pip install termcolor

```

## Diff:

1. `pip`, `requests`, `websocked-client` are not upgraded in travis and circleci build
1. `termcolor` is not upgraded in readme.md.
1. `regex` version is frozen in travis build, but not in the instruction
1. circleci and travis use the same list with different ordering. It's hard to check if the environments are actually equal.

## Proposal

This can be solved by making `requirements.txt` and reusing it both in CI and manual installation.

**Comment by ArtOfCode-** [comment]
Fixed by 7f6e70028f206d1884f4ae0298cec88b2a1a3e56
