### ISSUE TITLE
Wrong MS link for posts on child metas

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#2097]
Example: https://chat.stackexchange.com/transcript/message/44227697#44227697
The MS link is https://m.erwaysoftware.com/posts/uid/stackoverflow/366614 which doesn't work; I'm not sure what it *should* be (meta.stackoverflow) does not work either.

**Comment by AWegnerGitHub** [comment]
Why are we manually reporting child meta posts, particularly this one?
Child metas aren't monitored by smokedetector.

**Comment by Glorfindel83** [comment]
I don't think this post should've been reported, but it has been useful in other instances in the past.

**Comment by ArtOfCode-** [comment]
So I missed this case when I did the conversion to UID links yesterday. The API parameter for MSO _is_ `meta.stackoverflow`, but there's an MS bug that means using it won't work; I'm fixing that, and updating the API param parser to pull meta sites as well.

**Comment by ArtOfCode-** [comment]
Fixed Smokey and MS-side.
