### ISSUE TITLE
Deletion watcher mixes up question & answer

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#2172]
[This post](https://metasmoke.erwaysoftware.com/post/119937) is marked as 'deleted' in metasmoke, but its [timeline](https://stackoverflow.com/posts/46446426/timeline) suggests it isn't. Instead, one of the answers ([also reported](https://metasmoke.erwaysoftware.com/post/119938)) *has* been deleted, but metasmoke doesn't know about this. I assume the deletion watcher somehow mixed up the question and answer.

**Comment by iBug** [comment]
I think I have some ideas about how this is working, but the fix may be more complicated than it looks at first glance.
