### ISSUE TITLE
Detect proper links at the end of an body, not partial ones

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/SmokeDetector#218]
http://english.stackexchange.com/a/344768/71877 was reported for _link at end of answer_ but at the end the post only contained

>  (Dictionary.com)

That looks like a domain but I don't know if that should qualify as a proper link. Otherwise consider excluding certain domains from that check?

Smokey report: http://chat.stackexchange.com/transcript/message/32525630#32525630

**Comment by kevin-brown** [comment]
Do we know how many false positives we get because of cases like this?

**Comment by Undo1** [comment]
[The reason itself has a fairly high false positive rate.](https://metasmoke.erwaysoftware.com/reason/73)

**Comment by hichris1234** [comment]
Yeah, LAE has some of the most false positives but also some of the most true positives. I haven't thought of a good way to avoid the false positives.

**Comment by rschrieken** [comment]
Maybe split it in 2 reasons: 

-  Url at end of answer
   -  http://something.com/page?q=foo
- Domainname at end of answer  
  - something.com

**Comment by acleach** [comment]
Or, allow sites to whitelist domains -- answers on english.se could well end with a link [as here] because of our cite-and-link policy, and dictionary.com is a real dictionary site. I suspect that would be quite a big enhancement though.

**Comment by honnza** [comment]
Whitelist is the way to go, I believe
