### ISSUE TITLE
@SmokeDetector included in MS comments

### ISSUE THREAD

**Issue by paper1111** [Charcoal-SE/SmokeDetector#2180]
When replying to an SD report, the comment marked in MS contains

    <span class="mention">@SmokeDetector</span>

 at the beginning. For example, https://metasmoke.erwaysoftware.com/post/120263 (I removed the `@SmokeDetector` text by editing). This text is not useful and should be stripped at first.

**Comment by quartata** [comment]
Are you sure the HTML tags were there too?

**Comment by paper1111** [comment]
It shows the HTML when I click on the edit button, without the edit button, the HTML is not shown. Transcript link https://chat.stackexchange.com/transcript/11540?m=44713658#44713658

**Comment by iBug** [comment]
I believe the bug is [fixed in the current revision][1], so I'm closing this issue for now.

[1]: https://github.com/Charcoal-SE/SmokeDetector/blob/488bc1bca1723218faf3020fef7f41e29492d23a/chatcommunicate.py#L199

**Comment by quartata** [comment]
That was always there. The only way this could be caused is if it wasn't recognized as a reply at all (in other words, it's ChatExchange's fault), but rather was turned into an autocomment because it contained a feedback name
