### ISSUE TITLE
Add a filter for title-case Japanese history spam

### ISSUE THREAD

**Issue by spacemonaut** [Charcoal-SE/SmokeDetector#2207]
RPG.SE is experiencing a confoundingly strange category of spam that seems to just be a series of wiki excerpts: https://metasmoke.erwaysoftware.com/search?body=japan&site=46&feedback=true+positive. I believe I've seen this on another site too a couple of weeks ago (can't remember which) so it may not be localised to RPG.SE.

I'd like SmokeDetector to have a filter which detects its two hallmark attributes:

1. Almost Every Word Is Title Case. I Don't Know Why, They Just Are.
2. It mentions Japan somewhere. (Or Japanese, so containing the word "Japan" anywhere is enough.)

[Chat discussion here (May 29 2018)](https://chat.stackexchange.com/transcript/message/44859678#44859678) in which
@tripleee [mentions a regex](https://chat.stackexchange.com/transcript/message/44859775#44859775) which apparently also has some wrinkles: `(([A-Z][a-z]*\W+){3,}([a-z]+\W+)?)Japan`

**Comment by tripleee** [comment]
Tested that this hits on the three samples in the ticket and that it only matches on RPG for now.

The regex was easy but remembering what the various flags do was tough ...
