### ISSUE TITLE
The post Markdown sometimes has info which is stripped from the HTML. Should feedback be based on it, or only the HTML?

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/SmokeDetector#2216]
The information that SD deals with is the rendered HTML, not the Markdown. SD could get the Markdown in addition to the HTML, but doesn't. Do we provide feedback based on information which exists in the Markdown, but which SD never sees because it's stripped from the rendered HTML? Such feedback could result in difficulty in training, if the feedback is used for ML training.

[Example ms post](https://m.erwaysoftware.com/posts/uid/meta/310743)

HTML that SD sees:

    <p>[enter link description here][۱]</p>

Markdown from post:

    [enter link description here][۱]

      [1]: http://%20%20alihamzehzadeh@outlook.com

While in this case, the Markdown is not completely damning, I recall seeing at least one other case with a post that SD reported where the Markdown made the decision clear due to having stripped a large amount of text out of the rendered HTML. IIRC, it was text that SE's Markdown converter interpreted as HTML and stripped.

**Comment by tripleee** [comment]
Another example: https://chat.stackexchange.com/transcript/message/45045471#45045471

**Comment by makyen** [comment]
That example is:
[ms post](http://metasmoke.erwaysoftware.com/post/122609)

The HTML SD sees:

    <p>this is static website canonical tag  but bellow link check it that is dynamic script we have 100 pages</p>

    <p>" /></p>

The [Markdown source](https://stackoverflow.com/posts/50738136/revisions) ([edit link](https://stackoverflow.com/posts/50738136/edit/f50e80f0-be5b-4a29-ad77-57ff65085f6a)) is:

    this is static website canonical tag <link rel="canonical" href="https://aapthitech.com"/> but bellow link check it that is dynamic script we have 100 pages

    <link rel="canonical" href="<?php echo 'http://'.$canon_url; ?>" />

**Comment by Undo1** [comment]
We should feedback based on whether the post on SE should have been blocked at the system level or not. Meta doesn't care about our technical details, they care about whether the stuff we catch is actually spam.

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/post/124155 another example

**Comment by makyen** [comment]
Another example: https://m.erwaysoftware.com/posts/uid/mathoverflow.net/304996

**Comment by makyen** [comment]
Another Example: https://metasmoke.erwaysoftware.com/post/127060

**Comment by iBug** [comment]
Same thoughts as Undo has. The only untimate feedback guideline is whether we want to block the post on SE. Complementary/supplementary information can be submitted as a comment on MS so special cases can be filtered out easier.
