### ISSUE TITLE
Duplicate watches still happen

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2219]
It is not at all infrequent for two people to `!!/watch something` more or less at the same time in chat, and have two separate branches be created, tested, and merged without conflict but resulting in a CI failure after the merge.

The run-time checking against duplicates doesn't help at all here, because it only examines the current branch, and arguably couldn't know whether another branch is also being created at some point during the time it is processing the command.

**Comment by tripleee** [comment]
Example just now:

https://chat.stackexchange.com/transcript/message/44901622#44901622

I believe all the recent "Duplicate fix" commits by myself are caused by incidents of this type.

**Comment by ArtOfCode-** [comment]
Could be fixed with a lock - only let one operation on each list happen at a time

**Comment by j-f1** [comment]
Or store a global list of pending watches and refuse to watch if the item is on the list (this has the benefit of getting cleared on reboot, when the changes have been successfully pushed)

**Comment by iBug** [comment]
Can be easily solved by checking duplicates in branch `master` instead of `deploy`.
