### ISSUE TITLE
!!/willibenotified doesn't work

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2238]
Reported here:

https://chat.stackexchange.com/transcript/message/45027394#45027394

Should the documentation be updated or was the functionality lost by mistake at some point?

**Comment by tripleee** [comment]
Quick review suggests that this was removed in commit https://github.com/Charcoal-SE/SmokeDetector/commit/504441091e11b698e5cdfb4fa205a75f64a6e4d9 but it's not clear whether this was intentional.

**Comment by quartata** [comment]
It's called !!/willbenotified.

**Comment by j-f1** [comment]
Time for an alias?

**Comment by Filnor** [comment]
Alright, thanks for sorting that out @quartata. I edited the wiki page and corrected the command.

@j-f1 IMO that sound like a good idea.

**Comment by quartata** [comment]
I think I renamed it just because the previous name was very difficult to read
