### ISSUE TITLE
Extend Japanese filter to watch all sites except JP

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2240]
Discussion here:

https://chat.stackexchange.com/transcript/message/45050931#45050931

**Comment by tripleee** [comment]
The earlier rule in #2207 was specifically targeting RPG only. The proposal is to extend this to all sites except the Japanese ones.

**Comment by tripleee** [comment]
It woul be nice to see it actually trigger on something but I suppose yeah, let's just close this and create a new issue if there is a problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iBug** [comment]
No new spam has come in the past days, but only [one innocent victim] has been caught. Good to remove this check?

[1]: https://metasmoke.erwaysoftware.com/post/123525

**Comment by makyen** [comment]
IIRC, there was a post in the last couple/few days which wasn't actually caught (manually reported, IIRC), but which was sufficiently similar such that there was discussion of expanding this detection to catch it.

**Comment by tripleee** [comment]
The Possible Expansion Would Probably be Significant Enough That it Needs a Different Name Anyway. I Was Thinking Look for Posts With at Least _n_ Words Where the Vast Majority is Capitalized; And Call it Something Like "Post Entirely In Title Case".

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
