### ISSUE TITLE
Blacklisted for making the same post

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2241]
[This report](https://metasmoke.erwaysoftware.com/post/122962) was filed as a result of being blacklisted for making [this post](https://meta.stackexchange.com/a/311088) ([MS report](https://metasmoke.erwaysoftware.com/post/122960)). But the problem is, both reports point to the same post.

Why was a duplicate report filed for the same post, for the sole reason that they made that very post? Was it because the title of the question was edited, and it thought it was a different post because the titles were different?

**Comment by tripleee** [comment]
status-bydesign

**Comment by gparyani** [comment]
@tripleee Can you please explain why it's intentional and by design that Smokey is supposed to report the same post twice in a row if the title is edited?

**Comment by tripleee** [comment]
I think NobodyNada's comment above is already an excellent explanation of the logic. The flag is warranted so a human can review whether it's still spam/off-topic and if not, remove the user from the blacklist by flagging the updated post as FP.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
