### ISSUE TITLE
Exclude SmokeDetector itself from !!/blame

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2249]
It happened again: someone ran the `!!/blame` command and [Smokey blamed itself](https://chat.meta.stackexchange.com/transcript/message/7021763#7021763).

The `blame` command is supposed to find real, normal users. As such, please prevent SmokeDetector from choosing itself as one of the blame targets.

**Comment by NobodyNada** [comment]
I really don't think this is necessary.  `!!/blame` is a joke command; why is it any less "funny" if it blames itself, and why is this worth changing?

**Comment by superplane39** [comment]
See also [Channels](https://stackoverflow.com/c/charcoal/a/294/6):

> The situation with extensions to existing commands is slightly different. If there's a bug in one of them, fixes for that are always welcome. If you're doing a major refactor or new feature and you happen to accidentally extend a fun command too, it'll probably be overlooked. Beyond that, though, pull requests or issues requesting extensions to existing commands are also likely to be declined.

**Comment by gparyani** [comment]
@superplane39 It's not an extension to a fun command. It's a request to *remove* a feature from an existing fun command.

**Comment by ArtOfCode-** [comment]
Playing the semantics game with a bunch of programmers is not going to go very far, I'm afraid. Removing a characteristic of a command requires more code - that much should be obvious to you - so it's an extension.
