### ISSUE TITLE
Upgrade to tld 0.8

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2251]
**Smokey runners:** please scroll down to the last comment

As noted in #2250 the latest release of `tld` has backwards-incompatible changes.

https://github.com/barseghyanartur/tld/blob/master/CHANGELOG.rst explains in some details that code should transition to the new method `get_fld()` going forward.

**Comment by iBug** [comment]
For what it's worth, [I have temporarily locked package `tld` to version 0.7.10][1] (which I suppose will be the last release of 0.7.x. If anyone if going to do this upgrade, please remember to release the lock by changing it to `tld>=0.8` after the job is done.

[1]: https://github.com/Charcoal-SE/SmokeDetector/commit/0f9bb66c630a6ce73518e7349dd6ff6950e0ee29

**Comment by tripleee** [comment]
Reopening. Please only close when all the checkboxes are checked.

Check when your instance is updated to have the 0.8.x version of `tld`:
- [ ] teward/Solar Flare
- [ ] teward/Lunar Eclipse
- [ ] teward/Supernova
- [ ] ArtOfCode/EC2
- [ ] Henders/EC2
- [ ] bwDraco/Linode
- [ ] Mithrandir/Tauremornalómë
- [ ] NobodyNada/Raspberry Pi
- [ ] angussidney/EC2
- [ ] Undo's RPI 3
