### ISSUE TITLE
Canonical procedure when one of our dependency packages has rolled out a backward-incompatible update?

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/SmokeDetector#2256]
From time to time, a PyPI package of Smokey's dependency gets a new, backwards-incompatible version published. This creates some hard time for us like it just happened some time ago (see #2251 and #2253).

On one hand, we can't update the code directly to adapt to the new version as adapted code will not run correctly on instances with the old version of the package.  
On the other hand, server owners can't update the package directly before adaption code is deployed.

This requires a developer and a server owner to have time to do the work *simultaneously*. While some of us are able to handle this, it's much too complicated in a general case.

So, is there a "canonical", or at least, better solution when this happens again?

**Comment by j-f1** [comment]
Is there a way to use some sort of dependency lockfile to avoid accidental upgrades, then install from that whenever the instance pulls? From my experience with Yarn, a package manager for JS that works like that, installs where nothing needs to change are pretty quick.

**Comment by tripleee** [comment]
`pip freeze` does that I believe. But blocking accidental upgrades isn't the beef here; managing upgrades we want without breaking anything is what this ticket is about.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
@tripleee Those are the same thing — if you control the exact version of each dependency on each instance, and can update it with a commit, you can make the backward-incompatible changes and upgrade the dependency in one commit, which will cause the update to be installed on pull.
