### ISSUE TITLE
!!/report should !!/scan first

### ISSUE THREAD

**Issue by longsonr** [Charcoal-SE/SmokeDetector#2289]
It seems that we're supposed to use [!!/scan](https://stackoverflow.com/c/charcoal/questions/101/102#102) now either before or instead of !!/report. 

Rather than having to remind occasional users of smokey to change their habits and have !!/report be a foot gun for them, why not...

1. have !!/report do a !!/scan first which falls back to !!/report if not detected

2. if you feel it necessary introduce a !!/report-no-scan command (or something like that) for the times when the user just wants to report w/o scanning.

that way those people used to using !!/report can continue to do so. 

This idea was originally suggested [here](https://chat.stackexchange.com/transcript/message/45394636#45394636) and [here](https://chat.stackexchange.com/transcript/message/45394662#45394662)

**Comment by iBug** [comment]
Good idea. TBH I've though of this before and I just kept it personal. Now that someone brings this up, I'll make it work.
