### ISSUE TITLE
Provide a way for non-privileged users to !!/scan

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#2332]
Right now, !!/scan is an alias for !!/report, which is (rightfully) a privileged command.
However, this has the drawback that non-privileged users cannot !!/scan anymore, like they did before.

If you ask for my interpretation of the word 'scan', it's way closer to 'test' than to 'report'. So my preference would be removing the alias entirely, but I'm open to a solution where !!/scan only scans for non-privileged users but also reports (if applicable) for privileged users. Though that might be too confusing.

Context: [here](https://chat.stackexchange.com/transcript/message/45664892#45664892)

**Comment by iBug** [comment]
I'll take this work. Hope it's not hard to do it.
