### ISSUE TITLE
Revert fix for #2354

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2361]
A while ago, I filed #2354 based on what I thought was an intentional change to URLs to answers. However, that change was actually considered a bug, and has been fixed.

Can the fix for that issue please be removed, as it's no longer an issue now that the change in question has been reverted?

See https://meta.stackexchange.com/questions/313428/why-did-the-format-of-full-form-urls-to-answers-change

**Comment by makyen** [comment]
Do we need to revert this?  Does the current code work with both formats?

**Comment by makyen** [comment]
[This was the commit that changed the parsing](https://github.com/Charcoal-SE/SmokeDetector/commit/927ad7563c87b7cf8edd6b2259e13e4ca763ae00).

**Comment by gparyani** [comment]
Closing, as original form still works even with the change. The "newer" form is still shown in some cases, such as if someone loads a subsequent edit, and as such that feature should still exist.
