### ISSUE TITLE
Why did SmokeDetector report this post as the second URL?

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2442]
A user [reported a post to SmokeDetector](https://chat.meta.stackexchange.com/transcript/message/7270614#7270614), using the incorrect syntax for reporting reasons:

    !!/report [url] spam nonsense

In this case, I'd expect that it would recognize the URL as post 1, while the two words at the end would be recognized as posts 2 and 3.

Why did it consider the URL as post 2, while not recognizing posts 1 and 3?

**Comment by iBug** [comment]
We used `urls = list(set(urls))` to filter out duplicate URLs, and `set()` is an unordered collection, so the order messed up. Fixed in 647bd9fbaa78a92b5e2468a21154b5bc28f7eeeb
