### ISSUE TITLE
End support for Python 3.4 compatibility?

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/SmokeDetector#2445]
Python 3.4 was released in March 2014 and is almost 4.5 years old. Support for Python 3.4 is anticipated to end in March next year.

Python 3.5 is the successor of Python 3.4, released in September 2015. Some features that we would utilize are:

- Improved asynchronous tasking / paralleling
- Improved high-level API of `subprocess` (we can start replacing `Popen` then)
- Improved `traceback` functionality and performance

Previously, the reason for holding Python 3.4 was because Henders's instance ran it. We've got 4 or 5 instances running Python 3.6 so the loss of a single one shouldn't matter too much.

Shall we discontinue compatibility support for Python 3.4 and embrace the advantages of Python 3.5 (or even Python 3.6, since we don't have 3.5 runners)?

**Comment by ByteCommander** [comment]
For reference, here are the planned EOL dates: https://devguide.python.org/#status-of-python-branches

```
Branch 	Schedule 	Status 		First release 	End-of-life 	Release manager
--------------------------------------------------------------------------------------------
master 	PEP 569 	features 	2019-10-20 	2024-10 	Łukasz Langa
3.7 	PEP 537 	bugfix 		2018-06-27 	2023-06-27 	Ned Deily
3.6 	PEP 494 	bugfix 		2016-12-23 	2021-12-23 	Ned Deily
2.7 	PEP 373 	bugfix 		2010-07-03 	2020-01-01 	Benjamin Peterson
3.5 	PEP 478 	security 	2015-09-13 	2020-09-13 	Larry Hastings
3.4 	PEP 429 	security 	2014-03-16 	2019-03-16 	Larry Hastings
```

While I'm fine with removing 3.4, I would still personally advocate for keeping 3.5-compatibility and rather adding a test runner than dropping it. E.g. Ubuntu 16.04 (EOL 2021) still ships 3.5 as default. 

We should also assemble a list of the currently used versions on all Smokey runner's environments first.
