### ISSUE TITLE
Git test abandons branch

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2465]
Running the test suite now includes some Git tests, which is nice per se, but it has some unpleasant consequences.

    $ git checkout -b branchname
    $ edit findspam.py
    $ git commit -m 'small changes' findspam.py
    $ python -W default::Warning -m pytest test -s
    .... things .... lots of things ....
    $ git status -uno
    On branch master

Notice that the test suite has caused the current Git branch to change to `master` as a side effect of the tests. Bewilderment and possible panic ensues when the changes you were testing are suddenly gone, and/or you commit additional changes to `master` when you think you are still working on your branch.

Also, another side effect is that the test suite fails if you have uncommitted changes.

**Comment by iBug** [comment]
Solution: Skip all git tests unless on master and working tree clean.

**Comment by iBug** [comment]
Please check if a43b62b32f8d3f8233e9f9d7df7ece9cd2dd5cfb solved this issue.
