### ISSUE TITLE
Incorrect detection of Non-English link in answer

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/SmokeDetector#248]
This [answer](http://stackoverflow.com/a/39961665/578411) was reported as [_Non English Link in Answer_ ](http://chat.stackoverflow.com/transcript/message/33387178#33387178) but I fail to see where the non-english is. The markup of the post was:

```
https://jsfiddle.net/TC2006/vcfjhg4m/[][1]

    Just something I made in JSFiddle.

    Hope it helps. :)

  [1]: https://jsfiddle.net/TC2006/vcfjhg4m/
```

Can this be fixed or explained why it qualifies for being reported?

**Comment by angussidney** [comment]
Link to reason in code, for reference:

https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L59

**Comment by hichris1234** [comment]
The non-English link text here is an empty link text. I looked at this a while back; it's only been detected a couple times in the past few months, and it does seem somewhat strange to have no link text, so maybe this is a decent idea to detect. I'm not sure though.

**Comment by rschrieken** [comment]
@hichris1234  I'm not saying it shouldn't be detected but I had to hit edit to check the markdown to verify that there was not something hiding in there. So I'm fine with detecting this empty link text but I would love to not have that called *non-english* although technically empty is also non-english...

**Comment by ArtOfCode-** [comment]
I'm gonna close this, because we haven't had any recurrences.

**Comment by angussidney** [comment]
And I'm going to reopen this, because we *literally* had another occurence of this about 20 minutes after you closed it:

http://chat.stackexchange.com/transcript/message/33657866#33657866

**Comment by ArtOfCode-** [comment]
Typical. Inconsiderate spammers, no thought for the common spam-detectors.

**Comment by Bhargav-Rao** [comment]
And another one https://metasmoke.erwaysoftware.com/post/47517
