### ISSUE TITLE
Enable SmokeDetector messages on international sites

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2488]
Per SE employee [request](https://chat.stackexchange.com/transcript/message/47321852#47321852).

We often get reports that we don't know how to tell if they're spam or not because they're written in a different language and posted on a foreign language community. It would be great to have Smokey posting in international site rooms so that the communities can take part in handling it.

**Comment by ArtOfCode-** [comment]
Is this a request for Smokey to post in The Terminal, or more generally for each international site to have its own reports/room?

**Comment by tripleee** [comment]
We don't generally have a problem with this, most spam can be machine translated well enough that you understand its topic, at least to the point where you can make your mind up on whether it's spam or not.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
We also have /pings/langs as a fallback.

**Comment by gparyani** [comment]
@ArtOfCode- Nicolas specifically requested having SmokeDetector post in each international room.

@tripleee I think it would be a great idea to give the international communities more power in deciding if things are spam. Also, I filed this request mainly because Nicolas requested we do so.

**Comment by ArtOfCode-** [comment]
@gparyani I'm gonna [status-decline] that: communities won't like their agency to request that (or not) themselves being taken away. If communities want it in their rooms they're more than welcome to it, but adding it without some general agreement from them is a recipe for not good things. Also happy to add Smokey to Terminal on the strength of Nicolas' request if that's useful.

**Comment by gparyani** [comment]
@ArtOfCode- Yeah, you should add Smokey to The Terminal if that's the case.

**Comment by ArtOfCode-** [comment]
Done

**Comment by gparyani** [comment]
@ArtOfCode- You forgot `rus.stackexchange.com`

**Comment by ArtOfCode-** [comment]
Ta, added

**Comment by gparyani** [comment]
Said tweaks have been completed in 4d1c7fd and 2cbd916
