### ISSUE TITLE
Post titles with Japanese characters aren't parsed correctly

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2493]
[This post](https://metasmoke.erwaysoftware.com/post/140816) was reported as "mostly dots in title" because it contained "1 period out of 1 character." However, this isn't the case; it consists of mostly Japanese characters, some English letters, and two dots.

Why was it parsed as only containing a single dot as its title?

**Comment by ArtOfCode-** [comment]
Unicooooooooode.

**Comment by iBug** [comment]
Closing for now (see the commit above). Feel free to reopen if it turns out to have not been fixed.
