### ISSUE TITLE
Smokey pickle transfer protocol via chat (SPTP)

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/SmokeDetector#2511]
Due to an earlier development failure, Smokey dumped the whole output of `git log` in message 47386004 and 3 other messages (all moved to Charcoal Test). It resulted in a message more than 3 MiB in length.

It indicates that there's no length limit or at least "very high" of multiline messages. I think this can be utilized (abused) to transfer pickles or other synchronized data like blacklisted users, ignored posts, etc. A chat command will dump the pickle directory or selected ones after some simple packaging and encoding, for example `tar zcf - | base64`, and post the resulting string to Charcoal Test. Another chat command will load the pickle from a given chat message and restore pickled data, and probably merge with its local data as well.

Of course, `tar` isn't the only solution. We can even pack the data up in Python and make it into a single file before base64-ing, but that's technical implementations and the base is the same (via chat).

What's your idea about this approach?

**Comment by tripleee** [comment]
We already have websockets, how about let the instances talk to each other over that?

Some further musings in chat: https://chat.stackexchange.com/transcript/message/47421920#47421920

**Comment by iBug** [comment]
@tripleee That could be an option, but how do instances know where each other is? And how to transfer data? Note that Smokey itself does not act as a server in any way, but a client.

**Comment by ArtOfCode-** [comment]
We've ruled out websockets before, because not everyone is okay with opening  ports to do it.

However, we already have this chat-based method of direct communication - look at socketscience.py and room 84821. I think this is worth a try.

**Comment by iBug** [comment]
@ArtOfCode- That sounds like a good point, but the primary concerns are **1.** security: whether the pickle content contains sensitive data or anything that we just don't want random people to see, and **2.** whether periodically creating a chat message of hundreds of KiBs or 1 to 3 MiB is acceptable to SE (and the messages looks like nonsense).

**Comment by ArtOfCode-** [comment]
(2) we can excuse fairly easily: if creating long messages wasn't allowed, then the system should reject them. It doesn't, so using it is excusable. (1) needs someone to go through the pickle files looking for sensitive data. I don't _think_ there is any, but I may be wrong.
