### ISSUE TITLE
Include instance identity and optionally time stamp in error messages in chat

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2519]
When SmokeDetector is in a twisty maze of restarts, and there could me multiple instances in the chat room concurrently, it would be extremely beneficial if error messages from each instance would indicate which instance generated the error message.

I'm thinking the chat error message reporting could probably be changed to simply add the instance name when an error is communicated in chat, but I got lost in the code when trying to figure out where exactly this might be possible to implement.

Perhaps in the end it would be easier if individual error messages in the code had this added where it makes sense.

For the `!!/errorlog` it would also be useful if the printed log could indicate the current time as well as the name of the instance which generated it.  So for instance

    me> !!/errorlogs 1
    iBug's SD> :2345678 Error logs from iBug/EC2 (2018-11-05 04:21:27 UTC):
    iBug's SD>     2018-11-05 04:15:25.094983 UTC 
    Solar> :2345678 Error logs from teward/Solar Flare (2018-11-05 04:22:02 UTC):
    Solar>     2018-11-05 04:18:16.957812 UTC

**Comment by iBug** [comment]
It's probably time for a refactor of our logging system

**Comment by iBug** [comment]
I'll take this later. I'll first migrate all the logs to an SQLite 3 DB file `errorLogs.db` (so we store more information) and then change the way logs are presented in chat.

```sql
CREATE TABLE error_logs (time REAL, instance TEXT, classname TEXT, message TEXT, traceback TEXT)
```

And the fetching the latest errors can be as easy as

```sql
SELECT * FROM error_logs ORDER BY time DESC LIMIT <number>
```

**Comment by iBug** [comment]
https://chat.stackexchange.com/transcript/message/47520147#47520147
