### ISSUE TITLE
PullApprove v3: what needs to be done?

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#2536]
[PullApprove v3 is out](https://medium.com/dropseed/introducing-pullapprove-version-3-4da68e14a623). Yay!

However, it looks like a lot has changed. For instance, v3 is tied in directly to the GH review system, which may affect the ability for non-collaborators to review blacklist PRs. We'll have to look into this.

Things that we need to check/do:

 - [ ] Does v3 still have all the features that we need? If it doesn't, what do we switch to?
 - [ ] If so, are any build system changes required (e.g. on metasmoke)?
 - [ ] Upgrade!

Currently there is no planned date for shutting down v2, however given how integral this is to our auto-blacklist system, I think it's a good idea that we start the migration process now so that we aren't caught with our pants down.

**Comment by iBug** [comment]
I received this announcement mail, too. I guess we don't depend as much as before on PA, as I [made `!!/approve` a chat command][2518] some time ago, which can replace the majority of our current use of PA (letting code-priv'd users approve watches without giving full write access).

I'm not objective to the upgrade, though, just sharing some thoughts.

  [2518]: https://github.com/Charcoal-SE/SmokeDetector/pull/2518

**Comment by iBug** [comment]
@j-f1 PA offers web hooks and MS currently listen to it.

**Comment by j-f1** [comment]
@iBug GitHub also has webhooks, and there’s [an event](https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent) for PR reviews.

**Comment by iBug** [comment]
@j-f1 Then it looks like we can drop PA, but it needs MS-side code work to adapt GH webhooks.

**Comment by iBug** [comment]
Looks like in the past few months folks have been preferring heavily the `!!/approve` chat command and PA is just out. Maybe we can ignore this issue for now or ever?
