### ISSUE TITLE
Command to identify matching regex

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2544]
Frequently in the recent past, we have had some "wtf" moments when an innocuous-looking phrase in a post triggered a "bad keyword in answer" or similar.  Troubleshooting these is slow and somewhat demanding. Couldn't we have Smoke Detector simply tell us which regex matched?

This was explored in the past when Quartata (I think it was) looked into having this information available for every post, but it turned out to be too slow.

A much less imposing solution would be to only provide this information when it is explicitly demanded, perhaps through a dedicated command.

I propose `!!/bisect` though it's probably too obscure. "Why" is already taken and `!!/wtf` is probably too easy to type in by mistake ... Additional proposals welcome.

The implementation I am imagining would check the input against everything, then gradually discard more and more of the blacklists until it has identified a single regex which is responsible for the detection.

(Corner case: What if a phrase matches more than one?)

**Comment by WELZ-gh** [comment]
Are you thinking `!!/command <ms url>` (or even `<post url>`) or would it be a command as a reply?

**Comment by iBug** [comment]
What exactly is it going to be? `!!/command <post>` or `!!/command <keyword>`? That's going to make some differences.

**Comment by tripleee** [comment]
I'm thinking the argument would be a string so you can experiment rather freely.

`!!/wtf +1-800-555-1212`

**Comment by tripleee** [comment]
The huge and unstructured regexes in `findpam.py` itself would still be problematic. Ideally, dividing them into smaller fragments would let you see which fragment matched; but you run the risk of producing an invalid regex by dividing between paired parentheses or brackets.

**Comment by iBug** [comment]
Example: <https://chat.stackexchange.com/transcript/message/48279574#48279574>

Details: <https://stackoverflow.com/c/charcoal/questions/505>
