### ISSUE TITLE
Send Magento alerts to dedicated room

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#277]
As requested by the Magento user [Raphael at Digital Pianism](http://chat.stackexchange.com/users/141835/raphael-at-digital-pianism) in [this Charcoal discussion](http://chat.stackexchange.com/transcript/message/33266689#33266689), please send Smokey reports for the Magento site to the dedicated chat room [47869](http://chat.stackexchange.com/rooms/47869/charcoal-smokedetector-reports).

**Comment by digitalpianism** [comment]
@tripleee thanks for that. Feel free to let me know if you need anything else from me.

**Comment by tripleee** [comment]
Documentation here will need to be updated as well: https://github.com/Charcoal-SE/SmokeDetector/wiki/Chat-Rooms

**Comment by ArtOfCode-** [comment]
#276 and #278 merged, Smokey pulled. `[status-completed]`.

**Comment by tripleee** [comment]
And I'll note that the linked wiki page was apparently updated at the same time.

**Comment by ArtOfCode-** [comment]
Yeah, I did that just before I merged the two.
