### ISSUE TITLE
Should the DNS cache size be increased?

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2798]
I've been looking at a local SmokeDetector instance with logging turned on, and I notice that it purges the DNS cache about once per minute even during relatively slow times. I remember I put very small limits when I wrote the code, and the intent was certainly to use larger values in production; but before I go ahead and increase them, do we have instances which are already consuming more memory than they should?

The current logic remembers the *n* most recent queries and their results -- it allows the cache to build up until it exceeds 10 entries, at which point it purges the oldest entries so that only the newest 5 remain.

There are several caches like this -- `TLD_CACHE` for top-level domain lookups, `DNS_CACHE` for all kinds of DNS lookups, and `LINK_CACHE` for the extracted URLs from recent posts so we don't have to keep re-extracting them. (This should perhaps have smaller limits, but it's easier to have just one global limit; maybe we can live with having some old data kept around as a necessary effect of having caching in the first place.)

Having DNS and TLD results cached speeds up processing in particular when a post is edited a short while after it was posted. The link cache is only really useful because we end up trying to pull the same set of links out of a post several times while we are processing it.

These caches are just simple text dicts; in the grand scheme of things, upping the limits to something like 200/20 should not increase memory consumption by noticeable amounts. I might even play around with values on the order of 1000/200.

Comments, objections?

**Comment by ArtOfCode-** [comment]
:+1:

**Comment by angussidney** [comment]
As far as I know, my instance has a fair bit of spare room, so increasing the limit to around 1000/200 sounds good.

**Comment by iBug** [comment]
Just leaving a note here, I don't have a particular objection, but AFAICT Smokey maintains a sustained RAM usage of up to 450 MB (seen in `htop`, resident memory usage `RES`), and bursts to 550 MB occasionally, particularly on high load (spam hours). If cache is too big, I'm afraid instances on servers with only 1 GiB RAM will start to have troubles.
