### ISSUE TITLE
Improvements to auto-blacklist PRs

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#284]
I'd like to see if I can make the following improvements to the PRs created by non-code-privileged users when they use the !!/blacklist command:

- [x] Link to a MS search for the URL
- [x] Link the username to their chat profile
- [x] (if possible) automatically search MS and show the number of tps and fps for the site.

**Comment by ArtOfCode-** [comment]
The first two are easy enough; the third is just about possible currently but would require a lot of code Smokey-side that doesn't have much relevance to spam-detection...

**Comment by Undo1** [comment]
> but would require a lot of code Smokey-side that doesn't have much relevance to spam-detection

I've thought about doing this from the metasmoke side. We could have a webhook from GitHub fired on pull request creation, then embed a comment or something in Smokey PRs that we could pick up on.

**Comment by Undo1** [comment]
Second one (linking user chat profile) is done, see #311 as an example.

**Comment by Undo1** [comment]
![screen shot 2016-11-25 at 10 54 14 pm](https://cloud.githubusercontent.com/assets/5162342/20638351/2a345134-b362-11e6-97e8-9814d9c1096a.png)

No. 3 is now done. Suggestions for more information to cram in there are definitely helpful!
