### ISSUE TITLE
Submitting nonexistent sites seems to crash the bot

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#285]
I am afraid I succeeded in bringing the bot offline repeatedly just now by attempting to `!!/report` posts which had already been deleted.

The first attempt was an experiment where perhaps I should have been more careful; the second, reports which originally didn't succeed, and when I retried, some of them had been deleted in the meantime.

This could easily happen by mistake at any time, so the bot should be able to cope with this.

Chat link for context: http://codereview.stackexchange.com/a/146113/63322

**Comment by hichris1234** [comment]
Yeah, that wasn't it. It can cope with this 

More than likely just a caught websocket or something.
