### ISSUE TITLE
Request for Smoke Detector privileges for Stack Exchange user 11267045

### ISSUE THREAD

**Issue by zoxuyu** [Charcoal-SE/SmokeDetector#2920]
Hello everyone,

I'd like to have Smoke Detector privileges, at least in the Tavern. If I recall correctly, I have already Reviewer privileges in Metasmoke.

Given the recent outages, I'd like to be able to give feedback directly from the Tavern, which I have almost always open.

My Stack Exchange network account:  
https://stackexchange.com/users/11267045/mee

Due to current Metasmoke outages, I am not able to get my MS user id. My browser history suggests 362 if that is of any help.

Thanks,
MEE the setup wizard (current MSE user name)

**Comment by double-beep** [comment]
MS is up now, you correctly found your user ID: it is 362.

It would be easier for if you'd provide:

- <s>Your account ID (network-wide)</s> yours is 11267045 as you provided.
- Your Stack Exchange chat ID.
- Your chat.MSE ID.
- You chat.SO ID.

and links to your profile each time. Saves admins some time. See also:

- https://github.com/Charcoal-SE/SmokeDetector/blob/master/users.yml
- https://github.com/Charcoal-SE/SmokeDetector/blob/master/rooms.yml

**Comment by makyen** [comment]
Done.
