### ISSUE TITLE
Better prevention of accidental use of a bare . in black- and watchlist

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#2937]
From time to time, people forget that a bare `.` matches every character, not just the dot itself. The correct syntax is to escape it (`\.`), which is the intended behaviour 99% of the times.
SmokeDetector could detect cases like

> !!/watch example.com

and reply with something like 

> @Glorfindel Bare dot detected in pattern; you most likely meant to `!!/watch example\.com`. Use !!/watch-force to override this check.

See https://chat.stackexchange.com/transcript/message/50123380#50123380 + surrounding pages.

It's maybe not necessary for !!/blacklist-keyword and !!/blacklist-username, but it definitely is useful for !!/blacklist-website.

**Comment by makyen** [comment]
Resolved with [458ca6](https://github.com/Charcoal-SE/SmokeDetector/commit/458ca6ff2c636fba2cdc9ca1453591f67f795c73)
