### ISSUE TITLE
Spammer says they're not #phishing

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2970]
The Smokey admins received an email:

> (domain).com is not phishing any brand or website. We is an independent lead generation software. It would be great if you delete your report.
> 
> Evidence of Abuse: https://metasmoke.erwaysoftware.com/domains/21297  
>
> Company Admin
> --
> Administrator
> **Raletta Technology Pvt Ltd**
> m: | +91 88888 399 39
> a: | 142/2 GNT Market, Dhar road, MR-6, Indore
> w: | www.(elided)  e: hello@(elided)

I am creating this ticket in accordance with our policy at https://charcoal-se.org/smokey/Process-for-blacklist-removal.html#process-for-blacklist-removal and am responding to them with this information:

> Hello, and thanks for contacting Charcoal.
>
>As a fundamental starting point for this correspondence, we do not remove historical records.
>
> We have a policy in place for blacklist removal. That is not what you are asking for here precisely, but I will point you to that as a basis for further discussion, and urge you to follow up on the ticket I created in our public Github issue tracker:
>
> [github.com/Charcoal-SE/SmokeDetector/issues/2970](https://github.com/Charcoal-SE/SmokeDetector/issues/2970)
>
> The policy is at 
> 
> https://charcoal-se.org/smokey/Process-for-blacklist-removal.html#process-for-blacklist-removal
>
> Removing a tag like #phishing is not technically hard, but there is no guarantee that it will not be added back if your behavior warrants it. In any event, I would be best if you could refrain from abusive advertising altogether, and probably a basic and minimal starting point for further negotiations.

**Comment by magisch** [comment]
Seems like this isn't really about our domain tags at all, but rather about the abuse report (https://metasmoke.erwaysoftware.com/abuse/reports/23) that was filed against the spammer last year.

**Comment by angussidney** [comment]
Given that there has been no response from Raletta Technology, I am closing this issue as stale. I will re-open the issue if or when the matter re-emerges.
