### ISSUE TITLE
Inavlidated feedback on MS does not remove the user from blacklist

### ISSUE THREAD

**Issue by Fortunate-MAN** [Charcoal-SE/SmokeDetector#301]
Apparently, if someone blacklists a user using `tpu-`, and the feedback gets invalidated, the user is not removed from the blacklist. 

This has caused false positives. Example: http://chat.stackoverflow.com/transcript/message/34103819#34103819

IMO, the user should be removed from the blacklist in case the feedback is invalidated.

**Comment by ArtOfCode-** [comment]
Ideally? Yeah, it should. In practice? This is like someone using `k` in chat by accident then switching feedback... which also doesn't remove the blacklist, which is why we have `!!/rmblu`.

**Comment by Fortunate-MAN** [comment]
@ArtOfCode- so could it be implemented? It seems like a good addition and will reduce some false positives.

**Comment by Undo1** [comment]
Over the last 3 months, 77 posts have had invalidated tp feedback. There were 10 other posts from those users made before or after the post with invalidated feedback. 7 of those 10 were true positives, 1 NAA, and 2 false positives.

So I don't think there are sufficient numbers here to justify it it.

Caveats (all working in favor of this proposal): 

 - Post timing isn't checked; the other posts could have been made after the one with invalidated feedback. 
 - I'm not checking the reason a post was caught. A better test (which would only shrink the numbers here) would be to look at posts caught by *only* the blacklisted user reason.
