### ISSUE TITLE
Improved handling for #drugs spam targeting free hosting and open forums

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#3259]
Since a few months back, we see regular spam with 3 or more links, some of which usually go to well-known #drugs sites, but others which are hosted on Google, Wix, Tumblr, Medium, various forums, occasionally probably hacked Wordpress sites and what not.

## Approaches

I have toyed with creating a SmokeDetector rule for `findspam.py` to identify these, but it's a bit of a moving target which would require us to maintain yet another list of target domains (or something like that -- that's what my current prototype does, at least).

Perhaps a better solution would be to tackle these completely reactively. Maybe set up tooling for someone (ideally, anyone, such as an interested support engineer from one of the victim domains; but I suppose this might add too much attack surface) to explore what spam has been targeting a particular domain name (with provisions for variations like subdomains like on Wix or Blogspot, and per-user URL path spaces like Medium or Google Sites). Some of this is already in place;

* [sites.google.com](https://metasmoke.erwaysoftware.com/domains?utf8=%E2%9C%93&filter=sites.google.com)
* [wix.com](https://metasmoke.erwaysoftware.com/domains?utf8=%E2%9C%93&filter=wix.com)
* [wixsite.com](https://metasmoke.erwaysoftware.com/domains?utf8=%E2%9C%93&filter=wixsite.com) (note the relation to the previous)

... but we should think about how to make this useful for reporting and possibly automation going forward.

## Useful Links

https://github.com/tripleee/SmokeDetector/tree/problematic-url-hosts is my personal but stale development branch for a simple `findspam.py` rule for this. The list of targeted domains will be out of date, but other than that, this was pretty much good to go when I had to abandon it for more pressing matters.

I discussed this with A J and he said he could probably help with the SQL for a Blazer query to help us isolate and perhaps add a tag to all relevant samples in metasmoke.
https://chat.stackexchange.com/transcript/11540?m=51244901#51244901

Halflife has a crude regex-based tag for finding some of these; see https://chat.stackexchange.com/search?q=tagged%2Fwebsite&room=65945 ... but just like my rule, this probably needs to be updated with many new victim domains.

## Additional context

The semi-automated reporting to Medium that @superplane39 used to be doing is a good demonstration of what this could be useful for; but I would like to see it developed to the point where you could simply point Medium to a URL where they can monitor confirmed spam in their netspace completely without our active involvement.

**Comment by ArtOfCode-** [comment]
I think I see what you're going for. This could potentially be as simple as defining a regex that dictates when two domains are in the same hostspace - i.e. `[^\.]+\.wix(?:site)?\.com` would define sites in the Wix network. That could be defined as a new `DomainGroup` model to let people (admin? core?) keep track on these, and then it just needs someone to email the relevant people at the hosts to let them know it exists.

**Comment by tripleee** [comment]
The Wix example is just an example. Grouping related domains would be a nice exrta, but the focus of this ticket should be making it easy for an individual domain owner to assess the impact on them.

What I'd like is to be able to say "hey, X, here is all the recent spam [by this spammer] abusing your resources, and here's all the other similar spam tageting Y, Z, Aa, Ab, Ac, Ad, etc if you'd like to see the bigger picture. Click here to get a live RSS feed (or whatever) going forward."

**Comment by ArtOfCode-** [comment]
[status: completed] with metasmoke DomainGroups and domain group mailings.
