### ISSUE TITLE
Revert (or allow to revert per room) the change made in #3321

### ISSUE THREAD

**Issue by Tyler-H** [Charcoal-SE/SmokeDetector#3420]
In change #3321, offensive/potentially bad titles are now censored in all rooms except MetaSmoke. This is a regression in functionality as we now have to click through to the question to see what the title is. Prior to this, such reports were able to be handled/responded to potentially without ever clicking on the link. I also don't see any convincing reason to censor offensive titles in the first place. It's also a little odd that the post that inspired change #3321, #811, was declined... it seems like rather than turning offensive titles off for all rooms, it should have simply been turned on for the one room where Catija was concerned about offensive titles "being hurled at them".

Preferably, I'd like to see this reverted *completely*, as the reasoning given for excluding MetaSmoke room frankly applies to *all* rooms: if you are hanging around a room where SD is posting these reports, you've signed on for the occupational hazard of having some bad stuff put in front of your face every once in a while.

However as a secondary solution, I'd like the ability to have it turned off for additional rooms (in this case, namely SOCVR, as I'm a Room Owner/participant there).

I'm aware this is something that's been discussed and may be getting implemented as a Hacktober challenge, but I didn't see a dedicated issue yet. I am also aware of #3353, but it's unclear whether this is something that would be handled by that PR.

**Comment by ArtOfCode-** [comment]
#811 was declined because it was an isolated incident. #3321 was created because it came up again a number of times in the intervening period. 

> Preferably, I'd like to see this reverted completely, as the reasoning given for excluding MetaSmoke room frankly applies to all rooms: if you are hanging around a room where SD is posting these reports, you've signed on for the occupational hazard of having some bad stuff put in front of your face every once in a while.

Not necessarily. Tavern in particular comes to mind. As it's the general chat for Meta, it gets more first-time SE users and first-time chatters; the same is true of a number of sites' main rooms where Smokey posts. The _ability_ to turn off offensive titles without turning off the reports for them is a useful ability to have.

The author of #3353 may be working on this, since someone else got to the feature they were originally working on before them. We'll give them a bit of time to see if they've got work ongoing on this; undercutting them twice would be rather churlish. If not, then we can implement a new room role to allow rooms to opt out of no offensive titles; CHQ will have that turned on, other rooms can request it.

**Comment by makyen** [comment]
A [comment I made on PR#3353]](https://github.com/Charcoal-SE/SmokeDetector/pull/3353#issuecomment-545107266) had an idea for an outline of how to implement this. Given that a new PR should be created to cover this, it's better to have the information here):

> Well, given that room configurations are controlled by rooms.yml, what's probably needed is an additional configuration option in rooms.yml under `msg_types:` which is something like:
> 
>     - dont-mask-offensive-titles
> 
> That config would then be placed under all rooms in which offensive titles shouldn't be masked (i.e. Charcoal HQ).
> 
> Then `chatcommunicate.tell_rooms` would need to be able to be called with appropriate arguments indicating 3 different cases: 
> 
> 1. The message should be sent ignoring that config option (i.e. just obeying the criteria as they currently exist). In other words, basically what happens now (i.e. all current calls to `chatcommunicate.tell_rooms` should continue to work).
> 2. The message should be sent to rooms qualifying by the other indicated criteria, but also requiring having the `dont-mask-offensive-titles` config option.
> 3. The message should be sent to rooms qualifying by the other indicated criteria, but also requiring *not* having the `dont-mask-offensive-titles` config option.
> 
> This could probably be handled by adding that config option to Charcoal HQ in rooms.yml and using it as a prop in the `has` and `hasnt` arguments.
> 
> There might be a better way to do it, but that's what I see off the top of my head. I've also only taken a relatively cursory look at the code in this area, so might be missing something.

**Comment by ArtOfCode-** [comment]
Completed with 627fbc6e85d9f3aaa661af8bef0fac46566d1e1c.
