### ISSUE TITLE
CI tests have been silently failing for the last month

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/SmokeDetector#3467]
Our CI tests have been silently failing for a month.

The last build on the master branch that *actually* passed CI testing was build number 56777 [on 2019-10-08](https://circleci.com/gh/Charcoal-SE/SmokeDetector/56777) (commit [297e0f9c](https://github.com/Charcoal-SE/SmokeDetector/commit/297e0f9cc45d97f92f99e25e642dd6acda2a4b74)). The first build that failed was [just after that](https://circleci.com/gh/Charcoal-SE/SmokeDetector/56779) ([commit 61cf8381](https://github.com/Charcoal-SE/SmokeDetector/commit/61cf8381d3d8b9dd7ad7f59d0b1d5e28fd18e5e4)).

#### A good run:
The output for a good `pytest` looks like (note the existence of a summary of the test results) (from [this CircleCI run](https://circleci.com/gh/Charcoal-SE/SmokeDetector/56777)):
[![passing pytest output][1]][1]

#### `pytest` exiting early without completing the tests, but not indicating failure:
The output of the crashing/failing `pytest` runs looks like (note lack of summary) (from [this CircleCI run](https://circleci.com/gh/Charcoal-SE/SmokeDetector/56779)):
[![crashing pytest output][2]][2]
The testing output looks so close to the correctly functioning one because the tests which were causing the issue were in the last few of the entire sequence. That's just where they happened to be located. Changing the order of the tests just results in the tests following the ones with the issue not being run.

I've submitted PR #3468, which resolves the immediate issue of the tests crashing. However, that PR won't resolve the issue that `pytest` *can* crash and silently fail. Until that's resolved, we need to be periodically manually checking that `pytest` actually completes.

<sub>Note: the title of this is tending towards click-bait. That's intended. The fact that `pytest` can silently fail is something which our contributors should be aware of, so they check for it from time-to-time. Once a bit of time has passed, I expect to change the title to something less like click-bait.</sub>

  [1]: https://i.stack.imgur.com/zpXQr.png
  [2]: https://i.stack.imgur.com/k6vcO.png

**Comment by ArtOfCode-** [comment]
That's a warning, not a test failure - currently status-bydesign. If we want to fail on warnings too, I imagine we can do that somehow.

**Comment by makyen** [comment]
@ArtOfCode-  I appear to have failed to communicate. The first image is a correctly functioning test that outputs a summary, which indicates some warnings (warnings that we don't necessarily care about). The second image is of a run of `pytest` which did not complete and aborted early. It should show a summary indicating any warnings and the last line of `pytest` output showing the number of failed, passed, skipped, and warnings resulting from the tests. Importantly, `pytest` should have exited with an exit code other than 0, due to the failure, but it didn't. The test run that produced the second image has 1 failing test and 2 tests which were never run, because the failing test exited from `pytest` prior to the last two tests running.

As an example, see the `pytest` output in [this CircleCI run](https://circleci.com/gh/Charcoal-SE/SmokeDetector/59305?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), which is from `pytest` exiting early, compared to the `pytest` output from [this CircleCI run](https://circleci.com/gh/Charcoal-SE/SmokeDetector/59307?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), which has the tests completing.

Looking at the last two lines of the above tests where the number of tests run in test/test_spamhandling.py is indicated:

    Failure/exit early:
    test/test_spamhandling.py ...............................
    Completed/correct:
    test/test_spamhandling.py ..................................             [100%]

Note the 3 additional tests indicated for test/test_spamhandling.py and the indication that 100% of the tests were run.


### Resolving the potential ongoing issue
I've played around with fixing it a bit more since I posted this issue. I have code that prevents the problem from occurring, even when there are tests which cause the same type of failure. I'm still determining the best way to integrate it into all of the tests. Doing so should be relative easy.
