### ISSUE TITLE
Supress reposting of all-caps posts

### ISSUE THREAD

**Issue by Infinite-Recursion-8** [Charcoal-SE/SmokeDetector#36]
Report an all-caps title only once, and then automatically ignore it. If no-one edits it after the first report, it is unlikely to be edited by Tavern folks on subsequent reports. 

Original request by Behaviour in The Tavern on the Meta: http://chat.meta.stackexchange.com/transcript/89?m=2858969#2858969

**Comment by ProgramFOX** [comment]
As I said to Behaviour in the Tavern, it is a good idea, but the list might grow very long and take many disk space.

What do you think about storing those all-caps titles for 24 hours and then remove (un-ignore) them? After 24 hours, it's unlikely that they still be in all-caps.

**Comment by ProgramFOX** [comment]
Closed via https://github.com/Charcoal-SE/SmokeDetector/commit/6b781e9f85dc6891a07fb51e4d9fd8788dce44a5

**Comment by Manishearth** [comment]
Wait, are you storing a list of all previously stored allcaps posts?

We have a mechanism in place for ignoring edited posts but it deliberately has a small cache, I didn't want to accumulate titles over time. I don't think we should do that here either.

**Comment by ProgramFOX** [comment]
They are just stored for 7 days. Then the list certainly won't grow too large.
