### ISSUE TITLE
Create unit tests for ws.py

### ISSUE THREAD

**Issue by hichris1234** [Charcoal-SE/SmokeDetector#37]
We inadvertently break ws.py from time to time. With Travis, we should be able to catch most of these errors by having unit tests for ws.py.

**Comment by ProgramFOX** [comment]
Partially done in https://github.com/Charcoal-SE/SmokeDetector/commit/989ee99870cb18b9630053df23e1b435d35afb6d

That commit adds tests for `parsing.py` (which was added in #38).

**Comment by Undo1** [comment]
@hichris1234 Thoughts on how this could work? Seems like almost anything would require network access, and relying on that for a test feels weird, somehow.

Perhaps there's a way to spoof a websocket connection/message and check for the right chat messages coming out?

**Comment by hichris1234** [comment]
That's pretty much what we do right now: https://github.com/Charcoal-SE/SmokeDetector/blob/master/test/test_chatcommunicate.py. The problem is our test coverage, while decent, still needs to increase -- we've broken the occasional chat command because of a lack of tests.

Not exactly the most urgent thing right now, but nice to have on the backburner for *some* future time.

**Comment by AWegnerGitHub** [comment]
These tests were a huge help when I refactored the chat commands a few
months ago too.

I'm happy with more tests, especially in areas we break.
