### ISSUE TITLE
Switch to most recent regex library

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#3713]
CI failed earlier today because the `regex` library had received an update which rendered it incompatible with our use.

@Makyen implemented a quick fix to pin it to an older version, but we really should be looking at changing our code so it works with the latest upstream: https://github.com/Charcoal-SE/SmokeDetector/commit/e966084ebdf8f878355b911eb17b6920b46e695e

In some more detail, we pass in the `city` list from several places in our code, and the latest version of `regex` now rejects calls where that list ends up not being used by the regex.

Ideally, we could persuade upstream to implement a new call which accepts unused arguments.

**Comment by makyen** [comment]
I've opened an issue, [New exception "ValueError: unused keyword argument" breaks use case](https://bitbucket.org/mrabarnett/mrab-regex/issues/357/new-exception-valueerror-unused-keyword), in the `regex` package's Bitbucket repository.

**Comment by makyen** [comment]
The resolution of the issue in the `regex` package's  repository was to implement a keyword argument, `ignore_unused=True`, which would prevent the exception from being raised. I've adjusted all of the places where we pass a named list to `regex.compile()` and changed requirements.txt to `regex>=2020.1.8`. The `ignore_unused=True` argument will be ignored by earlier versions of the `regex` package.

Current SD instances should not need to update. When they do update, the requirements.txt file should result in them jumping over the 2020.1.7 version which would still cause SD to crash.
