### ISSUE TITLE
Travis ImportError: No module named 'pep8ext_naming'

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#3737]
### What problem has occurred? What issues has it caused?
A couple of recent builds failed due to what looks like a `flake8` module problem on the Travis side (?)

E.g. https://travis-ci.org/Charcoal-SE/SmokeDetector/builds/649816066?utm_source=github_status&utm_medium=notification

https://chat.stackexchange.com/transcript/message/53524000#53524000

### What would you like to happen/not happen?

The build should succeed, like it still does on my laptop.

I'm guessing the failed module load is what causes everything after that to go downhill, but I could be wrong.

**Comment by tripleee** [comment]
Related? https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1664077.html

**Comment by tripleee** [comment]
Actually all builds after this one from yesterday have been failing:

https://travis-ci.org/Charcoal-SE/SmokeDetector/builds/649654411?utm_medium=notification

I can't tell if it's significant but one difference seems to be that Travis now downloads and installs Python 3.5 in order to run this test.

**Comment by makyen** [comment]
The issues we had with Travis CI failing for a day and a half appear to have been that the caches on Travis had become corrupted. The problems stopped when I manually cleared all the caches. If that needs to happen at some point in the future, I found it necessary to log into Travis as SmokeDetector, and delete all the caches on [this page](https://travis-ci.org/Charcoal-SE/SmokeDetector/caches).
