### ISSUE TITLE
PR-ish: Update privilege levels wiki page

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#3846]
https://github.com/tripleee/SmokeDetector-wiki/commit/0559d943ed0a69989041aa7aa52bf536e6aa72a7 proposes an update to the privileges wiki page, as discussed in an earlier thread.

Unfortunately, there is apparently no way in Github to create a PR against the wiki, although you can, as I have here, create a fork.

The proposed edit reorders and refactors the page somewhat, and attempts to spell out in more detail what admin actions are required to grant a specific privilege. (These additions probably need review in particular.)

**Comment by tripleee** [comment]
@ArtOfCode- @makyen review-pls?

**Comment by ArtOfCode-** [comment]
Looks broadly good to me. Interested to hear what Makyen thinks too.
