### ISSUE TITLE
Use one single SE API filter globally

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/SmokeDetector#4145]
Originally mentioned by @makyen here: <https://github.com/Charcoal-SE/SmokeDetector/pull/4074#pullrequestreview-441244797>

We have several places where an API filter is specified directly, and in most of these cases what we want is almost identical. Aggregating these into one filter in GlobalVars is a better idea for reasons of simplicity and maintainability.

**Comment by user12986714** [comment]
(antifreeze)

**Comment by makyen** [comment]
This was done in PR #7395.
