### ISSUE TITLE
Make SmokeDetector's code pass Flake8

### ISSUE THREAD

**Issue by ProgramFOX** [Charcoal-SE/SmokeDetector#43]
[Kevin Brown suggested](http://chat.stackexchange.com/transcript/message/19713459#19713459) to use something like Flake8 for the source checks. But in the current state, there are too many warnings to use it for actual tests. Hence, we should make SmokeDetector's code pass Flake8 (except warning E501, which means "too long line", and should not always be changed). /cc @kevin-brown

**Comment by hichris1234** [comment]
Do we have a list of these warnings? Can PyCharm run the tests automatically?

**Comment by ProgramFOX** [comment]
Here's a full list of warnings, with the directories ChatExchange and bayesian excluded:
https://gist.github.com/ProgramFOX/cedf2b79bf3c6461c19d

**Comment by ProgramFOX** [comment]
All Flake8 warnings (except the line length error, E503) have been fixed now.
