### ISSUE TITLE
Allow optional reason arguments to be surrounded by smart quotes in addition to straight quotes

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#4345]
The report and scan options support passing an optional reason for reporting posts in "quotes". However, that option only works for "straight quotes", and not  “smart quotes” (unique characters for beginning and ending quotes).

On Windows and Linux computers, and Android devices, this isn't much of an issue, as the keyboard types in straight quotes by default. However, Apple devices (both macOS and iOS) type smart quotes by default: in order to type a straight quote on iOS, one must tap and hold the quote key as if typing a special character. The two types of quotes are hard to tell at first glance, so it's not completely clear why a report command fails for some reason if this happens. (This isn't merely an Apple issue: users of other platforms can easily configure their systems to type smart quotes, if they'd like to use those for some reason.)

Can we please make SmokeDetector's report and scan commands recognize and accept smart quotes for the optional reason argument, and not just straight quotes?

**Comment by tripleee** [comment]
I think they can be turned off on Apple devices, too; I certainly don't suffer much from them (though the text replacement feature on IOS insists on switching to (not so) smart quotes when expanding a canned phrase).

A complication is that different languages use different quote marks, though I don't know if the "smart" quotes are quite so smart.  See e.g. https://jakubmarian.com/map-of-quotation-marks-in-european-languages/

**Comment by Daniil-M-beep** [comment]
I have experienced this issue before, but this can be easily fixed on iOS:

1. Go to Settings
2. General
3. Keyboard
4. Turn off "Smart Punctuation"

I don't think we need to make this a feature.

**Comment by Daniil-M-beep** [comment]
Looks like consensus on this is agreed so I'll close it.
