### ISSUE TITLE
Improved dependency management

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#4514]
This started as a discussion in #4512 but I'm creating a separate ticket for visibility.

The convention to document dependencies in `requirements.txt` is weak and slightly cumbersome. Ideally, there should be a way to force Smokey instances to verify that they are complying with the dependency requirements of the code base at run time, and ideally fix the situation themselves, or abort if they can't.

**Comment by tripleee** [comment]
I hear [Poetry](https://pypi.org/project/poetry/) gets all the MOT[OS]Ses these days. I haven't looked into whether we can drive dependency installation programmatically but at least it seems to straighten things out a good deal.

**Comment by makyen** [comment]
I was under the impression we had previously rejected the idea of having SD automatically installing dependencies, with the primary reason being that SD is, potentially, a guest sharing a computer and installing dependencies might be disruptive to other things on the machine.

I'm definitely for us verifying that the dependencies which are installed match the requirements specified in requirements.txt and user_requirements.txt. I'm less enthusiastic about automatically installing missing dependencies.

**Comment by tripleee** [comment]
I| you are in a virtual environment, that becomes a non-issue. I know not everyone is excited about requiring virtualenvs, but it's an option if we want it.

**Comment by teward** [comment]
> I was under the impression we had previously rejected the idea of having SD automatically installing dependencies, with the primary reason being that SD is, potentially, a guest sharing a computer and installing dependencies might be disruptive to other things on the machine.
> 
> I'm definitely for us verifying that the dependencies which are installed match the requirements specified in requirements.txt and user_requirements.txt. I'm less enthusiastic about automatically installing missing dependencies.

The way to solve this is to have SD install in userspace - i.e. `pip3 install --user -r requirements.txt -r user_requirements.txt`.

Or alternatively, package up Smoke Detector as a fully fledged application that would be installed in userspace via a setup.py or similar script, which would be able to handle dependencies.

THIS BEING SAID, the initial idea WAS to not have SD handle dependencies automatically because that could cause problems.  Not to mention as currently written, if dependencies update and they would affect NoCrash.py, you then need admin intervention anyways.

I don't think it's a good idea to have SD handle its own dependencies though.  That's why we have dockerfiles for spinning a docker instance or such.

**Comment by tripleee** [comment]
What about a hook in the startup script which refuses to go back online if `requirements.txt` has been updated since the last time it ran successfully? This would require manual intervention to clear up, but would presumably at least help the owner notice that something is amiss.

**Comment by makyen** [comment]
How about the person that wants to add code that requires a change to the requirements just coordinate this with the SD runners. The way we've handled this in the past is to merge just the update to the requirements.txt file to the desired packages/version, but not merge the code that needs it. The person making the change then pings the SD runners asking for them to update requirements. Once the requirements are updated by the SD runners, then the new code can be merged. It's a bit clunky, but doesn't take all that long. In general, SD runners need to be mostly available on the network anyway in case there are problems.

This only doesn't work if there's a time-critical need to update a dependency, which is a quite rare occurrence.

How much effort do we want to put into this?

**Comment by tripleee** [comment]
I'm fine with @makyen 's proposed procedure. If we agree that this is the current consensus, I'll document it in relevant places and close this as Wontfix.
