### ISSUE TITLE
Prioritize Autoflagging by activity.

### ISSUE THREAD

**Issue by magisch** [Charcoal-SE/SmokeDetector#457]
In preparation for when we're casting more then 1 auto flag, it would be nice to use flags from people who aren't currently active first in autoflagging (so the people who are active can use their manual flags on top of the auto flags).

For that, I propose basing it on feedback and autoflags.

Create a priority list, and people who haven't feedbacked a post or been made to autoflag a post for the longest will be prioritized.

**Comment by tripleee** [comment]
Maybe this should be a user preference.  At least initially, I would like to be able to see what the system is doing in my name.

**Comment by Undo1** [comment]
Closing because this belongs on the metasmoke repo.
