### ISSUE TITLE
Unable to start SmokeDetector

### ISSUE THREAD

**Issue by markyi370** [Charcoal-SE/SmokeDetector#465]
Reference here: https://github.com/Manishearth/ChatExchange/issues/134

It appears that I cannot login to any site other than stackexchange.com. The temporary hack I am using is to remove all references to any room other than the fake "Charcoal HQ" I set up.

**Comment by teward** [comment]
Did you properly configure your environment variables per the instructions?

Also note that SmokeDetector won't work *proper* without credentials, which you are aware you do not have.

**Comment by ArtOfCode-** [comment]
...

I'm gonna ask the dumb question. Does the sock that you're trying to run this with *have an account on those chat servers*?

**Comment by markyi370** [comment]
Well, I was able to get this working eventually. See #469.
