### ISSUE TITLE
Refactor Smokey to add setting to run in CHQ only

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#469]
Usually when you fire up a test copy of Smokey, you don't want it to go posting duplicate reports in the other rooms we report to (Tavern, SOCVR, AskUbuntu etc). 

Currently the only way to do this is to change the room IDs for each of these in the code to a throwaway room, where it won't bother anyone. However, this is messy, and may intefere with pulling in code changes etc.

We should refactor our code so that we can safely comment out other rooms without breaking smokey, or we should add some sort of `test` setting in config to disable them all.

**Comment by markyi370** [comment]
Hmm... I was able to modify Smokey to only run in my test room. If you'd like, I can try and dig up exactly what I changed. I wasn't recording it then, but now reading this issue, it might be helpful.

**Comment by markyi370** [comment]
I've made a gist with the necessary changes (I think):

https://gist.github.com/markyi370/91a2e1b61ded6ae73005791d557dcf6f

All that remains to be done is to add a commandline/config option, rather than using comments, like I did.

**Comment by Undo1** [comment]
Took a different approach - instead, we extend `ChatExchange.room` to intercept calls to `Room.send_message`.
