### ISSUE TITLE
Removing the "naa" feedback

### ISSUE THREAD

**Issue by Fortunate-MAN** [Charcoal-SE/SmokeDetector#483]
Smokey was created to classify spam, not LQP. The "naa" feedback serves no purpose IMO in Smokey. It has caused confusion many times, and I do not see the reason for this feedback type to be there anymore.

Relevant discussion in chat: http://chat.stackexchange.com/transcript/message/35002373#35002373 (read below that).

**Comment by Cerbrus** [comment]
:+1:
Whether something answers a question or not is irrelevant, when determining if said post is spam.

**Comment by ArtOfCode-** [comment]
I'm unsure. I *think* I was one of the proponents for adding it what must be a year or more ago now - and there must have been a good reason for that. I'd like to find out what that is before we just remove it.

**Comment by teward** [comment]
NAA has been implemented for at least a year, now.  My *guess* is to track cases where a filter catches half-positives that are not spam, but are still "valid".  (That is to say, something posted that matches the filter but isn't a `tpu-` worthy case)  @Undo1 would know more about this...

**Comment by Undo1** [comment]
It serves to identify posts that aren't spam, but that we'd still be happy if they were blocked before being posted. 

For example, there's a big difference between a group of posts that are 99% tp / 1% go, compared to a group that is 99% tp / 0.95% naa / 0.05% fp. The latter is much more representative of the potential for Real Damage if one of our metrics was allowed to integrate with the system (or was given extra flag weight).

**Comment by teward** [comment]
Tracking these metrics is a good thing.  I'm going to vote *against* removal of the "naa" feedback.

**Comment by Cerbrus** [comment]
That makes sense @Undo1.  
While this still applies:

> Whether something answers a question or not is irrelevant, when determining if said post is spam.

I understand it can be desirable to track some types of not-spam.

**Comment by angussidney** [comment]
Alternatively rename it to Low Quality (or use a similar name), then it can be associated with questions too. Then we can add NAA as an alias for it.  

FDSC could then bind NAA and VLQ in answers (and possibly delete?) to the LQ feedback along with VLQ and off-topic flags/closevotes for questions.

**Comment by Undo1** [comment]
Torn on that one. On one hand, there *have* been a few (small number, from what I've seen) of situations where this would be useful. 

On the other, I could make a fairly strong argument that it's an order of magnitude easier for us to accurately gauge whether an answer should have been posted than whether a question should have been posted. Some (many) sites have *really weird* rules around questions, and only a few have those around answers (sorry, SR and HR...)

**Comment by ArtOfCode-** [comment]
Hey, at least we have mods from SR and HR around to make a call :)

**Comment by Fortunate-MAN** [comment]
heh, fair enough.
