### ISSUE TITLE
Migrate away from Travis

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#4841]
Travis-CI.org is shutting down at the end of the year. We have been encouraged to migration to travis-ci.com

---

Hi there!

As you’ll no doubt have noticed, Travis CI has, for some time, been split between travis-ci.com and travis-ci.org. This was initially planned to enable open-source and commercial/private projects to be distinctly separate, but [back in May 2018, we announced](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps) that open source builders would have the opportunity to build and test their projects under travis-ci.com, meaning your public and private repositories could be managed under one domain with a consistent interface and build environment.

In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely on December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain. 
 

What this means for you

The main thing to expect is that your projects will be built and tested with the same speed and robustness as you’ve come to expect from Travis CI - but also with great new features such as support for AWS Graviton2 which is only available on travis-ci.com. Open-source projects will be free as they always have, with lighting fast builds provided by partners like Packet.

We encourage you to migrate your existing repositories that are currently on travis-ci.org over to travis-ci.com as soon as possible, enabling you to identify any additional changes required to your code or configuration well in advance of the December 31st deadline. We’ve documented everything you need to know in order to migrate your repositories, and of course, you can reach out on the community forum for any additional help.

If you have any questions or concerns, please feel free to contact our support team who will be happy to talk through any migration queries you may have!
 

Happy building on travis-ci.com!
 

The Travis CI Team

**Comment by NobodyNada** [comment]
It's easy to migrate, but is it worth it? We currently test everything with 3 CI providers (Travis, Circle, and GH Actions); is there a reason not to just drop Travis?

**Comment by NobodyNada** [comment]
And...TravisCI [just announced](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) that they’re no longer offering a free plan like they used to. OSS projects now receive 10,000 minutes free (lifetime, not monthly — i.e. they don’t renew every month), and every time we run out we would have to fill out an application for renewal.

I vote we just drop Travis altogether, unless there’s a *really* compelling reason not to.

**Comment by AWegnerGitHub** [comment]
Agreed. If they are making it life time, there is no reason we should stick with them while other options exist.

**Comment by tripleee** [comment]
I retitled this, as I guess we have a consensus now to abandon Travis rather than migrate to the .com version.
