### ISSUE TITLE
Remove mobilunity from the database

### ISSUE THREAD

**Issue by Mobilunity-Com** [Charcoal-SE/SmokeDetector#4846]
Dear Team, 

i would like to ask you to remove mobilunity\.com from your list.
We indeed outsourced our seo for a short period of time and subcontractors managed to do a huge mistake by posting promotional post. We've already added stackexchange as a special resource, which shouldn't be approached, to our databases and promise not to use it in promotional channels anytime in future.

Thank you for your consideration!

**Comment by ArtOfCode-** [comment]
I've sent an email to the address listed on your profile, @Mobilunity-Com, to confirm that this is coming from a representative of your organisation.

The last confirmed spam we saw containing `mobilunity.com` was 2020-03-16 09:56:22Z, i.e. _just_ over 6 months ago, so once this request is confirmed the domain will be demoted to the watchlist per our [removal process](https://charcoal-se.org/smokey/Process-for-blacklist-removal); if a further 2 months pass with no spam seen, the domain can be removed fully.
