### ISSUE TITLE
Strike-through editable Smokey messages which refer to already-deleted posts

### ISSUE THREAD

**Issue by ByteCommander** [Charcoal-SE/SmokeDetector#486]
In rooms like the Ask Ubuntu General Room, Smokey deletes its messages if the reported spam post gets deleted within the 3 minutes time frame during which the chat message can still be edited.

However, in the Charcoal HQ room, we want to keep all reports even after they get deleted for logging purposes, which is good. The downside is that you always have to click the links in recent messages to often find out that the linked post already got deleted.

I propose that if a reported spam post gets deleted within the 3 minutes time frame, Smokey could edit its messages about that post in all rooms where it is not configured to delete the messages to strike-through either the whole message

> ~~[ SmokeDetector | MS ] Bad keyword in title, phone number detected in title: 8875513486 best vashikaran IN Mohali by mohinimantra on askubuntu.com~~

or just a part of it, e.g.

> ~~[ SmokeDetector | MS ]~~ Bad keyword in title, phone number detected in title: 8875513486 best vashikaran IN Mohali by mohinimantra on askubuntu.com

This would help us in the Charcoal HQ to identify which reports might still need some more "love" and which are already handled so that we don't need to waste any time there, without removing any information from the chat transcript.

**Comment by ByteCommander** [comment]
This is related to #226 somehow as it serves the same purpose of helping users to know what reports might still need more attention.

**Comment by angussidney** [comment]
While I do think this is a good idea, I would much rather that #226 be implemented first. @ArtOfCode- any chance you could take another look at that API route and see if you can reduce the time it takes to run the query?

**Comment by ArtOfCode-** [comment]
@angussidney That's gonna need @Undo1's help - the query runs just fine locally, either way I express it. It was only ever on the server that we had a problem with it, which Undo will need to investigate.

**Comment by angussidney** [comment]
Also, for the record, if we decide to go ahead with this I think that the strikethrough should be less intrusive, e.g. Only strikeout the post title or append (deleted) to the end of it.

**Comment by teward** [comment]
-1 on the strikethrough - too evil on the eyes.

+1 on appending an italicized "deleted" to the end of the message, but we have to obey the rules of editing - Smokey is not a diamond moderator so it can't edit a post after the edit period expires.

**Comment by markyi370** [comment]
Can we make Smokey a mod @ThomasWard?

**Comment by Undo1** [comment]
No.

**Comment by AWegnerGitHub** [comment]
No

**Comment by NobodyNada** [comment]
@markyi370 I highly doubt that would ever happen.  We'd need the Stack Exchange team to do that, and while they *do* appreciate us, they're not going to give our chatbot a dangerous level of privileges just so we can implement a minor feature.

**Comment by ByteCommander** [comment]
If anything, it would be useful to grant Smokey the exclusive privilege to edit/delete only its own chat messages without time limit. However, such an isolated privilege does probably not exist and would take some development effort on the side of Stack Exchange. Therefore I doubt this will happen, at least not in the foreseeable future.

**Comment by markyi370** [comment]
Could we add an extension to FDSC that will say "Example post name" has been deleted?

**Comment by Fortunate-MAN** [comment]
@markyi370 I don't see the reasoning behind doing that. You only use FDSC _while_ you are accessing the post, and if the post is deleted, you will see it on the webpage itself, why make it more complex?

If you are referring to the case in which you have already loaded the flag dialog, and the post has been deleted, in most cases you will notice that the page will reload (leaving out exceptions, which has happened to me sometimes).

**Comment by markyi370** [comment]
@Fortunate-MAN Fair enough, But while we're mentioning FDSC, it doesn't refresh for me, **ever**. Instead, I get an error when I hit `Flag (Question/Answer)`.

**Comment by Fortunate-MAN** [comment]
@markyi370 I still do not see the reason behind adding this feature though. This happens rarely (at least to me), and on most sites (except those like SO), you normally have enough time to flag.

**Comment by ArtOfCode-** [comment]
@markyi370 What's the error? Drop it in CHQ.

**Comment by angussidney** [comment]
@markyi370 FDSC requires you to have the Reviewer privilege on MS before you can give feedback via it, so that would be why it isn't working

**Comment by ArtOfCode-** [comment]
@angussidney No, it was a different error - the post was already deleted by the time Mark got to flagging it.

**Comment by markyi370** [comment]
@angussidney _Mark whacks himself in head_

That was my mistake. I meant the standard SE flag dialog not FDSC.

**Comment by teward** [comment]
@markyi370 That sounds out-of-scope here.  If the post is already deleted it will already error when you try and flag.  An "already deleted" change would need to be implemented by SE for that dialog, or a special userscript created.  (My opinion)

**Comment by magisch** [comment]
Here's an idea: Instead of keeping track of the entire thing more complicatedly, why don't we just use the existing functionality (that deletes SD posts as soon as the thread is deleted) and modify it to merely edit the posts in certain chatrooms? @Undo1 @teward @ArtOfCode-

**Comment by Undo1** [comment]
I'm going to close this and say that https://github.com/Charcoal-SE/userscripts/blob/master/autoflagging.user.js provides the necessary functionality, in an easier-to-manage form that lives client-side.
