### ISSUE TITLE
Improvements to Smokey's reports in chat

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#488]
There is some room for improvement of Smokey's chat messages. For instance, the quite valuable MetaSmoke link is sometimes dropped because of the length of the message. To make optimal use of the 'real estate', we should consider that the messages are seen both in general chatrooms by users who have hardly heard of SmokeDetector, and by hardcore spam fighters in Charcoal HQ.

Some discussion about this can be found [here](http://chat.stackexchange.com/transcript/message/35077541#35077541).

IIRC, feedback via chat depends on correctly parsing the report message, so one can't just change the message format without changing that logic too. Also, I've seen some chat messages in the test part of the repository, which also need to be adjusted.

Here is a list of possible improvements. Some of them should be 'permanent' changes, others should only be changed if there's not enough space.

 - [x] The first link ([SmokeDetector]) isn't useful. In Charcoal HQ, you can find the link to GitHub in the starred Project Links message, or in the chatroom's description. It should be dropped there; for *other* chatrooms, it should probably link to http://charcoal-se.org/#whats-smokey because that's much more informative for a newcomer than the GitHub repository itself.
 - [ ] We can remove the spaces, so that the first part looks like [SmokeDetector|MS] *if necessary*.
 - [ ] Some of the reasons can be made shorter (at least, the way they're displayed in chat), e.g. "website" -> "site", "repeated URL at end of long post" -> "repeated URL", *if necessary*. [See here](http://chat.stackexchange.com/transcript/message/35077601#35077601) for more examples.
 - [ ] Reasons can be grouped, e.g. "bad URL, bad keyword (x2), blacklisted/pattern-matching website (x4), repeated URL" *if necessary*.
 - [x] List can be shortened (e.g. Reason 1, Reason 2, Reason 3, Reason 4, Reason 5, +2 more)
 - [x] The site, usually written out in full like `graphicdesign.stackexchange.com`, can be shortened to `graphicdesign.SE` *if necessary*.
 - [x] Add autoflagged information (if that's even possible - maybe something for the long term) to the messages (in Charcoal HQ only). This is also something a userscript could do.

Any thoughts?

**Comment by DavidPostill** [comment]
Agree to all suggestions

**Comment by ArtOfCode-** [comment]
Mostly agree. Autoflagging is truly async, so including info in the initial report is not possible without significant changes somewhere. Probably a userscript job. As for the rest, they're all worth considering, though we should start with whatever saves us the most space and loses us the least information.

**Comment by tripleee** [comment]
I'm not sure abbreviating reasons is the way to go. As the set of reasons is growing, we could expect to end up with dozens of reasons with fairly similar names, and keeping the full name is then less redundant and more informative.  In that scenario, even aggressively abbreviated reason names might not fit within the message limit, anyhow.  How about just breaking up the notification into multiple separate chat messages (only when necessary!) instead?

**Comment by Undo1** [comment]
Is there any reason we couldn't just start truncating the reason list? If a post is caught by a gazillion reasons, no one really cares which ones it was. If they do, we have metasmoke.

**Comment by Undo1** [comment]
I'm opposed to removing the tagline, especially in CHQ only. It's (1) good to have some consistency, and (2) good to have a link. I'd be in favor of changing the link, if we can get it suitably shortened.

**Comment by ArtOfCode-** [comment]
@Undo1 - https://goo.gl/6ylPSc

**Comment by j-f1** [comment]
How about adding a `[ deleted ]` to the end of the message if the post is deleted in <2 minutes?

**Comment by angussidney** [comment]
@j-f1 See this conversation: https://github.com/Charcoal-SE/SmokeDetector/issues/486

**Comment by j-f1** [comment]
@angussidney Thanks!

**Comment by tripleee** [comment]
+1 for Undo's suggestion to simply abridge the full list of reasons if it's long. My earlier comment was about shortening the individual reason strings until they can all be squeezed in, which won't necessarily scale, and impedes legibility. A nice detail would be to keep the most exotic ones, and then just defer to the full Metasmoke report. "Kangaroos, black magic in title + 23 more".

**Comment by j-f1** [comment]
Another option would be to call the metasmoke API to get the report ID, to avoid having the long link twice in the message.

**Comment by Undo1** [comment]
metasmoke reports are async; the record doesn't even exist when the chat message is sent. On platforms like Thomas' Aurora, it'd probably be fine to wait for the round trip, but on my Pi you're looking at +/- a second or two.

**Comment by ArtOfCode-** [comment]
Given how (relatively) slow SE chat is already, I wonder if two seconds really makes a difference.

**Comment by Undo1** [comment]
Yeah, it'd probably be doable. Just needs to be tolerant of the times metasmoke drops a post due to UTF stuff; threads have been the cheap way to isolate us from that.

**Comment by ArtOfCode-** [comment]
If that happens, metasmoke should just return a 500 - no difference in response time, just code, which we can then ignore (or alert about).

**Comment by angussidney** [comment]
See 3242881

**Comment by angussidney** [comment]
Sitenames are shortened, the reason list is limited to 5 items, and the Smokey link at the beginning points to a better place. I'm going to say this is completed enough to be satisfactory.

**Comment by angussidney** [comment]
I think I had to revert one of the changes a while ago (hence I reopened), but it has been re-implemented again, so I'm going to close this.
