### ISSUE TITLE
Alias 'tpa' with 'tpu'

### ISSUE THREAD

**Issue by Unihedro** [Charcoal-SE/SmokeDetector#49]
... I'm asking for this because I seem to always reply with "tpa" by habit (from using Phamhilator) instead of tpu.

**Comment by Manishearth** [comment]
What does `tpa` mean?

`tpu` means "true positive and block user"

**Comment by Undo1** [comment]
@Manishearth there's another bot that uses `tpa` to mean "true positive and announce"
