### ISSUE TITLE
Improve Smokey’s CI notifications

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/SmokeDetector#512]
Currently, Smokey’s CI notifications look like [this](https://chat.stackexchange.com/transcript/message/35261439#35261439):

> [CI](https://circleci.com/gh/Charcoal-SE/SmokeDetector/4444?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) on f0116ea succeeded.
 
I’m [proposing](https://chat.stackexchange.com/transcript/message/35261579#35261579) that the commit hash be linkified and formatted as code:

> [CI](https://circleci.com/gh/Charcoal-SE/SmokeDetector/4444?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) on [`f0116ea`](https://github.com/Charcoal-SE/SmokeDetector/commit/f0116ea) succeeded.

**Comment by teward** [comment]
Addressed in https://github.com/Charcoal-SE/SmokeDetector/commit/8d6108cfc519d86f552195f92fcf61350af47fcc

**Comment by ArtOfCode-** [comment]
8d6108cfc519d86f552195f92fcf61350af47fcc
