### ISSUE TITLE
Manually reported question: Show which rules would have hit

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#513]
When a post has been manually reported, it's hard manual work to figure out if it was reported because Smoke Detector missed it (which is often a problem which we want to spend time on solving) or just because the reporter was quicker than Smokey (which of course isn't a problem at all).  Could the analysis be run on these questions after they've been reported, and included in the Metasmoke record, so that it's easier to see when we have missed something?

**Comment by tripleee** [comment]
Really a feature request for Metasmoke actually, I guess.  Is there a way to move it?

**Comment by Undo1** [comment]
I'd say it should stay here, actually - SmokeDetector has all the parsing code; this is something that would be implemented here, not in metasmoke.

**Comment by ByteCommander** [comment]
I'd like to give this issue a little *bump*...

**Comment by superplane39** [comment]
What would happen with the weight of the !!/report command with this? Could this theoretically result in manually reported post being autoflagged?

**Comment by iBug** [comment]
https://chat.stackexchange.com/transcript/message/42954284#42954284

Maybe implement a `!!/scan <URL>` command to force a scan on a given post, and nothing should happen if the post is all right.

**Comment by iBug** [comment]
#1634 is a good solution for this and it does all the job I wanted: Scan the post and report it, and if the post is all right then do nothing (it does reply *Post does not look like spam* as a clearer indication). It's rolled out and (hopefulley) good to use now.
