### ISSUE TITLE
test issue for testing stuff

### ISSUE THREAD

**Issue by Manishearth** [Charcoal-SE/SmokeDetector#53]
hodor

**Comment by erickt** [comment]
💩

**Comment by Manishearth** [comment]
Such impudence!

**Comment by erickt** [comment]
you can't stop me, muwahahah

**Comment by erickt** [comment]
laglaglag

**Comment by erickt** [comment]
tick tock, github.

**Comment by erickt** [comment]
still work?

**Comment by hichris1234** [comment]
I have to ask (now that you sent ~10 emails to 20 or so people): what were you testing?

**Comment by Manishearth** [comment]
Oh, sorry :stuck_out_tongue: 

We were testing if it was possible to block people from _organizations_ on github. Sadly it isn't.

Aren't there just five of us?

**Comment by Manishearth** [comment]
Oh, right, the repo has watchers too. Nevermind.

**Comment by hichris1234** [comment]
Yeah, 7 watchers @Manish.
