### ISSUE TITLE
Add a global website whitelist

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/SmokeDetector#532]
For example, `example.*` domains are *unlikely* to be used for spam. This feature would allow for filters like “Link at end of answer” to be ignored when a harmless website ends up at the end of the post.

[context](https://chat.stackexchange.com/transcript/message/35543033#35543033)

**Comment by teward** [comment]
This *may* be a duplicate of https://github.com/Charcoal-SE/SmokeDetector/issues/490
