### ISSUE TITLE
Discussion: Spam methods need multiple parts of a post

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#538]
This is related to #450 but will impact any [`rule`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L379) that has a `method` attribute. 

Currently, we pass one element of a post at a time to these methods:

    matched_title, why_title = rule['method'](title, site)
    matched_username, why_username = rule['method'](user_name, site)
    matched_body, why_body = rule['method'](body_to_check, site)

With the function definition looking like this:

    def has_phone_number(s, site):

To check if a username matches an embedded link, we need both the username and the body. This means that we need to do one of a few things:

### Option 1: Adjust function definitions

This option would add an optional `*args`/`**kwargs` parameter to each definition. 

    def has_phone_number(s, site, *args):

Which would be called like this:

    matched_body, why_body = rule['method'](body_to_check, site, username)

OR

    matched_body, why_body = rule['method'](body_to_check, site)

With this, we should be able to modify the code block to check if `args` has data and proceed as expected. The existing checks will have no *code* changes, just the definition will change slightly. The new function for the username/link similarity would be able to use the passed argument.

The downside of this is that we will still need to pass these arguments due to how we call the `methods`. They are called in this [`else`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L768) block and do not discriminate based on method name. Thus, all methods must accept these option arguments, even if they don't use them. 

### Option 2: Adjust method calls

This option would change how the `s` parameter in these methods is expected. Instead of a single value, it'd be a list/tuple/dictionary which the methods could then utilize. An example, with a tuple, would look like this:

    matched_body, why_body = rule['method']((body_to_check, username), site)

With this, the function definitions remain unchanged, but the code block in all of these methods would need to be adjusted to utilize the appropriate element in the passed object.

The downside of this is the same as Option 1. All of these methods are called the same way, so all methods would need these changes.

---

Thoughts? Other ideas?

**Comment by AWegnerGitHub** [comment]
I prefer option 1. This has a much lower impact on the existing code because all we need to do is add the optional argument to the method definations. Methods that don't utilize the data will ignore it and existing code will be unchanged. With Option 2, we need to determine what type of object to pass and then adjust all existing methods to utilize the appropriate element(s) of that object.

With option 1, though, we need to determine if we want to pass keyword arguments or positional arguments (and if this, what order).

**Comment by Undo1** [comment]
Possibly out of scope here, but it seems that creating a proper `Post` object to pass around would be best overall - things like this are starting to show the constraints of the 'basket of strings' information system.

**Comment by AWegnerGitHub** [comment]
Closed with https://github.com/Charcoal-SE/SmokeDetector/commit/286008515030269cc52f0ce41d2f2da23b9a30a1
