### ISSUE TITLE
Smokey tests fail to run on Windows

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#540]
Smokey Detector includes a Windows incompatible library: `sh`. This is clearly noticed when running tests locally. 

[`sh` will not support Windows](http://amoffat.github.io/sh/sections/faq.html#will-windows-be-supported)

[`pbs` will no longer be supported](https://pypi.python.org/pypi/pbs)

	ImportError while importing test module 'H:\Development\SmokeDetector\test\test_chatcommunicate.py'.
	Hint: make sure your test modules/packages have valid Python names.
	Traceback:
	test\test_chatcommunicate.py:3: in <module>
		from chatcommunicate import *
	chatcommunicate.py:10: in <module>
		import chatcommands
	chatcommands.py:13: in <module>
		from gitmanager import GitManager
	gitmanager.py:1: in <module>
		from sh import git
	h:\Anaconda\lib\site-packages\sh.py:36: in <module>
		support." % __version__)
	E   ImportError: sh 1.12.9 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

--- 

Is there an alternative we can utilize that will allow developers in both environments to work without the above error?

**Comment by teward** [comment]
VPS, Windows Subsystem for Linux maybe, and also VMs.
I don't think Smokey was designed to be Windows compatible...



*Sent from my iPhone.  Please excuse any typos, as they are likely to happen by accident.*

**Comment by AWegnerGitHub** [comment]
I disagree @teward. For a long time it worked just fine on Windows. My Zephyr bot is built using the same architecture as Smokey. 

It is the gitmanager module itself that makes it Windows incompatible, not Smokey as a whole.

**Comment by teward** [comment]
Well, I have an evil-potential solution.  Basically, looking at gitmanager, we can try and determine if the system is Windows or not and load a custom library that relies on `subprocess.Pcall()` and similar to handle git calls.  I can probably write this 'layer' but it'll be a very *hacky* approach to it.  And it'll take time for me to set up a testing environment.

The core issue is that `sh` is just a wrapper for the git commands being called on the shell - creating a Windows-compatible wrapper shouldn't be infinitely hard.  Making it all work proper, that may be tricky.

**Comment by teward** [comment]
Notes: This is going to be a massive hack - we'll need the library to exist in nocrash and in gitmanager.

**Comment by teward** [comment]
So, I've looked into this a little.  It'll be a hackish mess where we have to replace the `sh` library with, essentially, a single `git` command and have to specify the commands we want to execute as a string passed to a subprocess call.  This is... not very pretty actually, and very hard to actually get working the same way that `sh`'s `git` functionality operates.

Even with such hackish approach, it's got some headaches and evils with it, such as we then have to strip shell colors, etc. and we have to reapproach how we handle exit codes and git calls in many places.  For now, I'm going to mark this as 'status: declined', but we can revisit this in the future when we're all a bit less busy.  Between me, ArtOfCode, and Undo, we are all trying to figure when Smokey would be run in Production environments, and we can't think of any - we all currently run in Linux environments, either on our own systems or EC2 instances, or VPSes, or other such environments which support the `sh` module.

**Comment by AWegnerGitHub** [comment]
As a contributor who does not have a Linux environment readily available, I find this very disappointing.

**Comment by teward** [comment]
@AWegnerGitHub I think this is only a temporary state - we can revisit this when the primary developers are less busy, but not at this second.

**Comment by teward** [comment]
Note: The current approach will be to check if we're on Windows, and disable Git functionality there.  That way, we don't have to worry about 'git' failures.  (This may fail Flake8 though, not sure...)

**Comment by caffeineaddiction** [comment]
I created a docker env that can run SmokeDetector on any system that can support Docker

https://github.com/Charcoal-SE/SmokeDetector/pull/541

**Comment by ArtOfCode-** [comment]
Is Docker a *good-enough* solution, @AWegnerGitHub?

**Comment by teward** [comment]
@AWegnerGitHub indicated in Charcoal HQ they'd test the docker instance yesterday.  I did point them at my "Don't Support Git Functions" warning approach for Windows runs - untested, but ultimately doesn't require additional containerizaiton, etc. on the host system.  And eliminates the git function issues that @AWegnerGitHub  was complaining about.

This approach is in https://github.com/Charcoal-SE/SmokeDetector/tree/windows_git_warnings, also in PR #544, and one or both approaches may be useful enough for them.
