### ISSUE TITLE
Don’t delete false-positive chat messages in Charcoal HQ

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/SmokeDetector#548]
Currently, if you feedback `f` to a message from Charcoal HQ, it is deleted. This should not happen.

**Comment by teward** [comment]
This is currently a by-design item, are you saying you want to change this so it *doesn't* delete the message from CHQ?

**Comment by Undo1** [comment]
Actually, we tried a while back to prevent messages from being deleted in CHQ. It regressed at some point (or never worked in the first place).

**Comment by teward** [comment]
This should be fixed as a result of a recent commit.  We now compare the integer values of the Room ID for a given message, and the Room ID of CHQ, and if they are not equal delete.

We previously had `not object == object` comparison which isn't guaranteed to be identical.  The IDs are always going to be something we can compare on though.
