### ISSUE TITLE
Add a new option to ignore mathjax

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#562]
We already have a `stripcodeblocks` option avaliable for rules, how hard would it be to add a `stripmathjax` option?

Alternatively, should we ignore mathjax altogether? I'm pretty sure that the majority of FPs on Math.SE are due to something being picked up in the mathjax.

Inspired by [this](http://chat.stackexchange.com/transcript/message/35731754#35731754)

**Comment by teward** [comment]
One small headache might be that `$` and others are part of mathjax.  That is also used in other 'spam' detections...
