### ISSUE TITLE
Refactor Effort: Objects

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#579]
Related to #537 

We should consider a major refactoring effort to utilize objects instead of passing strings all over the place.

**Comment by Undo1** [comment]
Thomas is taking a look at this, see http://chat.stackexchange.com/transcript/message/36009471#36009471.

**Comment by teward** [comment]
https://github.com/Charcoal-SE/SmokeDetector/tree/classes_refactor is relevant.   I've currently started working on the "Post" object, and additional refactoring going forward will be necessary.

**Comment by teward** [comment]
Thanks to @Undo, we've merged a refactorization that uses a custom Post object for passing posts around.  So far, it looks to be working.  If there's any failures, we can revert the merge.

Other than the use of the Post object, what other 'objects' do we need to consider refactoring around to pass between functions?

**Comment by Undo1** [comment]
Feedback could be model-ified, but it's a lower priority item in my mind. Getting posts figured out is a huge thing, thanks!

**Comment by teward** [comment]
Subtask: #595 - Replace PostData from apigetpost.py with the Post object in classes/Post.py

**Comment by teward** [comment]
We can track subtasks of the Refactor here: https://github.com/Charcoal-SE/SmokeDetector/projects/2
