### ISSUE TITLE
Make sd gone move messages that are too old to be deleted

### ISSUE THREAD

**Issue by quartata** [Charcoal-SE/SmokeDetector#580]
Currently, `sd gone` attempts to delete the message and then fails silently if it's too old to be deleted. I think it would be better if it moved the message to a room like the Trashcan instead if it can't be deleted.

This requires some modifications to ChatExchange to add moving messages: I've had these changes in my [CE fork](https://github.com/quartata/ChatExchange-Source.Python) for quite a while (it works fine, TF2Goat uses it). I can make a pull request to move these commits (but not the unrelated threading changes) upstream to CE if we want to do this.

**Comment by ArtOfCode-** [comment]
What would be the point? `sd gone` removes one message; moving a message *creates* one new message.

**Comment by ArtOfCode-** [comment]
It... doesn't really have any specified purpose. I suppose it *can* be used to remove offensive stuff, but on the other hand that's an occupational hazard, and in practice it gets used haphazardly for any number of purposes (including removing reports for now-deleted posts, or re-reports, or error logs, or...)
