### ISSUE TITLE
Refactor: Feedback object model

### ISSUE THREAD

**Issue by teward** [Charcoal-SE/SmokeDetector#597]
It was stated in #579 by @Undo1 that we may want to create a Feedback object model, however this was very low priority.  This issue is created to add to the Refactor project for tracking.

**Comment by j-f1** [comment]
You could also add a note to the project to avoid creating an issue until you’re ready to take it on.

**Comment by teward** [comment]
I have the issue here because after PostData, this is my next task :)

**Comment by quartata** [comment]
@teward Was what we have now in `classes/feedback.py` basically what you were envisioning for this?
