### ISSUE TITLE
Leave a comment on autoflagged posts

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#617]
SmokeDetector could leave a comment on posts which have triggered the autoflagging threshold to further increase visibility, and also to guide the occasional user who wonders what they should do.

A link to a pertinent meta question might be useful to include.

Rough sketch for what to put in the comment:

> This post was identified as probable spam. To expedite its removal, please flag as spam (don't vote to close). If the spam diagnosis was incorrect, please reply to this comment.

The last sentence would obviously require some additional logic to set up something to look for replies to these comments.

Background (though nothing more than in this ticket really): http://chat.stackexchange.com/transcript/message/36253120#36253120

**Comment by tripleee** [comment]
Angus suggested replying to any posted comments instead but I'm still partial towards commenting as soon as we can.  http://chat.stackexchange.com/transcript/message/36253259#36253259

**Comment by angussidney** [comment]
Alternate idea: rather than posting a comment on all autoflagged posts, watch for comments on the posts, then respond to ones which say stuff along the lines of 'I'm voting to close...' or 'I'm voting to delete this answer as NAA because it's spam' with some sort of automatic reply

**Comment by tripleee** [comment]
As detailed in the chat, that seems less useful to me for a number of reasons.

**Comment by ArtOfCode-** [comment]
Replying to comments is more difficult, because we have to watch for them and detect which to rely to. I'd be in favour of leaving a comment as soon as we detect a post, and asking people to come to CHQ if it's incorrect.

> This post [was identified](https://metasmoke.erwaysoftware.com/post/54920) as [probable spam](https://meta.stackexchange.com/questions/291301/can-a-machine-be-taught-to-flag-spam-automatically) - please flag as spam to destroy it quickly if this is correct. If this is a mistake, please [let us know](http://chat.stackexchange.com/rooms/11540).

**Comment by Undo1** [comment]
I'd be against implementing this. It sounds like noise for [any post we would autoflag](https://metasmoke.erwaysoftware.com/flagging/logs) - for the purposes of this, we have a 100% tp rate. When we *do* have a false positive, this could change it from an internal discussion to an external one. 

And even though we had a featured mSE post for a week or so, we all know that not everyone saw this. This is a step in the direction of maintaining PR with 150+ sites. We don't have the resources to handle more than a couple 'why is some robot flagging stuff here' posts, so I don't think we should go provoke people into posting them.

**Comment by AWegnerGitHub** [comment]
Agreed with @Undo. This sounds like it is adding noise to posts that will
be removed shortly anyway.

**Comment by Undo1** [comment]
Closing as discussion on this seems to be dead. Additional comments welcome.
