### ISSUE TITLE
Evaluate CodeCov auto-comments

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/SmokeDetector#623]
A couple questions to think about with [these comments](https://github.com/Charcoal-SE/SmokeDetector/pull/622#issuecomment-290907754):

 1. Do we need/want them at all?
 2. If so, what would it take to get it to not post something on every PR? JF [mentioned](https://github.com/Charcoal-SE/SmokeDetector/pull/612#issuecomment-288526020) that there's a way to tell it to only post if there's a coverage change, but I haven't had time to look into it.

**Comment by angussidney** [comment]
I vote we only post them if there's a coverage change. Otherwise, they're pretty useless.

All that would need to be done is for us to add a `codecov.yml` file with the following contents:

    comment:
      require_changes: yes

**Comment by Undo1** [comment]
Done for now, we'll see if it works.

**Comment by quartata** [comment]
Looks like it works.
