### ISSUE TITLE
Ping users that auto-flagged a false positive

### ISSUE THREAD

**Issue by FelixSFD** [Charcoal-SE/SmokeDetector#625]
When a false positive was automatically flagged, we already see a [warning](http://chat.stackexchange.com/transcript/message/36461530#36461530) in chat. But if the affected users are not actively looking into the chat or get pinged by other users, their flags will be declined.

It would be nice, if Smokey would ping the uses that have automatically flagged a false positive.

**Comment by quartata** [comment]
This should probably be moved to Metasmoke since the logic would be there (MS would broadcast the message to Smokey via ActionCable)

**Comment by quartata** [comment]
We can't be sure a user will be pingable though (or that we know their SE name if they didn't sign up with OAuth)

**Comment by Undo1** [comment]
Without superping ability (which requires a diamond), it's pretty difficult to do this reliably - especially with 200+ users in the mix, the vast majority of which don't visit chat. I think we'd be better served by pushing for https://meta.stackexchange.com/q/288120/215468.
