### ISSUE TITLE
Upgrade to Python 3.x

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#640]
Python 2 is dated and no longer receiving new features. It is still being maintained until 2020, so this is not a problem that needs to be solved immediately.

An upgrade to Python 3 will likely include upstream changes to ChatExchange as well.

**Comment by teward** [comment]
See the SmokeDetector-NG project - a Python 3 redo of SmokeDetector in Python 3.  That may be what you're after.  Until ChatExchange is Py3'd it'd be hard to make this fully Python3 as is (mixing versions is evil)

**Comment by AWegnerGitHub** [comment]
SmokeDetector-NG is very early in the development process and has been subject to a couple "is it really needed?" discussions. Without making a judgement on that project, this issue is a note that *at some point* SmokeDetector needs to support python 3.

**Comment by teward** [comment]
I have a local Py3 port already in progress. ChatExchange is the blocking problem for that migration..



*Sent from my iPhone.  Please excuse any typos, as they are likely to happen by accident.*

**Comment by ArtOfCode-** [comment]
Hang on, do we not use CE6? I thought we did...

**Comment by AWegnerGitHub** [comment]
I don't think we have CE6.

**Comment by Undo1** [comment]
For now, it's probably best to forget Smokey-NG even exists. If it turns into a feasible replacement, awesome! But if it dies or never reaches that state, we shouldn't stall out on development here.

**Comment by angussidney** [comment]
A nice-to-have would be to maintain cross 2/3 Python support, but that would probably take more effort than it's worth.

**Comment by teward** [comment]
@angussidney doable, but we need to have a working ChatExchange that works with both Py2 and Py3.  Otherwise we're going to have a mishmash of code that is evil to maintain.

**Comment by teward** [comment]
@Undo1 We could always fork ChatExchange under Charcoal-SE, import things from upstream as needed, and then make our CE Py3-converted.  Just to make sure it all works.

**Comment by ArtOfCode-** [comment]
@teward That's what ChatExchange6 is - Python 2 and 3 compatible.

**Comment by teward** [comment]
@ArtOfCode- Can we verify we are on CE6 or not?

**Comment by ArtOfCode-** [comment]
@teward https://github.com/Charcoal-SE/SmokeDetector/issues/640#issuecomment-294023737

**Comment by quartata** [comment]
CE6 has been merged into CE last I checked. I've been using ChatExchange on master in Python 3 projects just fine.

**Comment by ArtOfCode-** [comment]
That would be convenient

**Comment by ByteCommander** [comment]
My ChatExchange6 fork got merged back into the main ChateExchange repo end of last year already by @ProgramFOX . It should be working now with both Python 2 and 3, although the current CI tests suggest that it might be failing on Python 2 currently... Don't know whether that is just an issue with the tests or the main code though, haven't been involved any more for a while.

**Comment by ArtOfCode-** [comment]
Works for us on Python 2, @ByteCommander

**Comment by AWegnerGitHub** [comment]
@teward It looks like you've gotten it to at least pass unittests on [Circle](https://circleci.com/gh/teward/SmokeDetector/11). I've gotten it to pass unittests on [Win10](http://chat.stackexchange.com/transcript/message/36774775#36774775) with a very minor fix.

I think those are big steps one and two. 

The minor fix: It was initially failing on reading the Smokey source files in `test_srccheck`. This is because of the foreign characters. I fixed this by changing the `open()` call to also include `encoding='utf-8'`. This may be needed in other areas (like where we check the `.txt` files.

**Comment by AWegnerGitHub** [comment]
I'm going to call this one done. We've been running Py3 for several days now.
