### ISSUE TITLE
'Why' output for blacklisted user appends http: even when there is no link

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#643]
When a user is blacklisted via the API rather than from chat, the 'why' data for the post states that the user was blacklisted by metasmoke. However, Smokey assumes that it will be recieving a link, so it automatically adds `http:` (shouldn't it prepend `https:` instead?). This means that sometimes the output says 

> Blacklisted for < bla > (< MS post >) by http:metasmoke

**Comment by ArtOfCode-** [comment]
FOR SCIENCE

**Comment by magisch** [comment]
Also for science
