### ISSUE TITLE
Come, see the violence inherent in the system!

### ISSUE THREAD

**Issue by fielding-spidermonkey** [Charcoal-SE/SmokeDetector#644]
My klempen has been radically and unceremoniously censored (HE COMES) by an overzealous misguided dudebro pegasister with clear intent to decentralize and displeasure, and I would like to lovingly yet threateningly express my surprised discombobulation to the United Nations and Slashdot through the following immortal words of wisdom past:

Ah! Now we see the violence inherent in the system! Come see the violence inherent in the system! Help! Help! I'm being repressed!

[Does this company not care about freedom of speech?](https://gaming.meta.stackexchange.com/questions/7918)

**Comment by ArtOfCode-** [comment]
Bloody peasant.

**Comment by magisch** [comment]
@ArtOfCode-  We're a company now, how exciting?

**Comment by quartata** [comment]
s/watery tart/community manager/ s/sword/doubled API quota/

**Comment by quartata** [comment]
Also I'm pretty sure it's "scimitar" not sword.

**Comment by fielding-spidermonkey** [comment]
CENSORSHIP
