### ISSUE TITLE
Correctly send html encoded characters in usernames

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/SmokeDetector#665]
Usernames with special characters like ö should be shown as such and not as their html encoding.  I don't expect to see ```&#246;``` when there is just an ö ...

Point in case : http://chat.stackexchange.com/transcript/message/36892937#36892937

Notice that the display_name is html encoded: https://api.stackexchange.com/docs/users-by-ids#order=desc&sort=reputation&ids=544779&filter=default&site=stackoverflow&run=true in the user object:

``` "display_name": "M&#246;rre" ```

So I think the correct action is to html-decode display_name and then post the UTF8 result in the chatroom message

**Comment by teward** [comment]
I believe this has been fixed in https://github.com/Charcoal-SE/SmokeDetector/commit/26c581a57620c057143f7450f230258c0c3fc561 but if it isn't, please open another issue about it.
