### ISSUE TITLE
Allow code admins to easily merge blacklist PRs

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/SmokeDetector#672]
> Allow code admins to reply to a “You don’t have code privileges” message to accept/reject the PR
<sup>[source](https://chat.stackexchange.com/transcript/11540?m=36877742#36877742)</sup>

The reply looks like this:

> You don't have code privileges, but I've [created a pull request for you](https://github.com/Charcoal-SE/SmokeDetector/pull/663).
<sup>[source](https://chat.stackexchange.com/transcript/message/36877699#36877699)</sup>

All that’s needed is to `POST` to [`https://api.github.com/repos/Charcoal-SE/SmokeDetector/pulls/:id/merge`](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button). However, by setting the `commit_message` query param to `Approved by <username> (<message permalink>)`, anyone can see who approved the blacklist later on.

To reject the PR, optionally `POST` to [`https://api.github.com/repos/Charcoal-SE/SmokeDetector/pulls/:id/reviews`](https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review) with `body` set to “Rejected by <username>,” `event` set to `REQUEST_CHANGES` and the `Accept` header set to `application/vnd.github.black-cat-preview+json` to create a review, then `PATCH` to [`https://api.github.com/repos/Charcoal-SE/SmokeDetector/pulls/:id`](https://developer.github.com/v3/pulls/#update-a-pull-request) with `state` set to `closed`.

**Comment by angussidney** [comment]
In the time that it takes to reply to the message, I can most likely open the PR and merge it. Is this really worth the dev time required to implement?

I've already started work on a userscript which allows you to toggle autopull on any given commit/PR, which would make the standard approach even faster.

**Comment by magisch** [comment]
@angussidney Mind you, a bunch of code admins don't have git rights so they can't merge PRs (like me).

**Comment by angussidney** [comment]
This was implemented a while ago; code admins can simply type !!/approve in a comment on the PR, and metasmoke will automatically merge it (as long as only the blacklists were modified and the PR was made by Smokey).

Please note that you will need to be added to [PullApprove](https://about.pullapprove.com/) for this to work. If you're already part of the Charcoal-SE organisation on Github (any team will do), you can simply make a PR to add your GitHub username to [this](https://github.com/Charcoal-SE/SmokeDetector/blob/master/.pullapprove.yml) file, or ask someone with push access to do it for you. If you're *not* already part of the Charcoal-SE organisation, then ping @ArtOfCode- and he can set you up.

A related !!/approve command for chat has been `status-deferred`. See #819.
