### ISSUE TITLE
!!/watch and friends should permit a bare dot if it's followed by a quantifier

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#6775]
### Is your feature request related to a problem? Please describe.

The error message you get when you post a regex with a bare dot is generally helpful, but distracting when you really did mean a bare dot.

### Describe the solution you'd like

As suggested by @ThatRyanPerson [in chat](https://chat.stackexchange.com/transcript/message/59765947#59765947),  
we could soften it up by allowing a bare dot if it is followed by a regex quantifier (`*`, `+`, `?`, `{0,9}`)

### Describe alternatives you've considered

Just living with having to `-force` when you want a bare dot is palatable, but not requiring it in all situations might be nice.

**Comment by makyen** [comment]
I disagree, at least with respect to `*` and `+`, and, to an extent, `{x,y}` (and limiting my disagreement on the `{x,y}` form largely depends on parsing out the values of `x` and `y` and making a judgement as to at what point we want the human to double-check).

The current check merely requires that the human double-check what they are doing and add `-force` if that's what they want to do. I'd rather SD error on the side of caution here and ask the human to double-check than error on the side of not adding a minor inconvenience to the person adding the watch/blacklist entry of having to relatively quickly edit their message to add `-force`, if it's really what they want.

**Comment by tripleee** [comment]
With no consensus on the usefulness of this, let's just close it. It can obviously be reopened if someone wants to revive the debate.
