### ISSUE TITLE
"Still up" in a chat reply should not be added as a comment

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#6786]
### What problem has occurred? What issues has it caused?

Suggested by @ThatRyanPerson: https://chat.stackexchange.com/transcript/message/60057794#60057794

### What would you like to happen/not happen?

We have recently been pointing out when a flagged post is not yet deleted even after a longish time (think hours) with a chat comment, but adding it to metasmoke is not useful, and having to manually remove it is a hassle.

Personally, I have increased my effort in this area in the last few weeks, but the practice has existed for I think several years.

**Comment by teward** [comment]
has it been considered to *not* reply directly to the link though?  ANd instead say "still up" and then directly post a link to the chat timeline?  I know, it doesn't fix the "it shouldn't be doing this commenting thing" but... there's an easy non-programatic fix for this: change your workflow.
