### ISSUE TITLE
Blacklisting twice quickly breaks Smoke Detector

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#679]
I guess the automation tries to work in the same directory where the previous merge is in progress.

Checking out into a temporary directory and removing that when the merge is done should work around this issue.

There have been multiple situations where Smokey needed operator intervention to get back on track; most recently, http://chat.stackexchange.com/transcript/message/37019763#37019763

**Comment by ArtOfCode-** [comment]
What exactly do you mean by "breaks"? It still seems to be running after the instance you linked.

**Comment by tripleee** [comment]
The five blacklisting requests were processed but the active Smokey instance did not pull them, even when I tried to force it.  I restarted ([chat](http://chat.stackexchange.com/transcript/message/37019909#37019909)) but it was stuck on last night's final commit. `!!/pull`, `!!/master` etc were all fruitless. Somehow then it came back to life after about an when I blacklisted something [again](http://chat.stackexchange.com/transcript/message/37020633#37020633) (I was imagining I would just be piling stuff into a queue of merged but unpulled commits but it went through to my surprise).  Glorfindel had issued a couple of `!!/report`s in the interim but other than that, it seemed to just chug along with yesterday's `master`.

**Comment by angussidney** [comment]
Possible alternate solution: prevent Smokey from accepting any more blacklist requests until the appropriate commit is pulled in.

**Comment by teward** [comment]
@angussidney I... don't think this is still an issue.  It looks like we have had multiple sequential blacklist requests that have since 'worked', is this still an issue?

**Comment by tripleee** [comment]
I have carefully avoided tripping this, and I imagine others have too. I don't think anything has changed in this part of the code since I reported this a few days ago.

**Comment by tripleee** [comment]
And looking at the code, I don't think it *could* avoid breaking if two blacklist requests came in close enough to each other.

The proposed fix adds a `threading.Lock()` as suggested by Art in chat.

(The many ways to exit the critical region are a hassle.  I left the final `deploy` checkout outside the critical region with some hesitation -- there is still a tiny race condition there.)

**Comment by tripleee** [comment]
For what it's worth, happened again this morning:

http://chat.stackexchange.com/transcript/11540?m=37184130#37184130

Also ping related [PR#695](https://github.com/Charcoal-SE/SmokeDetector/pull/695)

**Comment by tripleee** [comment]
PRR#695 updated, now with the lock covering everything with a simple `try`/`finally` block.

**Comment by tripleee** [comment]
PR merged, calling this done.

**Comment by tripleee** [comment]
The fix doesn't actually work, it's a partial remedy but there are still issues when multiple CI merges are in progress simultaneously.  Should this be reopened or should I create a new ticket?

**Comment by angussidney** [comment]
It seems to have worked: http://chat.stackexchange.com/transcript/message/37404310#37404310

**Comment by tripleee** [comment]
I have multiple occasions recently when multiple successful blacklisting requests in quick succession would cause Smoke Detector to stop reporting tpu- etc feedback and never pulling the merged commits.

For example, here: http://chat.stackexchange.com/transcript/message/37425827#37425827
(ending up [attempting to pull](http://chat.stackexchange.com/transcript/message/37425914#37425914) but failing, then eventually [rebooting](http://chat.stackexchange.com/transcript/message/37425965#37425965)).

And again at http://chat.stackexchange.com/transcript/message/37426300#37426300 with a [manual pull](http://chat.stackexchange.com/transcript/message/37426322#37426322) when I gave up on waiting for it.

**Comment by tripleee** [comment]
This was never solved completely.  I have submitted a new PR which should handle this (I hope) ... #1191

**Comment by Glorfindel83** [comment]
The last month, I've seen that whenever I go on a !!/watch spree, Smokey does autopull & restart. I never have to !!/pull manually anymore. Example [here](https://chat.stackexchange.com/transcript/message/41976041#41976041). So I guess this is fixed?
