### ISSUE TITLE
Adding bold URLs appears to have broken FIRE

### ISSUE THREAD

**Issue by DavidPostill** [Charcoal-SE/SmokeDetector#6867]
Adding bold URLs appears to have broken FIRE - the FIRE icon no longer appears in the SD chat reports.

![Screenshot - 09_04_2022 , 19_56_16](https://user-images.githubusercontent.com/7079224/162587997-f3abe847-40b6-4b4e-b272-8db0906b72fe.png)

**Comment by teward** [comment]
Question: shouldnt this bug be filed against FIRE and not SmokeDetector then?

**Comment by makyen** [comment]
This was resolved both by updating FIRE and by reverting the commit which added bolding to the post title. There will probably be further discussion as to having the title bold, but my position is that it should be something which is implemented in a userscript. If it is in SD, then it would need to be on a per-room basis.
