### ISSUE TITLE
Website Whitelist?

### ISSUE THREAD

**Issue by CalvT** [Charcoal-SE/SmokeDetector#699]
For blacklisting websites, we currently have a blacklisted website file, and Smokey has a command to add to it. For whitelisting websites, we have to submit a pull request to add to findspam.

Could a whitelist file and command be added to Smokey?

Obviously we would need to set some criteria first, such as how many fp's the website is getting to qualify for whitelisting etc. I'm thinking about websites such as regex101 and similar

**Comment by Glorfindel83** [comment]
A partial whitelist already exists [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L85), but this would definitely be a good addition.

**Comment by angussidney** [comment]
I'm going to merge this for now, but I think in future it might be a good idea to start work on a global whitelist (#490) which doesn't only work for LAEOA

**Comment by angussidney** [comment]
See #490
