### ISSUE TITLE
If a post reported with only experimental reasons gets true positive feedback, it should be reported in other rooms normally opted out of experimental reasons

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#7236]
Often, a clearly (to a human) spam post gets reported by SmokeDetector with only experimental reasons. Because of the experimental nature of these reasons and the higher chance of them being false positives, most rooms across the network don't get reports of such posts.

However, once a human has reviewed over an experimentally-reported post and given it true positive feedback, it means that they're affirming that it is in fact spam. But when this happens, the report is still not posted in the other rooms, meaning the time the post spends on the site is increased. As such posts don't get autoflagged, we often depend on users in other rooms from Charcoal HQ and those opted in to receive experimentally-reported posts on a specific site. This often leads to users having to [manually go to other rooms and ask for these to be flagged](https://chat.meta.stackexchange.com/transcript/message/9283219#9283219).

I propose that if a post gets reported for solely experimental reasons, and one or more humans have reviewed over the post and affirmed it to indeed be spam (by giving it true positive feedback), messages about it should be posted in other rooms that don't normally receive reports of experimentally-reported posts.

**Comment by tripleee** [comment]
I like the basic idea, but a single TP might not yet be sufficient. Requiring two is often not all that different in outcome, in my experience (I have been manually reporting posts to the Tavern when they remain up and have not been reported there because of the experimental reasons).

**Comment by codygray** [comment]
Additional discussion occurred in CHQ; excerpts follow:

> [gparyani:](https://chat.stackexchange.com/transcript/message/61857176#61857176) @Makyen Is https://github.com/Charcoal-SE/SmokeDetector/issues/7236 technically viable?

> [Makyen:](https://chat.stackexchange.com/transcript/message/61866844#61866844) Yes, but that doesn't mean that it's easy to get such to work or a priority to address that particular issue. In addition to the technical aspects, we'd have to separately get buy-in from each room to change the configuration of what gets posted in their room.

> [gparyani:](https://chat.stackexchange.com/transcript/message/61879756#61879756) As far as I'm aware, for most outside rooms, they didn't explicitly state they didn't want experimental-only reports; it was simply a default condition we set unless they specifically wanted such reports. I don't think this would be a road-block. We can also make another role for rooms that later on object to it so such reports aren't posted.)

> [Makyen:](https://chat.stackexchange.com/transcript/message/61882596#61882596) :61879756 I disagree. There's a mix of some rooms having been explicitly asked and some rooms having been set based on the assumption of what they'd want. To cover bases, we'd need to explicitly ask each room.
