### ISSUE TITLE
Update ChatExchange

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#741]
We are a month or two out of date on our version of ChatExchange. There have been a few updates and feature additions.

Specifically, I'd like to use the new [`last_message` property on users that was merged last week](https://github.com/Manishearth/ChatExchange/pull/144). 

This will be used to add a new feature to Smokey. 

![WHOIS](https://i.imgur.com/FHTkqET.png)

I see such a feature being useful to both new and existing users so that immediate problems can be resolved more quickly, and so that users can quickly see who can help them. 

The reason I'm adding this as an issue is because this will require all Smokey instances to update the submodule.

**Comment by ArtOfCode-** [comment]
Pretty sure I'm live at the moment. Gimme a few.

**Comment by ArtOfCode-** [comment]
Turns out this actually just needs someone to update CE in the repo, and a standard pull will apply it to Smokey instances. Currently-live instance is up-to-date with CE, others will be when they do a pull - calling this done.
