### ISSUE TITLE
Minor phrasing problem in training documentation 

### ISSUE THREAD

**Issue by protagnost** [Charcoal-SE/SmokeDetector#7651]
In the Charcoal training documentation, on the page "[4. Handling Reports](https://charcoal-se.org/training/reports)", under [Self-Promotion](https://charcoal-se.org/training/reports#self-promotion), the second bullet point reads: 

> On sites you’re familiar with, many well-meaning users respond well a polite comment requesting the author to edit in disclosure.

I believe it is missing the word '_to_' ("_many well-meaning users respond well a polite comment_"), or I'm misinterpreting the sentence and it requires another construction.

**Comment by Spevacus** [comment]
Thanks for pointing this out! This is now repaired. See PR [#84](https://github.com/Charcoal-SE/charcoal-se.github.io/pull/84) over on our documentation repo.
