### ISSUE TITLE
A chat reply to a SmokeDetector report saying "r/a edit" gets converted to just "Edit" in the post's comment

### ISSUE THREAD

**Issue by jeffschaller** [Charcoal-SE/SmokeDetector#7657]
I replied to https://chat.stackexchange.com/transcript/message/63198866#63198866 with "r/a edit" expecting the resulting comment to say "r/a edit", but it instead says (https://metasmoke.erwaysoftware.com/post/418429): "Edit".

I believe the expected usage is to prefix a feedback status (tp/fp/etc), but I expected SD to bypass "r/a" as not-a-command and insert my entire reply as a comment.

**Comment by codygray** [comment]
`r/a` is a valid feedback alias. It corresponds to "true positive", just like `k` or `tp`.

You can see `r/a` in [the list of `TRUE_FEEDBACKS`](https://github.com/Charcoal-SE/SmokeDetector/blob/8b61697c76893ca8463e5f21d6b5c44d19dbf27e/classes/feedback.py#L28), a list which is used in [the `feedback` function](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommands.py#L2391), which processes feedback replies to SmokeDetector.

Therefore, this is [status-bydesign]. However, the documentation/wiki should probably be updated to contain a more exhaustive list of all these aliases.

**Comment by jeffschaller** [comment]
I just edited the wiki to list (what I think are) the missing commands.
