### ISSUE TITLE
Make append-only files easier to merge

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#776]
If a blacklist PR sits around for a while, it is likely to conflict with subsequent commits.  This is rather silly, because the files are basically append-only, and the conflicts are trivial to resolve.

http://stackoverflow.com/questions/34795604/does-git-support-automatic-merge-conflict-resolution-for-append-only-files outlines a way to tell Git how to resolve these conflicts automatically.  I'm proposing to take it into use.

**Comment by Undo1** [comment]
Makes sense to me. Curious whether GitHub will respect that setting, though.

**Comment by quartata** [comment]
This can be closed now.
