### ISSUE TITLE
Blacklisting is broken

### ISSUE THREAD

**Issue by quartata** [Charcoal-SE/SmokeDetector#788]
Using !!/blacklist-keyword or !!/blacklist-website results in the blacklist branch being created, but no commit or push is made. (As far as I can tell it makes it up to [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/gitmanager.py#L130), then dies somehow and doesn't throw an error because of the try).

**Comment by quartata** [comment]
Just confirmed that nothing is actually written to the blacklist file, meaning there's not really anything to commit. (Probably the issue)

**Comment by Undo1** [comment]
Fixed. Issue with git credentials not allowing push
