### ISSUE TITLE
Some non-useful patterns to remove

### ISSUE THREAD

**Issue by jdahobbs** [Charcoal-SE/SmokeDetector#790]
These website patterns have never produced a true positive and have several false positives:

* [`nfoodfacts.org`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=nfoodfacts.org&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) (4fp)
* [`boostsolutions.co`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=boostsolutions.co&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) (4fp)

Looking back through recent [false positive website pattern matches](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=&username=&why=&site=&feedback=false+positive&autoflagged=&reason=35&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) I'm also coming up with a bunch of odd one-offs that only ever had 1-2 false positives and never a true positive:

* [`http://nightlifer.new-norm.pro/`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=http%3A%2F%2Fnightlifer.new-norm.pro%2F&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
* [`wholesaler.co`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=wholesaler.co&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
* [`ituredeal.co`](https://metasmoke.erwaysoftware.com/search?autoflagged=&body=ituredeal.co&commit=Search&feedback=&feedback_filter=fp&reason=&site=&title=&user_rep_direction=%3E%3D&user_reputation=0&username=&utf8=%E2%9C%93&why=),
* [`agingwpblog.wordpress.co`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=agingwpblog.wordpress.co&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)

Also the keyword `coins` only matches [2 tp's 4-5 months ago](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=coins&username=&why=&site=&feedback=&autoflagged=&reason=102&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) and nothing since.

**Comment by tripleee** [comment]
(Sorry for the random spam here; typo.)
