### ISSUE TITLE
Detect when web socket connection to chat is lost

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#797]
Over the last week, Smoke Detector has lost it's connection to the chatrooms more than once, but has *not* crashed. This leads to a zombie version running as it can't be interacted with in any room. To force a reboot requires hacky forcing of a commit that is autopulled (or [development time on the metasmoke side](https://github.com/Charcoal-SE/metasmoke/issues/183)).

Smoke Detector, itself, should be able to determine when it loses connection to a chatroom and re-establish this connection (or restart)

**Comment by ArtOfCode-** [comment]
This has been running in prod without issues for ~24h, calling this closed.
