### ISSUE TITLE
Repeated letter in question may need a little tweaking:

### ISSUE THREAD

**Issue by durron597** [Charcoal-SE/SmokeDetector#81]
It seems like this question ought to have been caught:

http://stackoverflow.com/questions/31643388/no-gateway-trying-to-portfoward

> **i do ipconfig /all, it gives me a blank gateway.
The gateway it gives me is not in the standard form
the first LETTER of the gateway is F**

> > HEEEEELLLP

**Comment by durron597** [comment]
Outside the scope. 

> we don't want to catch them, since there'd be too many and smokey isn't for closing questions but flagging questions as rude/spam/defacing

http://chat.meta.stackexchange.com/transcript/message/3751729#3751729

**Comment by Undo1** [comment]
Really, this kind of thing makes me wonder if SmokeDetector should just be a websocket + chat platform, with an easy way to plug in filters for whatever you want it to do. I.e. we could have a spam chatbot, with a set of filters designed for spam, then an LQ chatbot, with filters and logic for close-worthy stuff, etc. Might make things more maintainable.

Although it's not really a maintenance nightmare *yet*, so meh.

**Comment by normalhuman** [comment]
An interesting idea. When I (briefly) considered adapting SmokeDetector to a different purpose, (detecting homework dumps on math-se) one annoyance was that the logic of what goes into what room is scattered throughout. The room numbers are defined in a separate module, but the room names are still hard-coded as "charcoal_hq", "tavern", etc, and there isn't an easy way to say what should be done where. 

I don't know what's more logical: have sets of rules associated with rooms (repetition of rules) or having a  "rooms" property of every rule, with its value being an array of rooms where this rule is in effect.
