### ISSUE TITLE
Prevent potentially-offensive keywords/usernames from being posted in special rooms

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/SmokeDetector#811]
Original suggestion from Catija and snailplane: https://chat.stackexchange.com/transcript/message/37843634#37843634

It'd be cool if we could look at building in a way to stop potentially offensive post titles/usernames from being posted in special rooms. CHQ can still have them posted - it's an occupational hazard there - but special rooms that just get occasional reports to help out don't particularly need to have offensive stuff hurled at them. (It's also more likely to get us flagged, which looking at Smokey's suspension history isn't exactly *rare*.)

**Comment by AWegnerGitHub** [comment]
That last statement is a bit misleading. The vast majority of Smokey's suspensions are testing suspensions. There are 6 automated ones for inappropriate content and the last one of those was in October of 2015.

**Comment by ArtOfCode-** [comment]
*shrug*. Just an incidental note. None of this has actually been a major problem.

**Comment by Undo1** [comment]
Mostly oppose - seems like a fairly major change for something that doesn't seem like a Real Problem. Additionally, if automatic deletion is enabled in those rooms (should be) the lasting impact is minimal.

If we're not already doing automatic deletion outside of the Tavern, we should start.
