### ISSUE TITLE
Add !!/approve command

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#819]
With the new PullApprove integration, it'd be nice if we could add an "!!/approve" to the issue from SE Chat.

This will probably need the following changes:

 - Code admin access level will need to be checked in Smokey. 
 - User that requested the PR still shouldn't be able to approve it (or should they?). This is assuming the approval will be posted as either Smokey or Metasmoke and just mention which user approved it (possibly with a link to chat)

**Comment by ArtOfCode-** [comment]
Code admins can approve PRs *or* directly blacklist, so we don't actually have problems about authors approving their own requests. The only time approvals come into it is if a non-code-admin fires a blacklist request, in which case they can't approve it because they're not a code admin.

**Comment by tripleee** [comment]
Why was this closed? Is there code which allows us to !!/approve from chat now? (Or should #886 be reopened?)

**Comment by ArtOfCode-** [comment]
because [status: deferred]. If/when someone gets around to finishing this, it can get reopened.

**Comment by angussidney** [comment]
Not much point having this one as a chat command; in order to find out the PR number you have to open up GH, where you can easily type the approve command anyway. I'm happy to leave this one closed.

**Comment by ArtOfCode-** [comment]
You *can* hover the link to find the number, but I tend to agree it's marginal value - which is why status-deferred.
