### ISSUE TITLE
Prevent TravisCI build on blacklist requests/watchlist requests

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#828]
Is there a way to prevent Travis builds on blacklist requests/watchlists? There are no specific unit tests tied to the individual blacklist items.

**Comment by AWegnerGitHub** [comment]
Would there be any unintended side effect of putting `[ci skip]` on these commits?

https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by j-f1** [comment]
Not AFAIK. It should probably get added to the pull request title so that it shows up in the merge commit, too.

**Comment by ArtOfCode-** [comment]
Honestly, I'd quite like to keep CI, at least on the merge commits. Given that blacklist commits are auto generated, if the generator goes wrong, CI gives us a chance at catching it before it goes live. I can get behind skipping it on the branch commit, that'd save us a couple minutes, but for the merge to master I think we can trade two minutes for a sanity check.

**Comment by AWegnerGitHub** [comment]
What are you expecting to catch, @ArtOfCode-? 

We don't have tests to test the new blacklist items.

**Comment by ArtOfCode-** [comment]
No, but we do test datahandling, which is the most likely candidate to break if a generator messes up a format or similar.

**Comment by angussidney** [comment]
Note that we do have some unit tests to prevent duplicate blacklist entries etc. however, I think Smokey intercepts these blacklists before they are commuted, so I think shouldn't be much of a problem. 

Currently, Smokey requires the CI build to pass before it pulls the commit in. Will some changes be required for Metasmoke in order to allow no CI build at all?

**Comment by ArtOfCode-** [comment]
Nope, @angussidney - just remove `or not states` from [this line](https://github.com/Charcoal-SE/SmokeDetector/blob/75dad4e3a036b2d3cbaae389dd50d6c8f127710b/chatcommands.py#L688) and you're good.

**Comment by quartata** [comment]
I think most of us agree that we should keep CI on blacklist items (especially considering we do actually have tests for rogue regexes), so this should probably be closed.

**Comment by teward** [comment]
We have requests that arent compliant with regex format AND we need to CI
test new blacklist or watchlists because they break Python or such.

-1 on the request to not run  CI for blacklist/watchlist requests.

**Comment by quartata** [comment]
Precisely. A minute's wait isn't a huge deal (especially since currently it's still blacklisted locally anyways).

**Comment by Undo1** [comment]
Kinda late, but 100% agree that we should be keeping CI on blacklist PRs.
