### ISSUE TITLE
Wrong link in 'Merged' chat message after !!/approve

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#842]
After an !!/approve comment, Smokey will post a [chat message](https://chat.stackexchange.com/transcript/message/38128174#38128174):

> Merged SmokeDetector #841.

However, the link to the PR is wrong, it should be 'pull'

    https://github.com/Charcoal-SE/SmokeDetector/pull/841

instead of 'pulls'

    https://github.com/Charcoal-SE/SmokeDetector/pulls/841

**Comment by ArtOfCode-** [comment]
[Charcoal-SE/metasmoke 58d6dfc](https://github.com/Charcoal-SE/metasmoke/commit/58d6dfc3bdead9ad0489b6f8fd1400fc9db7db11)
