### ISSUE TITLE
!!/allspam should report all the user's posts to metasmoke

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#852]
While [discussing !!/allspam](https://chat.stackexchange.com/transcript/message/38181920#38181920), @angussidney noted:

> Using !!/report with multiple arguments is preferred however, as then we get a copy of the post on MS, we can give feedback ,etc

While this is true, it's also more cumbersome (and not doable if the user has more than _x_ posts, as !!/report is rate limited). Instead, !!/allspam should be rewritten so that it reports all the user's posts to metasmoke.

Alternatively, we could make a new command !!/report-all &lt;link to user> for this.

**Comment by tripleee** [comment]
I agree that the requested behavior is what I naively expected from a command named like this.

**Comment by Undo1** [comment]
It'd be great to be able to report all of a user's posts network wide. That could be quota-expensive (1 to get the user's site account, another to get the assoc accounts, and then up to 300ish (usually nowhere near that, more like 5) to get all posts. 

Does anyone know of a more efficient way to get from a user to all their posts across the network?

**Comment by AWegnerGitHub** [comment]
We might be able to use http://api.stackexchange.com/docs/users-network-activity and use that to check recent posts. More than likely a true spammer only has a handful of things on this. That will at least narrow down which sites we have to query. 

We still need to go from user account ID->network activity->listed activity (times how ever many sites listed here)

**Comment by angussidney** [comment]
https://github.com/Charcoal-SE/SmokeDetector/tree/allspam

**Comment by quartata** [comment]
This is currently in the NG pull request: https://github.com/Charcoal-SE/SmokeDetector/pull/1135
