### ISSUE TITLE
Patterns for catching known spam domains

### ISSUE THREAD

**Issue by kevin-brown** [Charcoal-SE/SmokeDetector#86]
_I know that some of these are already in the system, but it was easier to include them here as some can be improved. These were compiled based on the [master spam list](http://meta.superuser.com/q/9249/72528) by @FieryDragonLord_

Here are a few patterns that catch most of [the "Repair Toolbox" domains][repair-toolbox]

```
filefix(er)?\.com
fix(.*)(file(s)?|tool(box)?)\.com
(recovery|repair)kit\.com
(repair|recovery|fix)tool(box)?\.com
\.repair
```

And some patterns for most of [the "Wise Recovery" domains][wise-recovery]

```
fix1\.org
easyfix\.org
errorsfixer\.org
regeasypro\.com
recoverypro\.(com|net)
smart(pc)?fixer\.(com|net|org)
wiserecovery\.com
drivertuner\.(com|net)
official-drivers\.com
wisefixer\.(com|net|org)
```

These patterns can match most of [the "Tenorshare" domains][tenorshare]

```
-recovery\.(com|net)
passwordcracker\.(com|net)
-password\.net
(windows(7-)?)?password(s)?(-)?(recovery|reset)\.(com|net)
lost(windows)?password\.com
tenorshare\.com
(downloader|pdf)converter\.(com|net)
```

Some for [the "iSpire/Wasel" domains][ispire]

```
i-spire\.net
iwasl\.com
qobul\.com
unblockingtwitter\.com
bestcheapvpnservice\.com
openingblockedsite\.com
arabic(soft)?download(s)?\.com
(vpn|internet)?wasel(pro)?\.com
vpn(faqs|answers)\.com
```

[ispire]: https://gist.github.com/kevin-brown/3f22cd3cda906a60012a#file-ispire-txt
[repair-toolbox]: https://gist.github.com/kevin-brown/3f22cd3cda906a60012a#file-repair-toolbox-txt
[tenorshare]: https://gist.github.com/kevin-brown/3f22cd3cda906a60012a#file-tenorshare-txt
[wise-recovery]: https://gist.github.com/kevin-brown/3f22cd3cda906a60012a#file-wise-recovery-txt

**Comment by normalhuman** [comment]
[Implemented now, thanks](https://github.com/Charcoal-SE/SmokeDetector/commit/5b3b88682c9a7bdbb96b06610a7fadbee70060ba)
