### ISSUE TITLE
Feature request: the ability to revoke your own PR

### ISSUE THREAD

**Issue by fastnlight0** [Charcoal-SE/SmokeDetector#8642]
### Is your feature request related to a problem? Please describe.
Not really, as you can request for a blacklister to reject your PR, but it would make the blacklister's life easier if someone could do it themselves.

### Describe the solution you'd like
Either a `!!/revoke` command, or the ability to `!!/reject` yourself

### Describe alternatives you've considered
As mentioned above, you can request for a blacklister to do it, but many people would prefer having this possible

### Additional context
None.

**Comment by gparyani** [comment]
FYI: this was already requested as #1639 and declined.

**Comment by gparyani** [comment]
@fastnlight0 D'oh, got it confused. Stoopwafel-ified.
