### ISSUE TITLE
Blacklisting (watch etc) without restarting Smokey

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#882]
`!!/blacklist` and related commands currently force SmokeDetector to exit with a particular exit code in order to reinitialize it with an updated blacklisting database.

This seems mildly excessive and moderately disruptive.  Updating the affected blacklist in memory would avoid some failure scenarios and probably improve the user experience.

**Comment by tripleee** [comment]
I believe Angus was planning to work on this.  I'm creating a ticket for visibility and coordination.

**Comment by tripleee** [comment]
Brief plan: https://chat.stackexchange.com/transcript/message/38369083#38369083

**Comment by angussidney** [comment]
Started: https://github.com/Charcoal-SE/SmokeDetector/tree/no-restart-blacklists

**Comment by angussidney** [comment]
Not quite fixed yet
