### ISSUE TITLE
!!/approve in chat is broken

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#886]
Based on a single incident, I speculate that there is a problem with Metasmoke, ~~possibly related to the one which causes AIM to currently malfunction.~~

https://chat.stackexchange.com/transcript/message/38420604#38420604

Transcript:

> tripleee> `!!/approve https://github.com/Charcoal-SE/SmokeDetector/pull/884`

> SmokeDetector> 
`@tripleee Forwarding request to metasmoke returned HTTP 404. Check status manually.`

**Comment by tripleee** [comment]
Angus tells me this never worked in chat but I'll leave this open as a reminder.

**Comment by ArtOfCode-** [comment]
Angus is correct, I never fixed it

**Comment by ArtOfCode-** [comment]
Also, the format is `!!/approve <number>`,rather than with a URL

**Comment by angussidney** [comment]
Closing as duplicate of #819
