### ISSUE TITLE
Wiki link in the readme is broken

### ISSUE THREAD

**Issue by Quincunx271** [Charcoal-SE/SmokeDetector#893]
The README says

> User documentation is in the [wiki](https://charcoal-se.org/smokey).

It links to `https://charcoal-se.org/smokey`. This link is broken; it redirects to a 404.

**Comment by Quincunx271** [comment]
A fix is to link to `https://charcoal-se.org/smokey/` instead

**Comment by j-f1** [comment]
Should be fixed now. Thanks for reporting this!
