### ISSUE TITLE
Feature req: case-sensitive blacklisting

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#948]
I created a watch for "mohit kumar".  I wanted to create a case-sensitive blacklist entry but I was unable to.

Python `regex` says
```
>>> r = regex.compile(r'(?i)\b(key|words|((?-i)mohit kumar))\b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tripleee/charcoal/SmokeDetector/.env3/lib/python3.5/site-packages/regex.py", line 345, in compile
    return _compile(pattern, flags, kwargs)
  File "/Users/tripleee/charcoal/SmokeDetector/.env3/lib/python3.5/site-packages/regex.py", line 501, in _compile
    caught_exception.pos)
_regex_core.error: bad inline flags: cannot turn flags off at position 23
```

The current situation leads to false positives like this one:

https://chat.stackexchange.com/transcript/message/38729236#38729236

**Comment by tripleee** [comment]
For the record, I removed the entry for `mohit kumar`: https://github.com/Charcoal-SE/SmokeDetector/commit/93bef5e

**Comment by quartata** [comment]
It would be nice to have a general "flags" system for blacklist entries -- being able to toggle things like word boundaries and case sensitivity rather than having clunky separate blacklists for them.

**Comment by iBug** [comment]
Contact Smoke Detector Customer Support Number at https://pypi.org/project/regex/ . We're a professional team at providing support for regular expressions, case-sensitive regular expressions, regular expression customer support number.

Here's a brief note of our service. You can find the full service information on our website :>>>> https://pypi.org/project/regex/

> Scoped flags (issue #433028)
>
> `(?flags-flags:...)`
>
> The flags will apply only to the subpattern. Flags can be turned on or off.

```
(?flags-flags:pattern)
             ^
```

**Comment by iBug** [comment]
```
>>> r = regex.compile(r"(?i)\b(aaa|(?-i:bbb))\b")
>>> r.match("aaa")
<regex.Match object; span=(0, 3), match='aaa'>
>>> r.match("aAa")
<regex.Match object; span=(0, 3), match='aAa'>
>>> r.match("AAA")
<regex.Match object; span=(0, 3), match='AAA'>
>>> r.match("BBB")
>>> r.match("BbB")
>>> r.match("bbb")
<regex.Match object; span=(0, 3), match='bbb'>
```
