### ISSUE TITLE
Posts which trigger only experimental reasons should only generate notifications in Charcoal HQ

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#949]
There is a code path which is supposed to do this, but it's apparently not working.  Here is an experimental-only hit which was evidently reported in SObotics:

https://chat.stackexchange.com/transcript/message/38729208#38729208

**Comment by tripleee** [comment]
Looks like it actually works precisely the wrong way around!

https://metasmoke.erwaysoftware.com/post/76990 only triggered an experimental (watch) reason. It was [not reported in Charcoal](https://chat.stackexchange.com/transcript/message/38869987#38869987) but [was reported in SOCVR](https://chat.stackoverflow.com/transcript/41570?m=32819119#32819119).

**Comment by ArtOfCode-** [comment]
Sounds like someone over-negated a boolean....

**Comment by tripleee** [comment]
Closing as hopefully fixed.  We'll have to wait for a low-score post to see whether it behaves as expected but if not, just reopen.

**Comment by tripleee** [comment]
This one was reported in Charcoal and I believe only in Charcoal, so this seems to be properly done:

https://chat.stackexchange.com/transcript/message/38894750#38894750

Tangentially, that's an FP related to https://github.com/Charcoal-SE/SmokeDetector/issues/948
