### ISSUE TITLE
Feature Request: unshorten links and evaluate the resolved URL

### ISSUE THREAD

**Issue by ByteCommander** [Charcoal-SE/SmokeDetector#953]
The "shortened URL" detections could be improved by actually resolving and unshortening those shortened links and checking whether they redirect to a legit or malicious site.

One way to do this would be by simply sending a HEAD request allowing redirections and then checking the URL of the response, as suggested on https://stackoverflow.com/a/30156125/4464570: 

    def unshorten_url(url):
        return requests.head(url, allow_redirects=True).url

Another way could be using an unshortening API. To me after a bit of research, https://unshorten.me/api looked most promising. Their default free plan allows you 10 requests about new shortened URLs per IP per hour. However, if an URL had been requested once by anybody already, they have the result in their database and querying that doesn't increment the counter. In Python this could look like:

    def unshorten_url(url):
        return requests.get("https://unshorten.me/json/" + url).json().resolved_url
        # .json() output example: 
        # {'resolved_url': 'https://unshorten.me/', 'success': True, 
        #  'usage_count': 0, 'requested_url': 'http://goo.gl/IGL1lE'}

After unshortening the links, the post could either be evaluated as if posted with the direct link, or with a little additional weight because of the shortener.

Suggestions? Comments? Opinions?

**Comment by ArtOfCode-** [comment]
I like it. If we can use requests we may as well, instead of adding another external dependency.
