### ISSUE TITLE
'Bad pattern in url answer' triggers on Stack Exchange links

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#954]
See this post: https://metasmoke.erwaysoftware.com/post/76449
Smokey triggers on the following URL:

    https://askubuntu.com/questions/77655/how-do-i-enable-ntfs-write-support

Stack Exchange links should be whitelisted for this rule (and maybe others, if that isn't already covered).

**Comment by angussidney** [comment]
It's already whitelisted for other rules, but not this one by the look of it

**Comment by ByteCommander** [comment]
It also doesn't like the ubuntu.com site for some reasons...

https://m.erwaysoftware.com/posts/by-url?url=//askubuntu.com/a/294693

    Post - Bad fragment in link http://www.ubuntu.com/download/desktop/install-desktop-long-term-support

**Comment by tripleee** [comment]
Shouldn't be hard to fix, but could we refactor to a centrally-managed reusable method or (gulp!) regex fragment while we are at it?

If nobody else takes this, I can look at it tomorrow.

**Comment by tripleee** [comment]
I believe this is fixed now.  Sorry for the slightly messy commits.

**Comment by tripleee** [comment]
For the record, I have not whitelisted ubuntu.com which isn't a Stack Exchange site. We might want to whitelist it for other reasons but the scope of this problem is purely SE sites IMHO.
