### ISSUE TITLE
Add a link rel="shortcut icon" so the https://charcoal-se.org/ tabs are easy identifiable

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/SmokeDetector#975]
Something like this in the head

```
    <link rel="shortcut icon" 
            type="image/png" 
            href="/assets/charcoal-c0d57d82868cf7a8b169cfaf65a45179467c310868ebfdd0f10e6bd48f068816.png" />
```

as that image is already served you could hope it comes from cache (but I see no-cache control headers so that hope is shattered)

I tried looking for your page template but couldn't find it, hence this issue.

**Comment by j-f1** [comment]
The template is in https://GitHub.com/Charcoal-SE/charcoal-jekyll-theme.

**Comment by tripleee** [comment]
I created a tentative pull request https://github.com/Charcoal-SE/charcoal-jekyll-theme/pull/1 but I have no idea if I put this in the correct place.
