### ISSUE TITLE
Add multiple "few unique characters" reasons based on the number of unique characters

### ISSUE THREAD

**Issue by bwDraco** [Charcoal-SE/SmokeDetector#986]
Currently, the "few unique characters" reason is triggered in essentially the same way if a post has just two unique characters or as many as 15. This degrades the validity of this reason as a determinant of spam and hurts autoflagging accuracy.

I would suggest splitting this reason up into several separate reasons, like "5/10/15 or fewer unique characters in title/question/answer". We could go so far as to have individual reasons for each number of unique characters, though this would probably add a significant amount of complexity and would be computationally expensive.

[This chat conversation](https://chat.stackexchange.com/transcript/11540?m=39047704#39047704) provides some context behind this issue.

**Comment by tripleee** [comment]
Could you point to posts where this makes a difference? Does it really make a difference for proper spam (not rude/abusive/vandalism)?

**Comment by angussidney** [comment]
After all, vandalism is only a side-effect of our spam searching and not the focus of our organisation.

**Comment by bwDraco** [comment]
I guess there is little interest in this feature.

Closing.
