### ISSUE TITLE
What feedback is appropriate for repairable offensive posts?

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#995]
Case in point: https://m.erwaysoftware.com/posts/by-url?url=//stackoverflow.com/a/45460636
Some (non-native) speakers think *f\*cking* is a synonym for *very*. Smokey reports them, we edit out the rude language and leave a comment.

What feedback is appropriate in this case?

Arguments for `tpu-`:
- It's rude, and `rude` is synonymous to `tpu-`

Arguments for `tp-`:
- Doesn't blacklist the user.
- Like vandalism, this is something the community can resolve.

Arguments for `fp-` (or `naa-` when appropriate):
- Doesn't blacklist the user.
- The post itself is (potentially) valuable so we don't want it as a system block.

I was (when this case was posted) in the `fp-` camp, but I'm slowly leaning towards `tp-` now. Whatever the outcome, it's good to add this case to the [Feedback Guidance wiki page](https://charcoal-se.org/smokey/Feedback-Guidance).

**Comment by ArtOfCode-** [comment]
The post itself is (potentially) valuable so we don't want it as a system block.

In my opinion, that's the test. We wouldn't want to implement a system-level block against this, so it's an FP.

**Comment by Undo1** [comment]
Adding to Art's answer, these aren't even flaggable. We (I, at least) decline red flags on bad language used within an otherwise good post - with the reasoning that all we'll do is edit it out, so you should just do it yourself.

**Comment by Glorfindel83** [comment]
Well, the system block could be a warning like 'Your post contains offensive language, are you sure you want to post it?'. But if you both think it's fp-, that probably defines policy on this matter and I will update the wiki.
