### ISSUE TITLE
tpu- by <Charcoal member> on <old post> is not shown

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#997]
At [this moment](https://chat.stackexchange.com/transcript/message/39196627#39196627), Smokey does report `tpu- by` for the last reported post, but not for older ones. It used to report something along the lines of

> tpu- by <Charcoal member> on <old post>

**Comment by Undo1** [comment]
Should be a metasmoke issue. Let me take a look.

**Comment by Undo1** [comment]
https://github.com/Charcoal-SE/metasmoke/commit/b3febb5a57354807ab32b38ac20d28dedcd71c61?diff=unified#commitcomment-23458586

**Comment by Glorfindel83** [comment]
@Undo1 it [seems to have been fixed](https://chat.stackexchange.com/transcript/message/39220686#39220686), so I'll close it now.

**Comment by Undo1** [comment]
Ghosts.

**Comment by ArtOfCode-** [comment]
Suspect it was down to sending these from review as well, actually - the bit that added the link had a bug, but for those without links it was fine.
